### ISSUE TITLE
Metric does not support optional values

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#102]
The Metric class does not support optional values via `Option[Type]`.  This would be nice as there are definitely cases where some values are optional, and not necessarily present.

**Comment by tfenne** [comment]
Outputting is relatively simple (see `PickLongIndices`' `IndexMetric` for an updated `formatValues` method), but reading back doesn't work as expected.

**Comment by nh13** [comment]
@tfenne  I think we have to agree on how to represent `None` on disk, which also affects arg-parsing (see https://github.com/fulcrumgenomics/dagr/pull/197).  The special token for `None` was proposed to be `<None>`.  What do you think?
