### ISSUE TITLE
Improve the parallel collection support

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#103]
Instead of this:

```
val parIter = iter.par
parIter.tasksupport = new ForkJoinTaskSupport(new ForkJoinPool(threads))
val result = parIter.map(x => doWork(x))
```

something like:

```
val result = iter.withPar(threads).map(x => doWork(x))
```

and something like this:

```
val threadPool: ForkJoinPool = ...
val result = iter.withPar(threadPool).map(x => doWork(x))
```

The latter is useful if we have multiple parallel collections.

**Comment by nh13** [comment]
Consider: https://github.com/tim-group/iterata/

**Comment by tfenne** [comment]
@nh13 Did the addition of the implicit class `ParSupport` to `CommonsDef` solve this or is this something else?
