### ISSUE TITLE
HapCutToVcf: `FORMAT/PR` has no header entry

### ISSUE THREAD

**Issue by jaredo** [fulcrumgenomics/fgbio#115]
Hi again,

Just noticed a format field has no header entry:

```
$ java -jar fgbio-0.1.2-SNAPSHOT.jar HapCutToVcf -v ../NA12878.1000G.vcf -i na12878.output_haplotype_file  -o test.vcf.gz
$ bcftools view test.vcf.gz > /dev/null 
[W::vcf_parse_format] FORMAT 'PR' is not defined in the header, assuming Type=String
```

**Comment by nh13** [comment]
Is the PR field in the input VCF? I'll try to take a look today?

**Comment by jaredo** [comment]
I think `PR` is generated by HapCut2 and then I think fgbio tries to propagate it. It wasn't in the provided vcf. 

It looks like there is some code in HapCutToVcf to add the relevant header in https://github.com/fulcrumgenomics/fgbio/blob/37767f80f02f08fcd44b12db6cda8cc1f5f7926b/src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala#L210

**Comment by nh13** [comment]
I have a fix that will be merged after tests pass here: https://github.com/fulcrumgenomics/fgbio/pull/116
