### ISSUE TITLE
GroupReadsByUmi returns empty bam

### ISSUE THREAD

**Issue by mh1111** [fulcrumgenomics/fgbio#123]
Hi folks, 

First of all, many thanks for providing this nice package. I just started using fgbio to deal with sequences that use some customized UMIs. I could successfully annotate my bam file with UMI tags. Bam file looks like the following after annotating with AnnotateBamWithUmis: 

 NS500607:25:HGWNLBGXY:4:11404:10042:8605	99	chr1	836282	60	74M	=	836455	247	GTGAATCTAAAACCGTTCTTTAAAAAGAGTTTATTTAGTAGGCTGGGCATGGTGGCTCACACCTGCAATCCCAG	AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEE	X0:i:1	X1:i:0	MD:Z:74	XG:i:0	AM:i:37	NM:i:0	SM:i:37	XM:i:0	XO:i:0	XT:A:U	RX:Z:AGGGCTTAACGC
NS500607:25:HGWNLBGXY:4:11406:25080:7099	99	chr1	836282	60	74M	=	836455	247	GTGAATCTAAAACCGTTCTTTAAAAAGAGTTTATTTAGTAGGCTGGGCATGGTGGCTCACACCTGCAATCCCAG	AAAAAEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEE	X0:i:1	X1:i:0	MD:Z:74	XG:i:0	AM:i:37	NM:i:0	SM:i:37	XM:i:0	XO:i:0	XT:A:U	RX:Z:AGGGCTTAACGC

Please note that mates are also in the bam file, but not shown here. 

So the issue is with GroupreadsByUmi: nothing is written in the output bam (empty file). Following is the log output:

[2016/11/02 17:17:28 | FgBioMain | Info] Executing GroupReadsByUmi from fgbio version 0.1.2-SNAPSHOT as mh1111 JRE 1.8.0_73-b02
[2016/11/02 17:17:28 | GroupReadsByUmi | Info] Filtering and sorting input.
[2016/11/02 17:17:44 | GroupReadsByUmi | Info] Assigning reads to UMIs and outputting.
[2016/11/02 17:17:44 | FgBioMain | Info] GroupReadsByUmi completed. Elapsed time: 0.33 minutes.

I also run the code as: 

java -Xmx32g -jar ~/src/fgbio/target/scala-2.11/fgbio-0.1.2-SNAPSHOT.jar GroupReadsByUmi -i input_bam.bam -s edit -e 2 -m 20 -o output_bam.bam --tmp-dir=../tmp

I would be very grateful if you could please help me out to fix this. It is very hard to figure this out as I do not get any error message. 

Cheers,
MH

**Comment by nh13** [comment]
Likely the easiest way to debug this would be to share a small snippet of the input BAM file to `GroupReadsByUmi`.  Would you be able to send us say the first few hundred reads?  For example, using samtools:
```
samtools view -H input_bam.bam > debug.sam
samtools view input_bam.bam | head -n 500 >> debug.sam
samtools view -Sb debug.sam > debug.bam
```
My gmail is "nilshomer".

**Comment by mh1111** [comment]
Thank you for your prompt reply Nils. I just emailed you debug.bam. 

Cheers,
MH

**Comment by tfenne** [comment]
@mh1111 Thanks for providing the BAM for debugging.  After staring at things for a few minutes I think I see what's going on.  The tool filters out reads with mapq < 10 _and_ mate mapq < 10.  To do the latter it expects that `MQ` (mate mapping quality) optional tag to be present on reads with mapped mates, and drops reads that don't have it set.

The quickest way for you to get results will be to run fgbio's `SetMateInformation` on your BAM.  

We should add to the documentation that the MQ tag is required (sorry about that), and this also makes me think that perhaps we should emit counts of filtered reads by reason so it's clear why reads are being dropped.

**Comment by mh1111** [comment]
@tfenne thank you very much for letting me know about the required MQ tag. I was in the middle of testing what you suggested that our cluster just crashed! :( 
I will get back to you as soon as I had a chance to test it. 

Again, thank you and @nh13 for your prompt assistance. 

Cheers, 
MH

**Comment by mh1111** [comment]
@tfenne you were exactly right. The issue was not having MQ tags in input BAM. After adding them, GroupReadsByUmi worked just fine! :) Thank you so much for your help. 

Just a side note; SetMateInformation needs input BAMs sorted by query name via SortSam class of picard. At first, I sorted input BAM via samtools sort -n and it didn't work. I am guessing samtools and picard use different methods for sorting based on query name.

Cheers,
MH
