### ISSUE TITLE
likelihood model of CallMolecularConsensusReads

### ISSUE THREAD

**Issue by mh1111** [fulcrumgenomics/fgbio#130]
Hi folks, 

We have successfully used AnnotateBamWithUmis, GroupReadsByUmi and CallMolecularConsensusReads pipeline and we are very pleased with the fgbio package so far. Hats off to the developers! 
I was wondering if you have additional documentation online beyond what is provided by –help command. For example, in order to properly interpret the consensus reads, we are very interested to learn more about the likelihood model used in CallMolecularConsensusReads. Such information would be very helpful to adjust the input parameters such as --error-rate-pre-umi, --error-rate-post-umi, --max-base-quality, and --base-quality-shift to name a few. Another important question is about masking consensus bases. Does the package call ‘N’ solely based on --min-consensus-base-quality? 
Thank you very much in advance for your help. 

Cheers,
MH

**Comment by nh13** [comment]
Hey @mh1111, take a look at our wiki as we fortunately have a brief write-up: https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Consensus-Reads.  Feedback is always welcome.

**Comment by mh1111** [comment]
Thanks a lot @nh13 
The write-up is absolutely helpful. 

Cheers,
MH
