### ISSUE TITLE
Details on the likelihood model of CallMolecularConsensusReads 

### ISSUE THREAD

**Issue by mh1111** [fulcrumgenomics/fgbio#135]
Hi folks, 

I have a question about the write-up on the likelihood model of CallMolecularConsensusReads available here: https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Consensus-Reads

Almost all of the parameters used in the model are described in the write-up, but unfortunately I could not find how Err_{post} and Err_{pre} are determined. More precisely, what are the factors affecting these error rates? And how one can set these two parameters given the quality of grouped reads by UMI? 

Thank you for your continued support, 
MH

**Comment by nh13** [comment]
@mh1111 examples of the types of processes are described in the glossary.  The types of errors and their frequency are highly dependent on the assay type and steps involved, and so the they really should be tuned (learned) from the data as well as set according to your intuition.  For example, how often does oxidation occur in your assay (pre) or how often does target capture introduce an error (post).  

We currently do not have any public tooling to examine the data and calibrate these values.  Nonetheless, we have found the default values in `CallMolecularConsensusReads` to work well.

**Comment by mh1111** [comment]
Thank you very much for your reply @nh13 

MH
