### ISSUE TITLE
AnnotateBamWithUmis with two UMIs

### ISSUE THREAD

**Issue by lindakohn** [fulcrumgenomics/fgbio#136]
Hi,
How will the AnnotateBamWithUmis tool work with two UMIs? I have reads with one UMI 5' of insert and one 3' of it.

**Comment by tfenne** [comment]
Hi @lindakohn - my apologies for not responding to your issue sooner.  `AnnotateBamWithUmis` is probably not the right tool for the job if you have inline UMIs (i.e. they show up in the template reads).  We have two other tools that could help you though.  If the reads are already in BAM format you could use `ExtractUmisFromBam` to extact the UMI bases into appropriate tags.  If you have fastq you could use `FastqToBam` to convert the data to BAM and extract the UMIs along the way.

Please feel free to re-open if you're still interested and this doesn't work for you.

**Comment by BigTA78** [comment]
The newer versions of Illumina's bcl2fastq support inline UMI's. You could remove PCR duplicates at the same point as demultiplexing/fastq building
