### ISSUE TITLE
SimpleCounter and NumericCounter should implement CanBuildFrom and maybe Map

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#160]
It would be nice to have the counter objects implement the CanBuildFrom interfaces so that you can manipulate their contents and get another counter back without a lot of extra effort.

Similarly it might be nice to implement immutable Map too to provide Map-like accessors?

**Comment by nh13** [comment]
I agree with this.  I am finding I am using these classes a lot more these days.

**Comment by tfenne** [comment]
Closing for now as a) we haven't done it and b) that code is now in commons.
