### ISSUE TITLE
Support for setting common/global options

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#182]
There are a number of options that are common to many, but not all, tools in `fgbio` that it would be nice to be able to have standard names for.  For example things that control some aspects of BAM and VCF writing like whether or not to create indices, what compression level to use, whether or not to enable async-io.

Perhaps we could convert `fgbio` to use the same `sub-command` model as `dagr` uses, and then define options to `fgbio` separately from options to the tools?  Then we could write things like:

`java -jar fgbio.jar --async=true DemuxFastqs --input ...`

**Comment by tfenne** [comment]
This will, of course, complicate generation of usages and param documentation though!

**Comment by nh13** [comment]
You don't want to use `java -Dasync=true`? 👍

**Comment by tfenne** [comment]
This just made it onto master and will be in 0.2.0.
