### ISSUE TITLE
Soft Clipped Bases 

### ISSUE THREAD

**Issue by ssaif** [fulcrumgenomics/fgbio#188]
Hello,

I was wondering if soft clipped bases, in Illumina HiSeq4000 data, are removed before consensus building? We have noticed a lot more longer insertions in our analyses when use all reads for a given UMI but don''t not in consensus build from 3 or more reads of a given UMI.

Thanks,
Sakina

**Comment by tfenne** [comment]
Hi @ssaif - sorry for not seeing this sooner.  Is this still something you're having an issue with?  There have been multiple updates to the consensus callers lately, which may relate to this.

In short the callers don't remove soft-clipped bases since we don't know in advance if they are clipped for quality, for being adapter, or perhaps because there is a real indel near the end of the reads.

We've recently added code to do things like trim reads back to their insert size if they are longer than the insert size, and also there's an open PR to do quality based trimming prior to consensus building.

**Comment by tfenne** [comment]
I'm closing this, but if a question remains please feel free to reopen.

**Comment by janrehker** [comment]
I would like to reopen this, as I am facing a similar phenomenon :)

After consensus calling, soft clipped bases get removed or partially removed in consensus sequences. At the moment I still cannot figure out any pattern, like base quality or mapping quality.
While some reads with low quality mapping/bases seem to pass, others get removed or partially removed.
It also happens that bases just at the beginning of the aligned part of the read get removed as well, which were not soft-clipped in the beginning.
Maybe you can elaborate a bit regarding the trimming that was integrated into the consensus caller?

Thanks,
Jan

**Comment by tfenne** [comment]
I realize the pages I'm linking to talk about duplex consensus calling, but the trimming stages are the same for both.  Take a look at this section on [Quality Trimming](https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads#quality-trimming) and this one on (Trimming To Insert Length)[https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads#quality-trimming].

**Comment by janrehker** [comment]
Is there a way to alter both? Having the 'trimming to insert' feature seems to be necessary regarding consensus calls for overlapping parts of a read pair. However I cannot figure out why it is needed in consensus calls from single-umi data.
While this hard-clipping does not affect calling of snp's and indels that much, it certainly does for translocations.

**Comment by tfenne** [comment]
You can effectively turn off the quality trimming by setting the `min-input-base-quality` to something suitably low.  It's already at Q10.

There's no way to turn off the insert-trimming but that's intended to only ever take off sequencing adapters.  I'd be curious how it's affecting your translocation calling.

**Comment by janrehker** [comment]
OK, the soft clipped sequences that get removed actually look like adapters. My bad :(
Maybe we can close this thread again?
Once I compared translocation calling on deduplicated and unaltered data I could still reopen it if there are issues.

Thanks, Jan
