### ISSUE TITLE
segmentation fault error during haplotype calling

### ISSUE THREAD

**Issue by madhubioinfo** [fulcrumgenomics/fgbio#201]
I am trying to identify the haplotypes and its alleles and my command line is posted below when am running this am getting following error , help me in fixing this error
calling MAXCUT based haplotype assembly algorithm
./command.sh: line 11: 10635 Segmentation fault

/share/apps/hapcut/extractHAIRS --VCF filtered_variants.vcf --bam aln_sorted.bam --maxIS 600 --ref 2017_V2_ND886_assembly.fa --indels 1 > fragment_matrix_file
/share/apps/hapcut/HAPCUT --fragments fragment_matrix_file --VCF filtered_variants.vcf --output output_haplotype.vcf --maxiter 100 > hapcut.log

**Comment by tfenne** [comment]
This is an issue with HapCut, not with fgbio.  Please report it there.
