### ISSUE TITLE
CorrectUmis should store the old/uncorrected UMI in a tag once the spec says which one

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#208]
Requires the spec to be a bit more settled.  See:
* https://github.com/samtools/hts-specs/issues/109
* https://github.com/samtools/hts-specs/pull/119
* https://github.com/samtools/hts-specs/pull/200

**Comment by nh13** [comment]
# Those are some issues
![](http://www.reactiongifs.com/r/mog1.gif)

**Comment by tfenne** [comment]
The spec is now ammended.  `OX` is the tag for original UMI.  I think the only question that remains is whether to always write that tag, write it only for UMIs that get corrected, or never write it.  Or make it an argument to the program.
