### ISSUE TITLE
Metric.write and Metric.read don't agree on how to deal with Boolean values

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#209]
The default mechanism for writing out values in Metric.write causes `Boolean` values to be emitted as either `Y` or `N`.  However, the code that reads the values back only appears to recognize `true` as a value value for Boolean.True.  So upon roundtrip all boolean values become `false`.

**Comment by nh13** [comment]
I think this is because `Metric` uses `htsjdk.samtools.util.FormatUtil.format(boolean value)` but does not use `parseBoolean`.

**Comment by tfenne** [comment]
Agreed. We should probably just modify formatValues to not use FormatUtil for booleans.

**Comment by tfenne** [comment]
See https://github.com/fulcrumgenomics/commons/pull/18

**Comment by nh13** [comment]
@tfenne LGTM.

**Comment by tfenne** [comment]
Resolved by the change in commons.
