### ISSUE TITLE
Can CallMolecularConsensusReads use a different tmp directory?

### ISSUE THREAD

**Issue by fleharty** [fulcrumgenomics/fgbio#221]
Sometimes when I run CallMolecularConsensusReads, I run out of disk space in the /tmp directory that I have.

Is it possible using something like the --tmp-dir argument to change the directory that it write the sortingcollection to?

**Comment by tfenne** [comment]
Hi Mark.  Right now fgbio doesn't have a toolkit specific way to do this.  We are exploring a better way to add some global options that won't interfere directly with tool options.

In the meantime, the code uses whatever temp directory Java says it the default.  This can be changed using a JVM system property:
`java -Djava.io.tmpdir=/scratch -jar fgbio.jar .....`

**Comment by fleharty** [comment]
@tfenne Thanks again @tfenne!
