### ISSUE TITLE
HapCUT2 format has changed slightly

### ISSUE THREAD

**Issue by pjedge** [fulcrumgenomics/fgbio#222]
Sorry for the change in format, but it this change will really improve interpretability of HapCUT2 output.

The value in HapCUT2 output corresponding to the 'SE' tag is now represented by a floating point phred-scaled quality score (closer to 0 means switch is likely, closer to 100 means switch is unlikely).
Similarly, the value corresponding to 'ME' is represented by a phred-scaled quality score (closer to 0 means mismatch is likely, closer to 100 means mismatch is unlikely)

If that were all, I'd just commit a change to the description string in https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/vcf/HapCutToVcf.scala with the updated information. However there is also a change that if a score is not explicitly computed (based on the flags used) it is represented as a period '.' rather than just being given the max score. I'm not familiar with scala at all so if someone else could add code to handle this case that'd be fantastic.

**Comment by nh13** [comment]
@pjedge thanks for keeping us in the loop on this, and I'll take a look at updating it.

**Comment by nh13** [comment]
@pjedge do you have some example output you could send me.  I wouldn't mind having a test case or two from a real example dataset.

**Comment by pjedge** [comment]
Hey Nils. Sorry for the delay. Sent you 3 example files to your gmail.

**Comment by nh13** [comment]
@pjedge can you take a look and potentially try the tool on your data?
