### ISSUE TITLE
Have github hashes in the snapshot release version.

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#234]

**Comment by nh13** [comment]
If this (https://github.com/fulcrumgenomics/commons/pull/10) works in commons, it should work here.

**Comment by tfenne** [comment]
@nh13 Perhaps we should revisit this with the next release we do?

**Comment by nh13** [comment]
@tfenne it seems to work there, so that's good.  I hope maven has a lot of disk space!

**Comment by nh13** [comment]
Also, I think we should add it to sopt while we are at it.  Maybe dagr too.

**Comment by nh13** [comment]
We did it: https://oss.sonatype.org/content/repositories/snapshots/com/fulcrumgenomics/fgbio_2.13/
