### ISSUE TITLE
Sorter does not need to spill to disk...

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#240]
if we have all the records in memory!

**Comment by tfenne** [comment]
It doesn't, but it reduces complexity significantly by doing so _and_ ensures that consecutive sorts can't over-consume on memory.  E.g. imagine sorting with max 1m in memory, to queryname to fix mate information, then back into coordinate.  If you had 999k records, you'd end up with them all in memory twice potentially.

**Comment by nh13** [comment]
It's max in memory for this sorter. Not all sorters. It wouldn't be too complex to return an iterative over the records in memory.  If it becomes a big problem, I'll probably implement it. Thanks for the background.

**Comment by tfenne** [comment]
I understand.  My point is that the current implementation has very predictable semantics:

1. Large amount of memory are only used during the accumulation/sorting phase
2. Iteration is non-destructive (i.e. you can iterate > 1 times if you want)

It's largely impossible to do that unless you write the records to disk, even if you never hit max memory.  So we'd either have to add the complication of clients indicating whether a destructive sort is ok, or accept that depending on the number of records supplied, memory consumption during iteration will vary significantly.
