### ISSUE TITLE
Does CallDuplexConsensusReads support outputting consensus reads from one strand only?

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#243]
I think not: https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/umi/DuplexConsensusCaller.scala#L144-L146

@tfenne what do you think?  If not, should this be explicitly documented somewhere?

**Comment by tfenne** [comment]
Currently it does not.  It's documented in the usage here:
https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/umi/CallDuplexConsensusReads.scala#L47

Wouldn't be a huge deal to change, but is/was a nice simplifying assumption to begin with.

**Comment by tfenne** [comment]
Closing this as I believe #293 resolves it.
