### ISSUE TITLE
Error while running CallDuplexConsensusReads

### ISSUE THREAD

**Issue by abolia** [fulcrumgenomics/fgbio#246]
Hi, 

I am getting this error while running "CallDuplexConsensusReads":

"Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Not all AB-R1s and BA-R2s were on the same strand for molecule with id:260/A"

I tried looking around for this error but couldn't find anything useful. Can you please help me understand what's this error and how can I fix this issue. 

FYI: The commands I am running are -
java -jar $fgbio **FastqToBam** -i $firstFastq $secondFastq --read-structures 3M2S132T 3M2S132T -o ${name}_unmapped.bam --sample=${name} --library=Hotspot_v24 --read-group-id=${name} -s true

java -jar $picard **SortSam** I=${name}_unmapped.bam O=${name}_unmapped_sorted.bam SORT_ORDER=queryname VALIDATION_STRINGENCY=LENIENT
java -jar $picard **SamToFastq** I=${name}_unmapped_sorted.bam F=/dev/stdout INTERLEAVE=true 
VALIDATION_STRINGENCY=LENIENT | $bwa mem -p -t 24 $indexFasta /dev/stdin > ${name}_unmapped_aligned.bam
java -jar $picard **SortSam** I=${name}_unmapped_aligned.bam O=${name}_unmapped_aligned_sorted.bam SORT_ORDER=queryname VALIDATION_STRINGENCY=LENIENT
java -jar $picard **MergeBamAlignment** UNMAPPED=${name}_unmapped_sorted.bam ALIGNED=${name}_unmapped_aligned_sorted.bam O=${name}_mapped.bam R=$indexFasta SORT_ORDER=queryname ALIGNER_PROPER_PAIR_FLAGS=true MAX_GAPS=-1 ORIENTATIONS=FR VALIDATION_STRINGENCY=LENIENT CREATE_INDEX=true

java -jar $fgbio **GroupReadsByUmi** -i ${name}_mapped.bam -o ${name}_grouped.bam --strategy=paired --edits=1 --min-map-q=20

java -jar $fgbio **CallDuplexConsensusReads**  -i ${name}_grouped.bam -o ${name}_consensus.unmapped.bam --error-rate-post-umi=30

Thank you,
Ashini

**Comment by nh13** [comment]
The error is complaining that it expected that the following reads should be on the same strand:
  - all reads that are the first end of a pair and have molecular identifier "260/A"
  - all reads that are the second end of a pair and have molecular identifier "260/B"

Can you post the reads that have molecule id "260"?  Something like this should work: `samtools view ${name}_grouped.bam | grep "MI:Z:260[^0-9]"`.  This will help us debug the issue.

**Comment by abolia** [comment]
Thanks for the quick reply. Here are the reads that have id "260"

D00783:175:H7JGYBCXY:1:2211:0:7400483	99	1	2713207	60	53M79S	=	2713207	53	GATCATTAAAGTGGAAGGCCCCCTCCCTCCTGGAGCCCCCTTGCTGTGGGCATGAGAGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTATCTCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAA	GGGGGGGGGGGGGGGGGGGIIIGGGGGGIGGIGIIIIGIIIIIIIIGGIGGAAGGGIIIIIGGIIGGGIGAGIGIIGIGIAGAGIGGGGGAAGGGIGIGGIGGGGGGIAGGIIGGGGAGGIGAGGGGAGAGA	MC:Z:79S53M	PG:Z:bwa	RG:Z:10-ColoBL-50ng-FFPE_S10	MI:Z:260/A	MQ:i:60	AS:i:54	RX:Z:CTG-CTC
D00783:175:H7JGYBCXY:1:2211:0:7400483	147	1	2713207	60	79S53M	=	2713207	-53	TTTTAATGATACGGCGCCCACCGAGATCTACACCGTATCTCACACTCTTTCCCTACACGACGCTCTTCCGATCTCTCTTGATCATTAAAGTGGAAGGCCCCCTCCCTCCTGGAGCCCCCTTGCTGTGGGCAT	AG.AGGGA..<GAA<..<GGGGA<.<.AAAIGGGGGIGGGGGGAGAGGG.GGGGGGAGGGIGGGGGGGGGGIGIIGIGGGAGGGIGGGIGGGIGGA<GGGGGGIGGAIGIIIGGGGIGGGGGIGGIGIGAGG	SA:Z:chrAdapter,5927,-,41S34M57S,0,0;	MC:Z:53M79S	PG:Z:bwa	RG:Z:10-ColoBL-50ng-FFPE_S10	MI:Z:260/A	MQ:i:60	AS:i:54	RX:Z:CTG-CTC
D00783:175:H7JGYBCXY:1:2202:0:6162351	99	1	2713207	60	53M79S	=	2713207	53	GATCATTAAAGTGGAAGGCCCCCTCCCTCCTGGAGCCCCCTTGCTGTGGGCATGAGAGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTATCTCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAA	GA..<GGGIAGAA.G.GGA.AG.G.<<.GA<AGGGA<.<<GAAGA<GG..<AGGGAA...<.<..<.<G.G...<<GAGAGG.<G<GAA<G<AG.<G....<..<.G<GGGIG..<<<.<.GGA<G.G.AGI	MC:Z:79S53M	PG:Z:bwa	RG:Z:10-ColoBL-50ng-FFPE_S10	MI:Z:260/B	MQ:i:60	AS:i:54	RX:Z:CTC-CTC
D00783:175:H7JGYBCXY:1:2202:0:6162351	147	1	2713207	60	79S53M	=	2713207	-53	TTTTATTGCTACGGTGTCCACCGAGATCTACACCGTATCTCACACTCTTTCCCTACACGACGCTCTTCCGATCTCTCTTGATCATTAAAGTGGAAGGCCCCCTCCCTCCTGGAGCCCCCTTGCTGTGGGCAT	....<.<.....<....A<<..A<.G<<.GAGAA.<.GAGG<<.GAGAGG<A<..<<A<<GGGAGGGGGGGGGGG<GGGAGGGIGGGAAGGGGGGAGGGGGGGGGGGGIIGGGGGGIGGIGAGGIIGGGGGG	SA:Z:chrAdapter,2165,-,41S34M57S,0,0;	MC:Z:53M79S	PG:Z:bwa	RG:Z:10-ColoBL-50ng-FFPE_S10	MI:Z:260/B	MQ:i:60	AS:i:54	RX:Z:CTC-CTC
D00783:175:H7JGYBCXY:2:1210:0:11199813	99	1	2713207	60	53M79S	=	2713207	53	GATCATTAAAGTGGAAGGCCCCCTCCCTCCTGGAGCCCCCTTGCTGTGGGCATGAGAGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTATCTCATCTCGTATGCCGTCTTCTGCTTGAAAAAAAA	GGAGGIIGIIGGIGGGIGGIIIIIIIIIIIIGGGIIIIIIGGGIAGGGGGGGGGGGIIIIGGGGGGIIIGIGGGGIGGGIIIGIGGGIIIIGGGGGGAGGG<AGGGGIIIAGGGIGAGGGGAAGGGGIIGII	MC:Z:79S53M	PG:Z:bwa	RG:Z:10-ColoBL-50ng-FFPE_S10	MI:Z:260/B	MQ:i:60	AS:i:54	RX:Z:CTC-CTC
D00783:175:H7JGYBCXY:2:1210:0:11199813	147	1	2713207	60	79S53M	=	2713207	-53	TTTTAATGATACGGCGACCACCGAGATCTACACCGTATCTCACACTCTTTCCCTACACGACGCTCTTCCGATCTCTCTTGATCATTAAAGTGGAAGGCCCCCTCCCTCCTGGAGCCCCCTTGCTGTGGGCAT	GG.AA<<GG.<.A<A.G<A<G.GGAAIGIIIIGGGGGAGGGGGGGGGG.GGGG<GGGGAGGGGGGIIGGGGGGGGGGGGGGGGIIIIIIIGGGGGIIIGGIIGGGIIIIIIIGGIGIGGGGAIIGGGGIIIG	SA:Z:chrAdapter,5813,-,2S27M12I33M58S,0,12;	MC:Z:53M79S	PG:Z:bwa	RG:Z:10-ColoBL-50ng-FFPE_S10	MI:Z:260/B	MQ:i:60	AS:i:54	RX:Z:CTC-CTC

Thanks for looking into it.
Ashini

**Comment by tfenne** [comment]
Thanks for the reads @abolia.  I think I see the problem.  I think there is a bug upstream in `GroupReadsByUmi`, and that it is doing the wrong thing when the A and B UMIs on a molecule are the same or very similar.  In your case it looks like the UMIs are `CTC-CTC`, or maybe `CTG-CTC`, so it's incorrectly assigning the reads to A vs. B strands, and confusing the caller.  I'll look into a fix shortly.

**Comment by abolia** [comment]
@tfenne Thank you so much for helping out with this. I will look forward to the fix. 

Thanks,
Ashini

**Comment by tfenne** [comment]
@abolia I just merged the fix to master.  It's from PR #247 if you want to see what changed.

**Comment by abolia** [comment]
@tfenne After the fix, it ran successfully. I was able to generate a consensus bam file. Thank you so much for your help.

**Comment by tfenne** [comment]
You're welcome - glad it solved your problem.
