### ISSUE TITLE
Incorrect Quality Score assignment by CallDuplexConsensusReads

### ISSUE THREAD

**Issue by abolia** [fulcrumgenomics/fgbio#250]
Hi, 

I found a bug with "CallDuplexConsensusReads". It is assigning 90 quality score to each base in the entire bam. I can see the correct quality score in the bam generated from "GroupReadsByUmi", however when the reads are collapsed, somehow the quality scores get altered.

For example, here is one line from my bam:
Sample_Hiseq:100002 77 * 0 0 * * 0 0 CTCTTGTTACTTACAAGCTGAGCCATGAGGACCAGGTCACAGGACCTCTTTGGACTGCAGTTTCCCTCTCTGTAGGCAGGGATGGTAACTCCTGCCCTGTTTCCCTAACCGCTGCCACTCCCCACCCTCTA {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{ aD:i:33 bD:i:24 cD:i:57 aE:f:0.00138793 bE:f:0.00858779 cE:f:0.00441945 RG:Z:A MI:Z:100002 aM:i:33 bM:i:24 cM:i:57 ad:B:s,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33 bd:B:s,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24 ae:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0 be:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,2,1,1,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,1,1,0,1,0,1,0,1,1

Can you please look into this issue on why "CallDuplexConsensusReads" is doing this.

Thanks,
Ashini

**Comment by abolia** [comment]
Okay so I looked through my bam files and found that the "CallDuplexConsensusReads" is actually assigning 90 quality score to each base in the entire bam. I can see the correct quality score in the bam generated from "GroupReadsByUmi", however when the reads are collapsed based, somehow the quality scores get altered.

For example, here is one line from my bam:
Sample_Hiseq:100002      77      *       0       0       *       *       0       0       CTCTTGTTACTTACAAGCTGAGCCATGAGGACCAGGTCACAGGACCTCTTTGGACTGCAGTTTCCCTCTCTGTAGGCAGGGATGGTAACTCCTGCCCTGTTTCCCTAACCGCTGCCACTCCCCACCCTCTA     {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{  aD:i:33 bD:i:24 cD:i:57 aE:f:0.00138793 bE:f:0.00858779 cE:f:0.00441945 RG:Z:A  MI:Z:100002     aM:i:33 bM:i:24 cM:i:57      ad:B:s,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33      bd:B:s,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24   ae:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0 be:B:s,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,2,1,1,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,0,0,0,1,1,0,1,0,1,0,1,1

Can you please look into this issue on why "CallDuplexConsensusReads" is doing this.

Thanks,
Ashini

**Comment by nh13** [comment]
I believe the[ maximum PHRED ](https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/util/NumericTypes.scala#L58)score we produce is `93`, which should be allowed, though not all tools can handle even scores above 40-50.  I believe that htsjdk (see [SAMUtils.MAX_PHRED_SCORE](https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMUtils.java#L113)) and the [description on wikipedia](https://en.wikipedia.org/wiki/FASTQ_format) allow it, so it is likely a GATK issue.  

Looking at options to `HaplotypeCaller`, I see this option: 
`--allow_potentially_misencoded_quality_scores`, could you give that a try.  I also see `--fix_misencoded_quality_scores` though I am not sure how it "fixes" them.

**Comment by nh13** [comment]
And for that particular read, you have very good depth on the A and B strand respectively (33 and 24), so the final quality of the call will be very good.  See these two pages on our wiki about how we call duplex consensus reads and the math behind it:

- https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads
- https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Consensus-Reads

**Comment by abolia** [comment]
Thanks for the quick reply.
I randomly picked few 1000 reads from my bam and they all had 93 quality score so that kinda baffled me, but I will look into the documentation you mentioned. 

Yes, I tried "fix_misencoded_quality_scores" option but it throws another error: "Bad input: while fixing mis-encoded base qualities we encountered a read that was correctly encoded; we cannot handle such a mixture of reads so unfortunately the BAM must be fixed with some other tool"
I had also tried using "--allow_potentially_misencoded_quality_scores", and it throws the same error:
"SAM/BAM/CRAM file appears to be using the wrong encoding for quality scores: we encountered an extremely high quality score (89) with BAQ correction factor of 7. Please see https://www.broadinstitute.org/gatk/guide/article?id=6470 for more details and options related to this error."

Thanks
Ashini

**Comment by nh13** [comment]
@abolia could you try turning `--baq OFF`?  Unfortunately it looks like it is a problem with GATK and not our software, so I would head over to that forum and link an issue to here.

As for _why_ there is a lot of `93` base qualities, it's likely because you have very high depth of coverage across both strands of your duplex molecule (this is really good), and therefore the consensus quality is very high, in fact, the maximum possible!

**Comment by nh13** [comment]
@abolia can you tell us _which_ GATK you are using as well?

**Comment by abolia** [comment]
I am using gatk version 3.6. I turned --baq off but got the same error. 
Command line for gatk:
java -Xmx20g -jar $gatk -nct $threads \
-T BaseRecalibrator -R $indexFasta \
--allow_potentially_misencoded_quality_scores \
-knownSites $dbsnp \
--baq OFF \
-I ${name}_sorted.bam -o $name.recalibration.grp  &> Logs/6_recal.txt

I looked at the GATK forum for similar issues but they ask to check the encodings, so looks like there isn't a solution here.  Thanks for your help.

Ashini

**Comment by nh13** [comment]
I think you can skip base recalibration anyhow.  The other option is to write a quick script to cap the base qualities to a fixed value and retry.  Sorry we cannot be of more help.  If you link your question in the GATK forum here, I'd be happy to chime in.

**Comment by nh13** [comment]
Also, here's the relevant line in the GATK codebase: https://github.com/broadgsa/gatk-protected/blob/master/public/gatk-utils/src/main/java/org/broadinstitute/gatk/utils/QualityUtils.java#L51

It looks like 60 is the maximum.  I would rather see GATK cap the quality rather than throw an error, which is not so user friendly.

**Comment by nh13** [comment]
Asked here: http://gatkforums.broadinstitute.org/gatk/discussion/9791/request-to-only-warn-when-a-base-quality-greater-than-60-is-encountered/p1?new=1

**Comment by abolia** [comment]
Thanks @nh13 for your help on this. I can write a script to cap the base qualities. But, I have one more question, "CallDuplexConsensusReads" only assigns quality scores to collapsed reads. If there are any single reads (that cannot be grouped), does "CallDuplexConsensusReads" assigns quality scores to them as well or does it keep the quality scores from bwa. If thats true and we have singletons, then we have 2 different encodings going in the bam file, and that may throw off GATk and the reason why I get the error about mixed encodings. Is that right ?

Thanks again for all your help.

**Comment by nh13** [comment]
At the moment, `CallDuplexConsensusReads` will not output singletons, and requires at least one read from both strands of a duplex.  Regardless, if you run BAM through Picard's `ValidateSamFile` you should get no errors.   The error for mixed encodings is 100% the issue with GATK not accepting quality values 60 or greater.

**Comment by abolia** [comment]
@nh13 When you say "at least one read from both strands of a duplex", are you talking about forward and reverse reads in a read pair? I am sorry I don't understand your definition of duplex here.

**Comment by nh13** [comment]
At least one from the "A" strand and one from the "B" strand, not the first read of a pair and second read of a pair.  It wont generate a consensus reads from only reads from one strand of the double-stranded (duplex) source molecule.

**Comment by abolia** [comment]
Got it. That makes sense. Thank you.
