### ISSUE TITLE
How to build a fastq file with UMI sequences for AnnotateBamWithUmis ‘-f’ argument

### ISSUE THREAD

**Issue by yyren** [fulcrumgenomics/fgbio#252]
I got a pair-end sequencing data by using The illumina Accel-NGS 2S Hyb DNA Library Kit, which P5 adapter is incorporated with a 9 base random N sequence as an UMI at the [i5] (index 2 position) like:
P5 adaptor:
AATGATACGGCGACCACCGAGATCTACACNNNNNNNNNACACTCTTTCCCTACACGACG
CTCTTCCGATCT

The forward and reverse strand both have but with different UMI sequences, how can I build a fastq file with the UMI sequences for the AnnotateBamWithUmis. I have also tried UMI-tools, but it can only output the processed fastq files
Thank you so much in advance

**Comment by nh13** [comment]
@yyren there's a relatively new tool in the `master` branch that may be more suited to your needs, called  [`FastqToBam`](https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/fastq/FastqToBam.scala#L42-L98).  The command line would look something like this:

```
FastqToBam --input r1.fq r2.fq  i2.fq --read-structures +T +T +B 9M
```

assuming that:
1. read one and two are all template bases
2. the fastqs are per-sample (i.e. the index one reads have already been used to demultiplex the sequencing run)
3. the second index read is made up of all UMI bases.

If you have a different read structure, post back.

**Comment by yyren** [comment]
@nh13 Thank you so much for your help and quickly answer.
I think the read structure is the same as you mentioned like this :
P5(UMI-1)+insert sequence+P7(index1)
P7(index1)+insert sequence +P5(UMI-2)

and one of read in my pair-end data looks like :
R1:
@NB501899:18:HHJCLAFXX:1:11101:26341:1028 1:N:0:CGATGT
ATTGCAAACTAGAATAACNAGTTTAGAGAAATAAATGACCTNATGGAGCTGAAAAACACAGCATGAGAACTTCAT
+
<AAAAEEAEEAEEEE/EE#AEEEEEE/EAEE/EEEEAEEAA#EEEEEEEEEE/EE6EEEEEEEEEEEA/EEEAE/

R2:
@NB501899:18:HHJCLAFXX:1:11101:26341:1028 2:N:0:CGATGT
GTCTTTTCACATAGTCCTACATTTCTTGGAGGCTGTTTGTTCCTTTTCATTTTTTTTCTCTAATCTTGTCTTCAC
+
A6AAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/EEAEAAAEEEEEEEEEEEEEEEEEE6EEEEEEEEE

**But It reported the error** :  cannot read non-existent:  i2.fq
There is not much information in the help document about the i2.fq, I assumed it is the output file with the UMI sequence, so it should not exist before start the software, do I make something wrong? Thank you so much

**Comment by nh13** [comment]
For `FastqToBam`, did you provide the FASTQ for index two, which I called `i2.fq`?

**Comment by yyren** [comment]
@nh13 Thank you very much for your help
I still feel confused about the meaning of `the FASTQ for index two, which I called i2.fq`. when I searched on the google, it is the output file from the sequencer like Miseq, I am not sure whether it is the same as you mentioned.  Is it convenience to you post an example of the i2.fq? Thank you very much

**Comment by nh13** [comment]
@yyren I believe you will need to run [`bcl2fastq`](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2_guide_15051736_v2.pdf) with the `--create-fastq-for-indexreads` option to get FASTQs for the index reads.  In this case, you should get four FASTQs assuming paired end reads and dual indexing:
1. `r1`: reads from the first end of the pair
2. `r2`: reads from the second end of the pair
3. `i1`: reads from the first index read (no template/sample bases)
4. `i2`: reads from the first second read (no template/sample bases)

Please refer to Illumina support and the lab that you obtained the sequencing data to obtain the data in this format.  If you have any issues after obtaining the data and running the tool, free to post back.

Alternatively you can use Picard's `ExtractIlluminaBarcodes` and `IlluminaBasecallsToSam` tools, which support UMIs in the index reads, though they are a bit more complicated to run, and are beyond the scope of this issue.
