### ISSUE TITLE
AB-R1s, BA-R2s on same strand check in CallDuplexConsensusReads

### ISSUE THREAD

**Issue by chapmanb** [fulcrumgenomics/fgbio#257]
Tim and Nils;
After your help working through the memory issues I'm running into an apparent input data related issue on trying to test this for duplex input reads. After running through GroupReadsByUmi with `-s paired`, I'm getting a complaint about the orientation of the reads using the latest development version:
```
[2017/06/22 13:39:04 | FgBioMain | Info] CallDuplexConsensusReads failed. Elapsed time: 33.38 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Not all AB-R1s and BA-R2s were on the same strand for molecule with id: 2520614/A
 at scala.Predef$.require(Predef.scala:277)
 at com.fulcrumgenomics.umi.DuplexConsensusCaller.consensusSamRecordsFromSamRecords(DuplexConsensusCaller.scala:166)
 at com.fulcrumgenomics.umi.UmiConsensusCaller.consensusReadsFromSamRecords(UmiConsensusCaller.scala:244)
 at com.fulcrumgenomics.umi.UmiConsensusCaller.consensusReadsFromSamRecords$(UmiConsensusCaller.scala:242)
 at com.fulcrumgenomics.umi.DuplexConsensusCaller.consensusReadsFromSamRecords(DuplexConsensusCaller.scala:96)
```
I'm not totally sure what this indicates about our data/prep process and if there is anything we can to mitigate or filter problematic reads. Do you have any tips/tricks to diagnose or work around the issue? Thanks much.

**Comment by nh13** [comment]
@chapmanb can you try with the latest (released) fgbio.  I am wondering if it is the same issue as here: https://github.com/fulcrumgenomics/fgbio/issues/246#issuecomment-307903215, namely a bug that `GroupReadsByUmi` incorrectly assigned the reads when the UMIs are similar, which happens much more often with short (ex. 3bp) UMIs.

**Comment by chapmanb** [comment]
Nils;
Thanks for following up on this. The 0.2.0 release does resolve most of the issues but I'm still running into cases failing with the same problem. I was able to put together a minimal example that demonstrates the issue:
```
wget https://s3.amazonaws.com/chapmanb/testcases/fgbio-grouped-ab.bam
fgbio -Xms500m -Xmx1g CallDuplexConsensusReads -i fgbio-grouped-ab.bam -o /dev/null
```
Let me know if I can provide anything else to help with debugging. Thanks again for looking at this.

**Comment by nh13** [comment]
@chapmanb @tfenne I re-ran this back through `GroupReadsByUmi` and can confirm there's an error.  I am wondering if there is an _actual_ collision between two independent source molecules having the same UMI.  I am wondering if we should just filter those cases rather than throwing an exception.

**Comment by nh13** [comment]
@chapmanb I created a new PR (https://github.com/fulcrumgenomics/fgbio/pull/259) that you could try out.  It will not generate consensus reads in this case, but should continue on.  Can you verify it works in your hands (it does in mine).

**Comment by nh13** [comment]
@chapmanb I merged the PR which changes `CallDuplexConsensusReads` to not output consensus reads in the case that AB-R1s and BA-R2s are not and the strand (and similarly for AB-R2s and BA-R2s).  @tfenne mentioned that we could also update `GroupReadsByUmi` to not mark reads in the same case, but I will leave that for another day (https://github.com/fulcrumgenomics/fgbio/issues/260).  You'll see a line in the log that will tell you how many reads were filtered for various reads, including this case:
```
[2017/06/26 15:59:11 | CallDuplexConsensusReads | Info] Raw Reads Filtered Due to Potential collision between independent duplex molecules: 10 (1.0000).
```
Thanks for being patient with this issue.

**Comment by chapmanb** [comment]
Nils -- thanks so much. This fix works perfectly for both my test case and the larger project that I was testing this on. I'll bump the bioconda fgbio package and start using this in bcbio. I appreciate all the help getting it fixed.
