### ISSUE TITLE
BuildToolDocs documents private constructor variables.

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#258]

**Comment by tfenne** [comment]
@nh13 I assume you mean that it's picking up private / non-@arg constructor params in tools and documenting them?  Can you point me to an example please?

**Comment by nh13** [comment]
The `generate-plots` option is documented here: http://fulcrumgenomics.github.io/fgbio/tools/latest/CollectDuplexSeqMetrics.html

**Comment by nh13** [comment]
Sorry I didn't link it originally.

**Comment by tfenne** [comment]
Resolved by https://github.com/fulcrumgenomics/sopt/pull/11

**Comment by tfenne** [comment]
Closing this as it'll be fixed in the next release when we bump up the dependency on sopt.
