### ISSUE TITLE
Reads counts from GroupbyUMI and CallDuplexConsensusReads

### ISSUE THREAD

**Issue by abolia** [fulcrumgenomics/fgbio#261]
Hi, 

I am finding some weird read counts with GroupbyUMI and CallDuplexConsensusReads. There is a drastic difference between the number of reads obtained after GroupbyUMI and CallDuplexConsensusReads. For example, some numbers from a fresh frozen 10ng NA12878 cell line is:

Reads before GroupbyUMI: 54045503
Reads after GroupbyUMI: 48877740
Reads after CallDuplexConsensusReads: 511372

As you can see, there is hardly any collapsing on the GroupbyUMI level, which tells that most of the reads originated from a unique source molecule. Also, shouldn't the reads from CallDuplexConsensusReads be half of reads from GroupbyUMI, as ideally everything originated from double stranded molecule. But there is this huge drop in the number of reads between these two steps. Do you have any idea what might be going on here.

I am also attaching the script I am using to run the fgbio pipeline:
[fgbio_pipeline.txt](https://github.com/fulcrumgenomics/fgbio/files/1112443/fgbio_pipeline.txt)

Thanks,
Ashini

**Comment by nh13** [comment]
@abolia `GroupReadsByUmi` simply adds the `MI` tag, so there really shouldn't be a large drop (besides a few filters like requiring both ends mapped, no secondary/supplementary, and a few more) after running `GroupReadsByUmi`.  The large "drop" should occur after call consensus reads.

As a heads up, we do offer [bioinformatics support services](www.fulcrumgenomics.com) if you find that you need more help beyond what we can offer on our free time.
