### ISSUE TITLE
Strings of different lengths

### ISSUE THREAD

**Issue by vfunari** [fulcrumgenomics/fgbio#263]
Hi Nils,
Hope things are going well... I love the new application its so critical now for integrating the UMI into pipelines, and so happy Brad Chapman has made it seemless in bcbio.

We worked hard on adapting the qiagen and other kits for this application, but we run into a problem that fgbio doesnt deal with UMIs of different length. One of the UMIs is always on the 3' side of the read, so it may be truncated, so it would be a partial UMI. 

Is there anyway to get around this? Specifically, IS there a way to set the options or code to be conservative tif they dont match because of length or content to leave them.

I put an example of the error below...
thank you!

> [2017/06/29 16:44:25 | GroupReadsByUmi | Info] Sorted     5,000,000 record. 
>  Elapsed time: 00:00:43s.  Time for last 1,000,000:    8s.  Last read 
> position: chr20:57,480,425 
> [2017/06/29 16:44:28 | GroupReadsByUmi | Info] Assigning reads to UMIs and 
> outputting. 
> [2017/06/29 16:44:30 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed 
> time: 0.86 minutes. 
> Exception in thread "main" java.lang.IllegalArgumentException: requirement 
> failed: Cannot count mismatches in strings of differing lengths: 
> CAAAACTGTCAATTGACA TTGCAAGAGTGATCA

**Comment by nh13** [comment]
@vfunari Sorry for not seeing this sooner, I don't know why I didn't.

I would be concerned that the shortened UMIs aren't long enough to uniquely identify the source molecule depending on the experiment, for example if you had short UMIs to begin with and the same start site for all reads.  A few *hacks* come to mind:
1. Truncate all UMIs to the UMI with the shortest length before running `GroupReadsByUmi` (may increase falsely grouping reads from _different_ source molecules).
2. Remove all truncated UMIs (not what you want).

I think it wouldn't be too hard to update the code to optionally allow partial matches. Let me see what I can do.

**Comment by nh13** [comment]
I am going to add an optional command line argument that specifies that all umis must be of a given length or greater.  We discard reads with UMIs shorter than this length when that option is supplied.  When comparing clusters of UMIs with variable lengths, we will truncate them down to the smallest UMI length that is greater than or equal to the command line option specified minimum length, and go from there.  

When the command line option is not supplied, all UMIs must be the same length.

**Comment by vfunari** [comment]
That’s awesome! Luca from bcbio had the same problem so he’ll be glad for this. I had to make a workaround. I noticed a few cases wear it didn’t look like it made a consensus quality score. That is it compressed the umi correctly but then didn’t increase the quality accordingly so the read was not scored any better than a single read. Have u seen this before? It should adjust the quality of the consensus read right?

**Comment by nh13** [comment]
@vfunari I think that is a separate issue from here if you don't mind adding a new issue.  Though I am not sure what you mean by "compressed the umi".  Can you given an example in the new issue?

Pull request for this feature here: https://github.com/fulcrumgenomics/fgbio/pull/309

**Comment by nh13** [comment]
@vfunari we have implemented support for partial UMIs.  Please take a look at the new description in the tool's usage.  We have not added support for the "paired" strategy, which is typically used for Duplex Sequencing, as we could not quickly agree on a good implementation.
