### ISSUE TITLE
Filtering Reads due to only seeing A or B reads

### ISSUE THREAD

**Issue by abolia** [fulcrumgenomics/fgbio#264]
Hi, 

I am calling Duplex consensus on my data and we are loosing 48-50% of the reads due to only seeing either A or B reads irrespective of DNA extracted from FFPE, FF or cfDNA. I saw in your documentation that "The expectation is that read 1s derived from the A strand will match read 2s derived from the B strand and vice versa". So, in order to assign the strands, does it look for matching sequence of reads on A1 and B2 (after reverting them) and does it allow some sequencing errors as well? And is there a way to turn off this behavior, like a way to support both duplex consensus reads as well as reads from single strand.

Thanks,
Ashini

**Comment by tfenne** [comment]
Hi @abolia the assigning of read pairs to strands is done by `GroupReadsByUmi` based on matching the UMIs alone.  The tool allows for errors within the UMI sequences, controlled by the `--edits` parameter.  The assignment to strand is done by looking for the UMIs in inverse order.  I.e. if it finds reads with the same positions, but with e.g. `AAAA-CCCC` and `CCCC-AAAA` it will interpret that as a read from each strand.

We are looking at supporting output of single-strand consensus reads in the output of `CallDuplexConsensusReads` but it's not currently at the top of our list to implement.

**Comment by abolia** [comment]
Thanks @tfenne for the explanation. I will play with the --edits parameter to see how it affects the consensus and overall metrics. 

Thanks,
Ashini

**Comment by abolia** [comment]
HI @tfenne, I ran my sample with different values for --edit parameter. Surprisingly I do not see any difference in the read counts when I allow for more errors in the UMI sequences.
I have a 3 bp UMI on each read, so 6bp in total. Therefore, I played with edit distance of 1 to 6. 

**Command**:
java -jar $fgbio GroupReadsByUmi \
-i ${name}_mapped.bam \
-o ${name}_grouped.bam \
--strategy=paired --edits=$edit --min-map-q=20

**Results**:
Sample | fgbio IDT FilterConsensus Reads
(after CallDuplexConsensus Reads) | fgbio IDT CallDuplexConsensus
  Reads | fgbio IDT CallMolecularConsensus
  Reads | fgbio IDT GroupReadsByUmi Reads | BWA aligned Reads
edit=1 | 257078 | 269741 | 2192550 | 30856144 | 34152402
edit=2 | 257602 | 273196 | 2172245 | 30856144 | 34152402
edit=3 | 257602 | 273735 | 2159384 | 30856144 | 34152402
edit=4 | 257895 | 277235 | 2134539 | 30856144 | 34152402
edit=5 | 257853 | 277717 | 2131092 | 30856144 | 34152402
edit=6 | 257963 | 279037 | 2118135 | 30856144 | 34152402
 
Ideally one would hope that with more error allowance, you would see higher number of reads as you would be combining unrelated reads together. I also looked at the strand distribution and its pretty uniform, ~50% reads on each strand (15426688 on A and 15429456 on B). 
However, based on this analysis it looks like, the reads aren't being thrown out due to non-matching UMI. It may be that the reads do not share same start position for the tool to group them together even with allowing 6 mismatches in UMI. Do you have any comments or suggestion on this data?

Thanks, 
Ashini

**Comment by tfenne** [comment]
@abolia I'm closing this for now, feel free to reopen.  I think what you're seeing is just an artifact of the prep.  One of the key challenges in duplex sequencing is recovering clones from both strands of an original duplex.  In my experience it is very common to only recover reads from one strand or the other for a high fraction of molecules.

We just updated the duplex caller to allow for output of consensus reads with support only from a single strand, which you may find useful here.
