### ISSUE TITLE
SamRecord.apply should thrown an exception if the tag was not found

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#274]
@tfenne I _think_ it will do the wrong thing currently.

```
 @inline final def apply[A](name: String): A              = getAttribute(name).asInstanceOf[A]
```
if `getAttribute` returns `null`, and `A` is `Int`, then, we have `null.asInstanceOf[Int]`, which in my REPL returns `0`!

**Comment by tfenne** [comment]
Well that's horrifying.  I would have expected that `null.asInstanceOf[Int]` to either return `null` itself, or fail with an NPE.  WTF is it doing returning the default value for `Int`?
