### ISSUE TITLE
GroupReadsByUmi output is empty

### ISSUE THREAD

**Issue by nicodemus88** [fulcrumgenomics/fgbio#277]
Hi to the developers,

I just recently started using fgbio but I have a problem. After annotating my bam file with UMIs, i tried to group them but my output file is always empty. 

Could you please check if there is anything wrong?

My input command for annotation is:
**java -jar /usr/local/bin/fgbio-0.2.0.jar AnnotateBamWithUmis -i htlv_map.bam -o htlv_umi.bam -f ./index2.fastq**

Resulting bam file looks like this:
NS500638:47:H77WVAFXX:2:21312:19274:1852	161	chr1	565149	0	76M	AB513134	2303	0	CTAACCAAAAAAATAAACCCTCGTTCCACAGAAGCTGCCATCAAGTATTTCCTCACGCAAGCAACCGCATCCATAA	AAAAAEEEEEEEEEEEEEEAEEEEEEEEEEEEEEAEEAEEEEEEEEEEEEA<<<AAAAAEEAAAAE<AAAEEEEEA	RG:Z:sample	NM:i:0	AS:i:76	XS:i:76	RX:Z:CACACGTG
NS500638:47:H77WVAFXX:4:11405:17447:6645	129	chr1	28979600	6	23M2D51M2S	AB513134	368	0	CCGGCTAATTTTTGTATTTTGAGTAGAGGCAGGGTTTTACCATGTTGGTCAGGCTGTTCTTGAACTCCTGATCTGT	AAAAAEAEEEEEEEE6EEEEEEEEEEEEEEE/<AEEEEEEEEE<EEAEE</</AE<EEEEEA</EEA/<<<E<<<<	RG:Z:sample	NM:i:2	AS:i:66	XS:i:61	RX:Z:TGCGGTGT
NS500638:47:H77WVAFXX:4:21511:9219:14234	129	chr1	28979600	6	23M2D51M2S	AB513134	368	0	CCGGCTAATTTTTGTATTTTGAGTAGAGGCAGGGTTTTACCATGTTGGTCAGGCTGTTCTTTAACTCCTGATCTGT	AA/AAEEEEEEEEEEEEEEEEEEEEEE//<EE/EEA<EE//</<EEE/EEE6EEEAE/<AA/<//66AA/<E66/<	RG:Z:sample	NM:i:3	AS:i:61	XS:i:56	RX:Z:TGCGGTGT
NS500638:47:H77WVAFXX:1:11210:19709:9204	81	chr1	43661311	60	76M	AB513134	3694	0	CTAGATGCACACTGTAGAATATCAAACATCAGTTAGAAGCAAATTATACATACTGCAACATAGATGATTCCTTAAA	EAEAA/AAEAAAA<EEEEEEEEE<EEAEEEEAEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEAAAAA	RG:Z:sample	NM:i:0	AS:i:76	XS:i:0	RX:Z:TTGTGTGT

I can see the RX tag there, so my annotation is working. 

Then I tried grouping them with the command:
**java -jar /usr/local/bin/fgbio-0.2.0.jar GroupReadsByUmi -i htlv_umi_sort_picard.bam -o htlv_umi_sort_picard_grp.bam -s edit**

But there are no reads in the output file except the header. I tried grouping them with all 4 different strategies but all of them gave the same output.

Did I make any mistakes here? 

Thank you for your help.

**Comment by tfenne** [comment]
@nicodemus88 It's a little hard to tell.  GroupReadsByUmi discards reads for various reasons, the most common of which are that the read is not paired, or that the mapping quality is <= 30 (default), or that the read's mate pair is not aligned.  The other requirement (listed in the usage) is that mapped pairs must have the `MQ` tag present, which I don't see in your files.  It's likely that's the culprit.  I think running `fgbio SetMateInformation` should fix that.

**Comment by nicodemus88** [comment]
@tfenne Thanks for your suggestion.
I think the first few reasons are probably not as for the BAM file I am using, I have already filtered it only for reads with mapping quality >= 30 and the reads are mapped proper and paired.
The culprit is most probably the missing MQ tag.
I was able to group the reads by UMI after sorting and setting the mate information. 
Thanks again!

However, I have a problem when using the CollectDuplexSeqMetrics tool with the command:

**java -jar /usr/local/bin/fgbio-0.2.0.jar CollectDuplexSeqMetrics -i usmg_sort.bam -o group**

When I run it, this error showed up.

[2017/08/24 09:23:03 | FgBioMain | Info] CollectDuplexSeqMetrics failed. Elapsed time: 0.04 minutes.
Exception in thread "main" scala.MatchError: [Ljava.lang.String;@6de30571 (of class [Ljava.lang.String;)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.$anonfun$updateUmiMetrics$3(CollectDuplexSeqMetrics.scala:354)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.updateUmiMetrics(CollectDuplexSeqMetrics.scala:354)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.$anonfun$collect$6(CollectDuplexSeqMetrics.scala:333)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.$anonfun$collect$6$adapted(CollectDuplexSeqMetrics.scala:324)
	at scala.collection.immutable.Stream.foreach(Stream.scala:530)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.$anonfun$collect$2(CollectDuplexSeqMetrics.scala:324)
	at scala.runtime.java8.JFunction1$mcVD$sp.apply(JFunction1$mcVD$sp.java:12)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofDouble.foreach(ArrayOps.scala:275)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.collect(CollectDuplexSeqMetrics.scala:318)
	at com.fulcrumgenomics.umi.CollectDuplexSeqMetrics.execute(CollectDuplexSeqMetrics.scala:295)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:93)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:74)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:45)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

I don't really understand this kind of errors but there is an error in the lines on the each of the scripts displayed above, isn't it? I don't think I should unnecessarily edit the scripts on my own but I'm not sure how to solve this problem.

For the input file used for CollectDuplexSeqMetrics, I have checked and the MI tag is present and I have already sorted them again by coordinate. 

Do you have any idea how can I solve this issue? Thank you very much!

**Comment by tfenne** [comment]
Hi @nicodemus88 .  I think I see what's going on here.  The example records you pasted in have MI tags like `MI:Z:5` and `MI:Z:6`.  But if this is duplex sequencing data I would expect to see either `MI:Z:5/A` or `MI:Z:5/B`.  Additionally your UMIs in the `RX` tag look like they are single UMIs.  Is the data you generated duplex sequencing data (i.e. two UMIs per sample, one at each end of the template) or single-UMI data?

The tool you're running expected _duplex_ data, and I think that's why you're running into problems, albeit with unhelpful error messages!  If the data isn't duplex, then `CollectDuplexSeqMetrics` is not going to be of any use to you.  If it _is_ duplex data, then we need to step back in the process and fix the `RX` tag so that it contains two hyphen separated UMIs (e.g. `ACGT-GGCA`), and then re-run grouping using `--strategy=paired`.

**Comment by nicodemus88** [comment]
Hi @tfenne. Thank you very much for your reply.
Ah, I see now. 
Well, my data is a single-UMI data. I wanted to get the metrics of the UMIs such as counts per UMI. At first I thought the CollectDuplexSeqMetrics was able to do it, without knowing that it is only for duplex data. I am terribly sorry for my mistake here.
Do you have any suggestion on any way I can extract sequencing metrics for my single-UMI data?
Thank you very much.

**Comment by nh13** [comment]
@nicodemus88 you could look at the output of `GroupReadsByUmi`, using the `--family-size-histogram` option.  Does that work for you?

**Comment by nicodemus88** [comment]
Hi @nh13,
Thank you for your response and sorry for the delayed reply.

I tried your suggestion and this is the result I got.

family_size     count   fraction        fraction_gt_or_eq_family_size
1       1493260 0.82354 1
2       261045  0.143967        0.17646
3       49003   0.027025        0.032493
4       8359    0.00461 0.005468
5       1261    0.000695        0.000858
6       215     0.000119        0.000162
7       42      0.000023        0.000044
8       12      0.000007        0.00002
9       5       0.000003        0.000014
10      3       0.000002        0.000011
11      4       0.000002        0.000009
12      4       0.000002        0.000007
13      2       0.000001        0.000005
14      1       0.000001        0.000004
15      1       0.000001        0.000003
16      1       0.000001        0.000003
17      1       0.000001        0.000002
19      1       0.000001        0.000002
20      1       0.000001        0.000001
38      1       0.000001        0.000001

However, I don't really understand the stats here and I can't find any documentation on it. Could you please kindly explain the meaning of the details in this table?

Thank you very much!

**Comment by tfenne** [comment]
@nicodemus88: that file is documented here: http://fulcrumgenomics.github.io/fgbio/metrics/latest/#tagfamilysizemetric

**Comment by nicodemus88** [comment]
Hi @tfenne,
Thank you for your response. 

However, I still don't quite understand the meaning of the metrics.

**Family_size = The family size, or number of templates/read-pairs belonging to the family.**

Does this mean family_size of 1 actually has 1 UMI? 

However, this option is not what I wanted.
Are there any options or alternatives in which I can group my reads by UMI, then display a stats of each UMI and their numbers?

Again, thank you very much for your assistance, I'd really appreciate it.

**Comment by tfenne** [comment]
The best way to think of family size is the number of read-pairs believed to come from the same source molecule.  E.g. a family size of 1 means one read pair with the same start/stop/UMI, a family size of 2 means two identical read pairs, etc.

If you're wanting to do this based solely on UMI, and not include genomic coordinates I'm not sure there's actually a better solution than a quick `samtools view | cut ... | sort | uniq -c` type approach to extract the UMI sequences from the BAM and count observations by UMI.

If you mean to group reads by start/stop/UMI, that's exactly what GroupReadByUmi does.  From there I would suggest that if the output you're getting isn't what you want, you can take a look at both the `RX` (UMI sequence) and `MI` (source molecule identity) tags in the BAM file and can probably very quickly get what you want from some combination of those.

**Comment by malnirav** [comment]
Would GroupReadsByUmi work on single end reads?

**Comment by tfenne** [comment]
As it stands, GroupReadsByUmi only works on paired-end reads, but it would not be a large undertaking to also support single-end reads.

**Comment by malnirav** [comment]
Thank @tfenne. It would be tremendously helpful if GroupReadsByUmi can support single-end reads in the near future.

**Comment by nh13** [comment]
@malnirav [drop us a line](www.fulcrumgenomics.com/contact/) if this is something urgent, as we we frequently add customizations and improvements to `fgbio` for our clients, and would be happy to discuss doing the same for you.  It likely will not be done in the near-term, unless @tfenne or I have a need, as we currently support work on `fgbio` via work for our clients.

I have tracked the issue here: https://github.com/fulcrumgenomics/fgbio/issues/287
