### ISSUE TITLE
Exception in ReviewConsensusVariants

### ISSUE THREAD

**Issue by dilmiperera** [fulcrumgenomics/fgbio#283]
Hi to the developers,

I'm working with a set of bam files with Duplex UMIs and I've followed the following steps:

1. AnnotateBamWithUmis
2. SortBam  --sort-order=Queryname
3. SetMateInformation
4. GroupReadsByUmi -s 'paired' 
5. CallDuplexConsensusReads
6. FilterConsensusReads -M=2 -N=20

And then I tried to run ReviewConsensusVariants
_

> java -jar fgbio-0.2.0.jar ReviewConsensusVariants -i mutations.vcf -c duplexConsensusReads_collapsed-sample_with_UMI_sorted_mateFixed_paired_sorted.bam -g collapsed-sample_with_UMI_sorted_mateFixed_paired_sorted.bam -r hg19.fa -o reviewConsensusVariants_duplexConsensusReads_collapsed

_

The 2 input bams are both sorted and indexed and I checked for errors using picards ValidateSamFile tool. But I keep getting the following exception. 

_

> [2017/09/23 19:48:31 | FgBioMain | Info] Executing ReviewConsensusVariants from fgbio version 0.2.0 as xxxx@xxxx.cbio.private on JRE 1.8.0_144-b01 with snappy
> [2017/09/23 19:48:32 | ReviewConsensusVariants | Info] Loading variants from mutations.vcf
> [2017/09/23 19:48:32 | ReviewConsensusVariants | Info] Loaded 35 variant positions for review.
> [2017/09/23 19:48:32 | ReviewConsensusVariants | Info] Extracting consensus reads from duplexConsensusReads_collapsed-sample_with_UMI_sorted_mateFixed_paired_sorted.bam
> [2017/09/23 19:48:32 | FgBioMain | Info] ReviewConsensusVariants failed. Elapsed time: 0.06 minutes.
> Exception in thread "main" java.lang.IllegalArgumentException: Invalid reference index -1
> 	at htsjdk.samtools.QueryInterval.<init>(QueryInterval.java:24)
> 	at com.fulcrumgenomics.bam.api.SamSource.$anonfun$query$1(SamSource.scala:91)
> 	at scala.collection.Iterator$$anon$10.next(Iterator.scala:448)
> 	at scala.collection.Iterator.foreach(Iterator.scala:929)
> 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
> 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
> 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
> 	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
> 	at scala.collection.TraversableOnce.to(TraversableOnce.scala:310)
> 	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:308)
> 	at scala.collection.AbstractIterator.to(Iterator.scala:1417)
> 	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:302)
> 	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:302)
> 	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1417)
> 	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:289)
> 	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:283)
> 	at scala.collection.AbstractIterator.toArray(Iterator.scala:1417)
> 	at com.fulcrumgenomics.bam.api.SamSource.query(SamSource.scala:91)
> 	at com.fulcrumgenomics.umi.ReviewConsensusVariants.execute(ReviewConsensusVariants.scala:189)
> 	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:93)
> 	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:74)
> 	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:45)
> 	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

_

I also tried using the filtered output from FilterConsensusReads and aligning (using bwa mem) the outputs from both CallDuplexConsensusReads and   FilterConsensusReads and giving them as input to '-c' but I keep getting the same error. 

Did I make any mistakes here?

Also, are there intermediate steps in which you need to align the unmapped BAMs? It is suggested in http://nilshomer.com/2017/07/05/single-strand-umi-somatic-variant-calling/ that the sequence of steps to follow includes mapping intermediate files using bwa mem. Does this apply to the paired end case as well?

Thank you for your help.

**Comment by nh13** [comment]
@dilmiperera can you post both the sequence dictionary in the VCF (`#contig` lines) and the SAM( `@SQ` lines)?  Yes, the consensus BAM should be mapped, as presumably you had to map it to feed it to the variant caller!

**Comment by tfenne** [comment]
@dilmiperera I'm closing this as it's been a few weeks and you haven't gotten back to us; feel free to reopen if you'd still like help.  My best guess is that the chromosome names in your VCF don't match your BAM, but as @n13 says we really need to be able to see a reproducible failing test in order to help more.
