### ISSUE TITLE
Support single-end reads in GroupReadsByUmi 

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#287]
@malnirav
See issue: https://github.com/fulcrumgenomics/fgbio/issues/277

**Comment by ivaltier** [comment]
Dear fgbio developers,

It would be wonderful if you could add this feature to GroupReadsByUmi and your other UMI-related tools. In the meantime, I would like to ask if you have any recommendations to group reads and call the consensus per UMI on single-end data with the current version of fgbio.

Thank you for your attention and for the great software!

**Comment by nh13** [comment]
@ivaltier unfortunately we do not have the bandwidth at this time to add the feature (single-end support), and so likely until we have a need for it for our own purposes, it likely wont get added.  As mentioned in the [linked issue](https://github.com/fulcrumgenomics/fgbio/issues/277#issuecomment-333888443), feel free [drop us a line](www.fulcrumgenomics.com/contact/) if this is something urgent, as we we frequently add customizations and improvements to `fgbio` for our clients, and would be happy to discuss doing the same for you.

**Comment by adamantli** [comment]
Dear nh13,
I too like to see if single end reads can be supported in  GroupReadsByUmi. In the mean time, I am wondering if we can artificially create a uniform molecular tag for reverse reads in order to use fgbio for single end reads.
Thank you for your software.

**Comment by jtpoirier** [comment]
I agree, this would be useful.

**Comment by tfenne** [comment]
Closing this as implemented in commit fdeac4000b78b01ff3bd2ad1b98bd03f93d57e3d
