### ISSUE TITLE
ErrorRateByReadPosition.scala line 216

### ISSUE THREAD

**Issue by dilmiperera** [fulcrumgenomics/fgbio#297]
Hi,

I'm trying to run the ErrorRateByReadPosition method and there is no output for the c_to_g_error_rate column. It looks like a bug in the code. 

In file ErrorRateByReadPosition.scala

```
line 216     case ('C', 'G') => a_to_g_obs += 1
```

Thanks,
Dilmi

**Comment by tfenne** [comment]
Thanks for reporting this @dilmiperera.  Fix is inbound in PR #300.

**Comment by dilmiperera** [comment]
You're welcome and thanks for the quick response.
