### ISSUE TITLE
Metric may not support collection member variables

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#314]
I need to confirm this, and if so, fix it.

**Comment by tfenne** [comment]
I don't believe it does.  I'm curious what your expected/desired result is though.  E.g. if I had a class:

```scala
case class Example(name: String, count: Int, warnings: Seq[String]) extends Metric
```

What would you expect this to write into a row?  And more importantly how would it be parsed back?  The former seems easy enough, if we never expect to read it back.  The latter seems fraught with peril.  I.e. you'd have to pick some string to join the entries with, then escape that anywhere it occurred within the values, yada yada.

**Comment by nh13** [comment]
This is what I would "like" to support:
```
case class Example(name: String, count: Int, warnings: Seq[String], message: Option[String]) extends Metric
```
