### ISSUE TITLE
ClipBam (and SamRecordClipper) don't hard clip if there is already >= n soft clipped bases

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#319]
ClipBam does not do the right thing when hard clipping, if there is already sufficient clipping present as soft-clipping.  I was trying to use ClipBam to generate a 2x75bp BAM from a BAM with 2x151bp reads by doing:

`fgbio ClipBam -i $in -o $out -r $ref --read-one-three-prime=76 --read-two-three-prime=76`

Most of the reads were clipped correctly - a `76H` was added to the cigar at the right place and the bases and quals were cut.  However, any reads that had >= `76S` at the appropriate end were left untouched.  E.g a positive strand mapping with `100S51M` would be left with the same cigar and full length bases and quals.

I think in this case it should be "promoted" to hard clipping, with a cigar of `76H24S50M` and the bases/quals adjusted accordingly.

**Comment by nh13** [comment]
@tfenne I think there needs to be some updates to `SamRecordClipper` to handle this looking at it.

**Comment by nh13** [comment]
Fixed

**Comment by ggydush** [comment]
I'm seeing a similar issue on Fgbio versions 0.5.0 and 0.6.1 when trying to clip 50 base pairs from 146 base pair reads (primary alignment and FR). Reads with long soft clippings end up having their cigars removed, mapping quality set to 0, and are not hard clipped (read is still 146bp).

Command:
`fgbio ClipBam -i $in -o $out -r $ref --read-one-three-prime=50 --read-two-three-prime=50`

Would be happy to supply an example bam if helpful.

**Comment by nh13** [comment]
An example would be great!

**Comment by ggydush** [comment]
@nh13

That makes sense - I guess I was mostly confused by the reads not being hard clipped in cases like these. Thanks for the explanation!

**Comment by nh13** [comment]
@ggydush if there is a specific application where you'd prefer to have all the bases hard clipped rather than bases retained (but as an unmapped read) read let us know.  I'd prefer not to add the support to keep the tool simple, but I'd be open if you have compelling use case.  Feel free to open a new issue if so.
