### ISSUE TITLE
metrics CallMolecularConsensusReads

### ISSUE THREAD

**Issue by Lien-NGSdummie** [fulcrumgenomics/fgbio#330]
Hi, 

I've used the fgbio tool to work with UMIs and it seems great. However, I still have a question regarding some metrics in the CallMolecularConsensusReads. 
The standard metrics that it outputs are already very useful, and we see large differences between different experiments. However, one important parameter that we don't know now is how many raw reads are used to generate the consensus reads. 
If I understand correctly, we get the 'total raw reads'  and the 'consensus reads emitted'. But I would like to know how many of the raw reads were used to generate the consensus reads. In that way, we can figure out how many reads were not used and why (like minimum mapping quality below 30, ...). 
Is it currently possible to calculate this in some kind of way? 

Many thanks!

**Comment by tfenne** [comment]
Hi @Lien-NGSdummie.  At the end of program execution (as of version 0.2.0+) you should see several lines logged.  The first gives you the total number of raw reads that were examined.  Then there should be a series of line which tell you how many raw reads were rejected (i.e. not used to build consensus reads) for various reasons, and then finally a line telling you how many consensus reads were output.  Are you not seeing that middle cluster of lines?

Also, in the resulting consensus BAM there are tags on each consensus read that tell you how many raw reads contributed to that consensus read.  E.g. the `cD` tag tells you the total number of raw reads used.  For more info please see: http://fulcrumgenomics.github.io/fgbio/tools/latest/CallMolecularConsensusReads.html

**Comment by Lien-NGSdummie** [comment]
Thanks for your answer. 
I do get these cluster of lines, but I thought some reads were not shown here if for example the minimum mapping quality is too low? 
I have two experiments that give very different results, and I'm wondering if that could be caused by lower mapping quality in one of them. And therefore, it would be useful if I could know the amount of reads that were used to build the consensus. Or can I assume that all reads that are not in the 'filtered out' columns were used for the consensus? 

```
                      Example 1             Example 2  
Total raw reads: 76 017 204          89 553 930
Filtered out due to orphan consensus created: 1 619 967          36 881 167
Filtered out due to mismatching cigars: 961 283          619 105
Filtered out due to insufficient support: 1 588 087          36 663 651
Filtered out due to low base quality: 18 765           6 904
Consensus reads emitted: 2 853 408           15 091 338
```


So in example one, 5.5% of total raw reads are filtered out, while in example two 82.8% of total raw reads are filtered out. But still, more consensuses are created in example two than in example one. Therefore I guessed maybe some other reads are also left out? 

Thanks!

**Comment by nh13** [comment]
@Lien-NGSdummie `CallMolecularConsensusReads` does not filter out reads that have low mapping quality, though `GroupReadsByUmi` does, so perhaps you can set the minimum mapping quality to zero for the latter and see what happens (if more or fewer are produced)?

**Comment by nh13** [comment]
@Lien-NGSdummie closing this for now.
