### ISSUE TITLE
DemuxFastqs: Error: Missing: Sample_Name

### ISSUE THREAD

**Issue by nrosewick** [fulcrumgenomics/fgbio#341]
Hi,

I've paired-end fastqs with R2 containing an UMI (12bp) and a barcode (14bp) .
I created a sample sheet as : 
```
Sample_ID	Sample_Name	Library_ID	Description	Sample_Barcode
T1	Sample1	ID1	Sample1	CGCTCTTCCGATCT
```

Then I executed DemuxFastq : 
```
java -jar $fgbio DemuxFastqs -i R1.fastq.gz R2.fastq.gz -r +T 12M14B+T -x sample_sheet.txt -o test
```
And I get an error associated with the sample sheet : 
```
Exception: IllegalArgumentException
Error: Missing: Sample_Name
```
Any ideas to solve this issue ?

Thanks

**Comment by nh13** [comment]
The input metadata file must be a CSV.  Please read through the long description with `java -jar $fgbio DemuxFastqs --help`.
