### ISSUE TITLE
Duplicate duplex molecules in CallDuplexConsensusReads

### ISSUE THREAD

**Issue by ggydush** [fulcrumgenomics/fgbio#348]
Hi,

I've been running fgbio tools (version 0.3.0) on samples barcoded with duplex UMIs and have had very promising results! Recently, I sequenced synthetic oligos that should have all had roughly the same start/stop positions and tried running duplex consensus calling on the resulting BAMs and found the duplex depth to be higher than expected. After consensus calling, I ended up with 8566 duplexes, and I noticed some of the "unique" duplexes had the same UMI, same start/stop positions, and same read sequences/insert sizes (in CallDuplexConsensusReads output). After reviewing read support in GroupReadsByUmi output, I noticed some of the reads contributing to a given consensus family also had UMI edit distances up to 4bp. Thinking this may be causing errors when designating families and because I was potentially expecting the full spectrum of UMIs at each start/stop position, I adjusted the edit parameter in GroupReadsByUmi to 0. The new duplex counts were 9235 and I am still seeing duplexes that have the same UMI, same start/stop positions, and same read sequences/insert sizes. In both cases, I was using the "paired" strategy of GroupReadsByUmi. 

Given my understanding of how families are identified, I'm stumped on what is happening. I realize that this tool may not be optimized for this use case, but I was hoping you could help explain how this may happen.

Thanks in advance,
Greg

**Comment by nh13** [comment]
Could you post the two consensus reads that you would expect to be coming from the same molecule?  Even better if you could post the BAM and command line you used to run GroupReadsByUmi and the command line for CallDuplexConsensusReads.  I am interested if there are differences in soft-clipping, as we use the start/end coordinates with clipping considered.

If you lower the mismatch tolerance (`--edits`), I would expect that some of the families you previously grouped would now be split into multiple families, so you would get _more_ consensus reads.  I think this explains the increase from 8566 to 9235.  But I am concerned about this:

> The new duplex counts were 9235 and I am still seeing duplexes that have the same UMI, same start/stop positions, and same read sequences/insert sizes

**Comment by ggydush** [comment]
Would you mind sharing an email address for the BAM files? I'd be happy to share and include the family ids for the consensus reads in question.

Regarding the command line arguments, please see below:

GroupReadsByUmi:
`java -jar ${fgbio_jar} GroupReadsByUmi 
            -i ${bam_file} 
            -o ${base_name}.groupByUmi.bam 
            -f ${base_name}.umiHistogram.txt 
            --strategy=paired`

CallDuplexConsensusReads:
`java -Xmx4g -jar ${fgbio_jar} CallDuplexConsensusReads 
            -i ${bam_file} 
            -o ${base_name}.consensus.bam`

Thanks for your help!
-Greg

**Comment by nh13** [comment]
@ggydush contact "at" fulcrumgenomics "dot" com should work.

**Comment by nh13** [comment]
@ggydush can you give me an example of two reads that you believe should be from the same duplex but appear as two consensus reads?
