### ISSUE TITLE
include tag for number of reads that make up an umi-consensus call

### ISSUE THREAD

**Issue by janrehker** [fulcrumgenomics/fgbio#357]
During consensus calling it might be interesting to include the number of reads that contributed to a specific call/consensus-read.

I have varying coverage in my targeted sequencing samples. Right now I am using fgbio CallMolecularConsensusReads with the min-reads parameter set to 1. After that I extract the reads and realign them to my reference genome and proceed with somatic variant calling.
For some regions with higher coverage I can afford setting the min-reads parameter to higher values and might thereby get cleaner calls due to the error-correcting effect of the consensus calling. This might stratify results for variant calls with low allelic fractions as they happen in tumor samples.

Right now I would have to repeat the consensus calling and extract reads again. With the addional info  stored in the consensus calling output though, I could split the extracted fastqs by read numbers used to compose consensus reads. Taking it one step further the information could be passed into the read-ID and then the samfile with the realigned reads could just be filtered by removing min-reads=1 entries. This would spare another consensus calling and realignment step. In addition, coverage on called variants with higher min-reads than 1 could be calculated, so one only needs to repeat variant calling at the specific sites as well.

Hope that makes sense,
Jan

**Comment by tfenne** [comment]
I'm assuming you found the information you needed, but just in case anyone else stumbles across this issue the consensus calling tools output a wealth of information in tags.  These are described in the program usage (via `--help`) and are online:

http://fulcrumgenomics.github.io/fgbio/tools/latest/CallMolecularConsensusReads.html
http://fulcrumgenomics.github.io/fgbio/tools/latest/CallDuplexConsensusReads.html

**Comment by janrehker** [comment]
Yep, there was even another closed question I stumbled over a few
minutes later..
Really like the fgbio tools btw. :)

Jan

Am 26.01.2018 um 14:40 schrieb Tim Fennell:
