### ISSUE TITLE
Metric can write Char but not read it back.

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#362]

**Comment by nh13** [comment]
Is the problem in commons?  https://github.com/fulcrumgenomics/commons/blob/3da708f3aa19294aa4c62a133e85a3a34b3738c0/src/main/scala/com/fulcrumgenomics/commons/reflect/ReflectionUtil.scala#L127-L142

**Comment by sstadick** [comment]
Possible related fix in commons: https://github.com/fulcrumgenomics/commons/pull/24
