### ISSUE TITLE
AnnotateBamWithUmis recommended memory

### ISSUE THREAD

**Issue by ionox0** [fulcrumgenomics/fgbio#363]
Hello fgbio team, thanks for your work with this library. I'm using the AnnotateBamWithUmis step and working with a fastq (32G, 8G compressed).

I am getting an error during this step while at an average memory usage of 32GB. I'm wondering about how much memory should be allowed for this step in proportion to the size of the fastq so I can supply the correct arguments to the jvm? 

```
P/W/jobdOa6G4    2018-02-06 01:20:10,015 call_cmd INFO EXECUTING: /opt/common/CentOS_6/java/jdk1.8.0_25/bin/java -server -jar /home/johnsoni/software/fulcrum/fgbio-0.3.0.jar --tmp-dir=/scratch AnnotateBamWithUmis -i /ifs/work/bergerm1/Innovation/sandbox/ian/temp-results-EM_2_5/tmpG0H4uO/stg40a75601-b74e-4ceb-ad9c-1a4847b6591f/TD-grail-162-30ng_IGO_05500_EM_1_S1_standard_RG_MD.bam -f /ifs/work/bergerm1/Innovation/sandbox/ian/temp-results-EM_2_5/tmpG0H4uO/stg4b3e628c-4e1d-4178-8f50-78def5fe3743/TD-grail-162-30ng_IGO_05500_EM_1_S1_standard_RG_MD_Duplex_UMI_for_readNames.fastq -o TD-grail-162-30ng_IGO_05500_EM_1_S1_standard_RG_MD_fulcrumAnnotated.bam
P/W/jobdOa6G4    [2018/02/06 01:20:23 | FgBioMain | Info] Executing AnnotateBamWithUmis from fgbio version 0.3.0 as johnsoni@u10.cbio.private on JRE 1.8.0_25-b17 with snappy
P/W/jobdOa6G4    [2018/02/06 01:20:23 | AnnotateBamWithUmis | Info] Reading in UMIs from FASTQ.
P/W/jobdOa6G4    [2018/02/07 02:05:17 | FgBioMain | Info] AnnotateBamWithUmis failed. Elapsed time: 1,485.11 minutes.
P/W/jobdOa6G4    Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
P/W/jobdOa6G4    	at scala.collection.immutable.HashMap$HashTrieMap.updated0(HashMap.scala:358)
P/W/jobdOa6G4    	at scala.collection.immutable.HashMap.$plus(HashMap.scala:62)
P/W/jobdOa6G4    	at scala.collection.immutable.HashMap.$plus(HashMap.scala:36)
P/W/jobdOa6G4    	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
P/W/jobdOa6G4    	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
P/W/jobdOa6G4    	at scala.collection.TraversableOnce.$anonfun$toMap$1(TraversableOnce.scala:317)
P/W/jobdOa6G4    	at scala.collection.TraversableOnce$$Lambda$228/1241938981.apply(Unknown Source)
P/W/jobdOa6G4    	at scala.collection.Iterator.foreach(Iterator.scala:929)
P/W/jobdOa6G4    	at scala.collection.Iterator.foreach$(Iterator.scala:929)
P/W/jobdOa6G4    	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
P/W/jobdOa6G4    	at scala.collection.TraversableOnce.toMap(TraversableOnce.scala:316)
P/W/jobdOa6G4    	at scala.collection.TraversableOnce.toMap$(TraversableOnce.scala:314)
P/W/jobdOa6G4    	at scala.collection.AbstractIterator.toMap(Iterator.scala:1417)
P/W/jobdOa6G4    	at com.fulcrumgenomics.umi.AnnotateBamWithUmis.execute(AnnotateBamWithUmis.scala:81)
P/W/jobdOa6G4    	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
P/W/jobdOa6G4    	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
P/W/jobdOa6G4    	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
P/W/jobdOa6G4    	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

Thank you!

**Comment by nh13** [comment]
@ionox0 looking at the source for this tool, it looks like it reads the entire FASTQ to create a map between the read name and associated UMI sequence (bases).  I can absolutely see how the tool could run out of memory loading in a large FASTQ like you have.  @tfenne would have to comment on why it reads in all the names ahead of time, but I suspect it is to add support for:

1. reads not being in the same order in the FASTQ as in the BAM
2. reads in the BAM not having an associated UMI in the FASTQ (via read name).

There are a number of options for your use case:

1. update `AnnotateBamWithUmis` to support a mode where we can assume the BAM and FASTQ are in queryname order, so that we do not have to read in the full FASTQ.
2. convert your BAM to FASTQ, and create a new BAM with the tool `FastqToBam`.

I might be missing a few more.  @tfenne thoughts?

**Comment by tfenne** [comment]
A few thoughts.  There are a bunch of ways to get to a BAM with UMIs, and I would say that `AnnotateBamWithUmis` is probably the last resort.  The other options are:

The best way is to use `fgbio FastqToBam` to create an unmapped BAM (uBAM) that includes the UMIs from the start.  This can work, e.g. with bwa's bam input, or with tools like Picard's SamToFastq & MergeBamAlignment to carry the information forward into the mapped BAM.

Alternatively if you're starting from an Illumina run-folder Picard's IlluminaBasecallsToSam will also create unmapped BAMs with UMIs in them.

Failing that, it's a little hard to predict exactly how much memory `AnnotateBamWithUmis` will take up, but it is caching a map of `read_name -> bases` in memory, and the JVM is not the most memory efficient for things like that.  One thing you might try is running on the JVM from Java 9 as this brings back compressed strings, which means all those strings will take up only half as much space.

**Comment by nh13** [comment]
Feel free to re-open if there are any more questions.
