### ISSUE TITLE
FilterConsensusReads should filter on total depth for duplex reads

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#365]
Currently it only filters based on ab and ba depths respectively.  Consider `--min-reads 7 3 2`.  I would interpret this to mean, have at least three reads on the AB strand, at least two reads on the BA strand, and and at least seven reads across both (assuming num(AB) => num(BA)).  I don't think the tool currently filters on total depth.  I am not sure if this is a bug or an enhancement.

**Comment by tfenne** [comment]
I think it does.  Since that filter is common to both duplex and vanilla, it occurs in `filterRecord()`.  Line 244 pulls the `cD` tag value, and then line 249 checks it against the specified minimum.

**Comment by nh13** [comment]
Doh, I missed it!
