### ISSUE TITLE
UMIs with Ns being counted after GroupReadsByUmi

### ISSUE THREAD

**Issue by jurhoades** [fulcrumgenomics/fgbio#366]
Hi fgbio team,

I've noticed that after running `CollectDuplexSeqMetrics` on a BAM file generated using `GroupReadsByUmi` and looking at the *.umi_counts.txt file that it's counting UMIs with single Ns (ie NTA, GNT, etc).  I'm confused because I thought that since v0.4.0 `GroupReadsByUmi` removed any read with an N in the UMI.  What's even more confusing is that when I look in the BAM file, I can't seem to find any reads with an N in them, suggesting that `GroupReadsByUmi` is working as intended.  Am I misunderstanding something about how `CollectDuplexSeqMetrics` counts UMIs?  Thanks for your help!

    java -jar /path/to/fgbio-0.5.0.jar --tmp-dir . GroupReadsByUmi \
        -i /path/to/in.bam \
        -o /path/to/groupReadsByUmi.out.bam \
        -f /path/to/umiHistogram.txt \
        --strategy=paired
    
    java -jar /path/to/fgbio-0.5.0.jar CollectDuplexSeqMetrics \
        -i /path/to/groupReadsByUmi.out.bam \
        -l /path/to/baits.interval_list \
        -o sample_id

-Justin

**Comment by tfenne** [comment]
Hey @jurhoades - there's some code in `CollectDuplexSeqMetrics` that, for the purposes of reporting, calls consensus UMIs.  I.e. if there's a row in a metrics file that corresponds to a tag family, but we want to put the UMIs in there, we either have to pick a representative UMI or take the consensus of the UMIs that were seen on the individual read-pairs.  It's a simple model, but what you're seeing implies, I think, that there are tag families with two different but equally prevalent UMIs, so where they disagree an N gets called.

Hopefully that makes sense!

**Comment by jurhoades** [comment]
Ahh I see, so it's not actually seeing a family with a UMI with an N but rather calling a consensus UMI for each family "on the fly" and in some cases that results in an N base being called in the UMI.  I think that clears it up for me.  Thanks for your response!
