### ISSUE TITLE
Distinguishing between non-consensus, single index consensus, and dual index consensus reads

### ISSUE THREAD

**Issue by fleharty** [fulcrumgenomics/fgbio#380]
Is there a way to create 3 bams after running GroupReadsByUmi so that,
nonconsensus.bam would contain all the reads that didn't form a consensus,
singleindex.bam would contain consensus called reads where only a single index could be used,
dualindex.bam would contain all the dual index called consensus reads.

**Comment by nh13** [comment]
What do you mean by single-index versus dual-index?  I think `GroupReadsByUmi` uses the value in the `RX` tag, so explain in terms of what's in there.  There's a bunch of pre-filtering of reads (and mappings) that we could output to a "filtered" BAM if that's what you mean.  Also `GroupReadsByUmi` doesn't call the consensus, so I assume you mean to ask if the downstream tools like `CallMolecularConsensusReads` could output reads that didn't form a consensus?

**Comment by fleharty** [comment]
Some time ago we were interested in and experiment to use the number of aD and bD counts as a covariate for BQSR.  The intuition was that reads with aD > 1 and bD > 1 would be better than those with aD > 1 and bD == 1, and even better than those with aD == 1 and bD == 1.

Instead of implementing a new covariate in BQSR to do this, we wanted to just test this out by splitting into 3 separate bams and running BQSR on each group independently.  We have since done this, and not surprisingly consensus reads with larger aD and bD values tend to have higher qualities.  

Unfortunately it doesn't seem to improve the quality scores in a way that is actually useful for variant calling.

I think we can close this issue.
