### ISSUE TITLE
fgbio for Agilent

### ISSUE THREAD

**Issue by maribuon** [fulcrumgenomics/fgbio#391]
Hi!

I am a bioinformatician working on the validation of a targeted panel with UMIs from Agilent (https://www.agilent.com/cs/library/usermanuals/public/G9702-90000.pdf ). Agilent provides their own package to process the data and to remove duplicates based on UMIs. However, our group has experience using fgbio (on IDT panels).  Also, by making my own processing pipeline allows me to have more control and to make any comparison of results easier. Thus, I would like to use fgbio. My question to you guys is if you have used fgbio in Agilent data? And if you recommend and/or see any restriction in applying fgbio to Agilent.

The functions I plan to use from fgbio are:
- AnnotateBamWithUmis
- GroupReadsByUmi
- CallMolecularConsensusReads
- FilterConsensusReads

Best regards,
Mariana

**Comment by nh13** [comment]
@maribuon this process seems reasonable.  I'd also that we have a plethora of tools to create a BAM with annotated UMIs depending on how your input data is given, for example:
- `DemuxFastqs` if you need to also perform sample demultiplexing
- `FastqToBam` if you have just the FASTQs for a sample
- `AnnotateBamWithUmis` if you have the UMIs in a separate FASTQ from the BAM
- `ExtractUmisFromBam` if you have just a BAM file. 

Also, we have some extra tools to make debugging or special cases easier:
- `CorrectUmis` if you have a fixed set of UMIs
- `ReviewConsensusVariants` to make reviewing of variant calls from consensus reads easier
- `ClipBam` to perform various types of clipping, including clipping overlapping read pairs, which is necessary prior to variant calling for some variant callers.

Enjoy!

**Comment by clbenoit** [comment]
Hi, 

I'm also working on validating the https://github.com/nf-core/sarek pipeline for use in clinical somatic genomics, with data generated using the Agilent XT-HS2 KIT: 3M2S+T 3M2S+T Kit . 

Unfortunately, I haven't found any validation data set that I can use to validate fgbio's use on Agilent UMIs 🔍 

If possible, I would prefer to continue using fgbio rather than the Agilent package. Does anyone know a validation dataset I could use ?

**Comment by kunstner** [comment]
Hi @clbenoit, 

did the read structure 3M2S+T 3M2S+T work for you?

Best, 
 Axel
