### ISSUE TITLE
Could GroupReadsByUmi be speed up by parallelization

### ISSUE THREAD

**Issue by ShannonDaddy** [fulcrumgenomics/fgbio#398]
When the sequencing data volume is large, GroupReadsByUmi may still not be fast enough. Is the any parallelization mechanism for speeding up, for example, parallel by each read cluster with the same mapping position or umi?

**Comment by tfenne** [comment]
@ShannonDaddy Can you be a bit more specific about what you're trying to do - e.g. is this super-deep coverage, or are you working with modest coverage of a very large region (e.g. exome)?  

I'm my experience most of the time in GroupReadsByUmi is spent in two places: 1) the initial sorting of the data and 2) writing the output bam.  As a first step I would suggest speeding up (2) by having GroupReadsByUmi output uncompressed bam to stdout (`fgbio --compression=0 GroupReadsByUmi -o /dev/stdout`) and then piping that into a tool that can do parallel compression, e.g. `sambamba view -f bam --nthreads=16 -o grouped.bam /dev/stdin`).  That should offload a lot of compression and IO to another process and speed things up quite a bit.  Could you give that a shot and report back what fraction of runtime you can shave off please?

**Comment by ShannonDaddy** [comment]
Thanks，I'll give it a try.

**Comment by nh13** [comment]
@ShannonDaddy did Tim's suggestion solve it for you? If not, feel free to re-open.
