### ISSUE TITLE
ProgressLogger should have a method to print the last "record" statement

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#42]
... so that we can call it when we have completed recording to get a final count.

**Comment by tfenne** [comment]
This will require either a PR to htsjdk (because the logging is all internal to the `record()` method, or breaking the dependency on htsjdk.

**Comment by nh13** [comment]
https://github.com/samtools/htsjdk/pull/1027

**Comment by tfenne** [comment]
Implemented in commit a59c4e1
