### ISSUE TITLE
First production of formal grammar for Read Structure swaps operator and length

### ISSUE THREAD

**Issue by tbl3rd** [fulcrumgenomics/fgbio#426]
https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures#formal-grammar

It appears to disagree with the examples on the page, which is helpful by the way.
Suggestion:
```
<read-structure>  ::= {<fixed-length> <operator>} <any-length> <operator>
```

Thanks.

**Comment by tfenne** [comment]
Oops, thanks for catching that!
