### ISSUE TITLE
error-rate-post-umi and error-rate-post-umi question

### ISSUE THREAD

**Issue by rosema62** [fulcrumgenomics/fgbio#429]
Can you provide any guidance in selecting appropriate values for theses parameters in CallMolecularConsensusReads?  I'm thinking the value for "post" should reflect the error rate of the sequencing technology.  The "pre" seems less certain.  Would it reflect the speculated error rate of, for instance, any PCR done before UMI addition?  What is the consequence of setting this values to low or high?

Thanks for your help

Mark

**Comment by nh13** [comment]
Mark, you're right about your intuition about the pre/post error rates, thought I'd say pre-error-rate can include ANY error prior to attaching the UMIs, not just PCR.  This could any process in sample acquisition or pre-umi preparation (ex. oxidative damage or deamination).  Similarly the post-error-rate includes anything up to but not including error on the sequencer (target-capture/amplification); we use the base qualities as measures of sequencing error.  The full explanation is on the wiki: https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Consensus-Reads

Ideally, you'd perform some experiments to empirically train (measure) each of the error terms (pre/post) and set values according to that model.  Unfortunately, that's really incorporated as part of the experimental design ahead of time (queue rant on the value of talking to bioinformaticians before running an experiment).  

In practice, the predicted base quality is capped by your pre-error-rate, as UMIs can't distinguish between things that happen before they're introduced.  The post-error-rate will affect how confident you are observing the base based on modifications after the UMI is introduced; it's a trade-off between the sequencer's predicted base quality and any other post-umi process.  

Have you tried running it on a validation sample with a variety of priors?
