### ISSUE TITLE
Running a duplicated BAM through GroupReadsByUmi

### ISSUE THREAD

**Issue by ggydush** [fulcrumgenomics/fgbio#430]
This may not be a typical use case, but I wanted to get your thoughts and suggestions on this.

I often use Fgbio to compare two (or more) BAMs using the following process:

1. Start with aligned UMI extracted BAMs
2. Add sample-specific read groups (each original BAM gets its own unique read group)
3. Merge BAMs
4. Run merged BAM through GroupReadsByUmi
5. Split GroupReadsByUmi output by read group
6. Run through duplex/molecular consensus, etc.

This allows me to compare multiple BAMs and look at common families amongst them - the above strategy works in most cases.

Where it fails, is when I try to compare a BAM with itself. This is useful when running different preprocessing strategies (downsampling, alignment, BQSR, etc.) and could be helpful in various other experiments. 

The failure happens in GroupReadsByUmi during `Assigning reads to UMIs and outputting` and the specific failure is:
```
Exception in thread "main" java.lang.AssertionError: assertion failed: Reads out of order @ D00102:HY7KVBCXY170919:HY7KVBCXY:2:2212:15387:93865/1 + D00102:HY7KVBCXY170919:HY7KVBCXY:2:2212:15387:93865/1
	at scala.Predef$.assert(Predef.scala:219)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$16(GroupReadsByUmi.scala:487)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.$anonfun$execute$16$adapted(GroupReadsByUmi.scala:486)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:486)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:80)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:48)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)
```

My current strategy is to make the read names of the duplicated BAM unique before merging (by appending a suffix on one of the duplicated BAM's read names), but I was wondering if you have any suggestions/solutions for this use case. Let me know if anything needs clarified or you want a more detailed explanation!

**Comment by ggydush** [comment]
No R1/R2 to not have trailing `/1` or `/2`. 

The problem when comparing the same BAM using the strategy above is that there are two R1 records with the same read name (different read group) and two R2 records with the same read name (different read group).

**Comment by nh13** [comment]
I see.

**Comment by nh13** [comment]
Do your read groups have the `LB` (library) tag set?

The `TemplateCoordinate` sort order is used by `GroupReadsByUmi` to pre-sort the data: https://github.com/fulcrumgenomics/fgbio/blob/3f90c873aa91ee078be020e71ef5b89283b903a9/src/main/scala/com/fulcrumgenomics/bam/api/SamOrder.scala#L160-L186

Library (from the read group) is used: https://github.com/fulcrumgenomics/fgbio/blob/3f90c873aa91ee078be020e71ef5b89283b903a9/src/main/scala/com/fulcrumgenomics/bam/api/SamOrder.scala#L172

If the library is not set, I suppose we could default to the read group id, but I'd rather the library be set.

**Comment by ggydush** [comment]
The duplicates have the same library ID, but different read groups (as they came from the same library, but were processed slightly differently). If I change the library, will they still be grouped together in the end?

**Comment by nh13** [comment]
They will not be grouped together in the end if they have different library values.  I don't understand why you would want to have the same read twice as part of a consensus call (i.e. grouped together).

**Comment by ggydush** [comment]
This could be useful for checking the effect of various preprocessing methods (i.e. downsampling, alignment strategies, BQSR). You would start with the original BAM file. The original could be downsampled, or ran through a number of preprocessing steps giving you a modified BAM file. Next, you want to see how these modifications affected your consensus calls, so you could merge the two BAMs (original + modified) and run them through Fgbio (using the method detailed in the first post). 

 If using the workflow outlined in the first post, your output would be two separate consensus BAMs (original and modified). The benefit here is that if a molecule is identical between original and modified, the family ID will be the same for both. If you had ran the two BAMs separately through GroupReadsByUmi, this would not be the case.

There are a number of other use cases that I have come across for this, but I realize they may be unusual.  My current method of renaming read names works for this particular application, but I wanted to see if you had any other recommendations.

**Comment by nh13** [comment]
Just so I understand, the major crux is that the MI tag is different between the two BAMs if you run the separately?  FWIW, I wouldn't input the same read more than once in a single invocation of the tool, but I understand why you did it.  

An easy way to solve your problem is to post-process the grouped BAMs:
1. For each BAM, have a mapping of read name to `MI` tag.
2. Join the tables based on read name, so that there are `N`  values for the `MI` tag, one for each input BAM.
3. Create a new `MI` tag based on the new table (ex. row index)
4. Update the `MI` tags in the BAMs.

**Comment by ggydush** [comment]
Thanks for your feedback and suggestion! That would definitely work for the use case described.

Unfortunately, I often have more than the duplicated BAMs in the mix (duplicated BAMs would be control samples, other bams would be samples to compare to control), so it would still be ideal to group all of the samples together at the GroupReadsByUmi level.
