### ISSUE TITLE
All the reads are filtered out by GroupReadsByUmi

### ISSUE THREAD

**Issue by fa-vio** [fulcrumgenomics/fgbio#444]
Hello,
working on UMIs , I tried to roughly follow the analysis pipeline outlined here. After some steps I end up with a mapped and annotated BAM file, where the UMI pattern is annotated with the RX tag.

I run GroupReadsByUmi and obtained an empty result file, with the log message saying all reads were filtered out because they were not part of a high confidence mapped read pair, even though the reads I am working on have a good mapping quality, surely above 30.
I tried with different grouping strategies with no success; tried tuning mapping quality flag, edits and umi-length flags, but nothing changed: the resulting BAM file was empty.

I realized the BQ tag was missing from the annotated BAM, so I run samtools calmd -r to add that tag and validated the BAM using Picard's ValidateSamFile, which reports no error. Here a sample read from the BAM file (quite a long row, sorry):

```
M05223:41:000000000-D46GK:1:1101:18741:24506    99      chr1    115252176       60      151M    =       115252186       151     AAGCTGTACCATACCTGTCTGGTCTTGGCTGAGGTTTCAATGAATGGAATCCCGTAACTCTTGGCCAGTTCGTGGGCTTGTTTTGTATCAACTGTCCTTGTTGGCAAATCACACTTGTTTCCCACTAGCACCATAGGTACATCATCCGAGT AAAABFFFFFFFGGGGGGGGGGHHHHHHHHGGHGGHHHHHHHHHHHGHHHHHHGHGGGIHHHHHHHHHHGHGGGGGGHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHFHHHHHHHHHHHHHHHHHHHGGGG MD:Z:151        RG:Z:1  NM:i:0  BQ:Z:CC@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@D    AS:i:151        XS:i:0  RX:Z:ATAGGTACCG
```

The UMI is a 10 random bp, and it has been trimmed off from 5' read2 before creating the BAM file.

I am writing here because I do not understand why the algorithm is filtering out all the reads, thus I cannot figure a way to solve my problem. Am I missing some steps?

**Comment by nh13** [comment]
Just a heads up that both maintainers are on vacation until the end of November. Thanks for your patience.

**Comment by fa-vio** [comment]
Back to that issue, I'm sorry for not posting here any log, but all it said was that all the 300 thousand reads from my `.bam` file where filtered out because not part of a high confidence mapped read pair. 

After some more investigation, I realized that data had to be handled using PICARD's tools before I could use FGBIO's, so that all expected tags are inserted into the bam file. 

What was unclear to me was that if I align fastqs using `bwa mem` and annotate the resulting `.bam` with UMIs, some required tags aren't injected in the resulting file and `GroupReadsByUmi` discards all the reads.

I loosely followed the steps explained [here](https://gatkforums.broadinstitute.org/gatk/discussion/6483/how-to-map-and-clean-up-short-read-sequence-data-efficiently) in order to obtain a clean and working `.bam` file. And that was it: I could move forward into the pipeline and call consensus sequences from reads with the same UMI tag.

**Comment by nh13** [comment]
@fa-vio thank-you for posting your solution; I am sure it will be helpful for others if they encounter this problem.

**Comment by fgvieira** [comment]
Hi @fa-vio,

I am having the same issue and not sure how to fix it? What do you mean by "handled using PICARD's tools before I could use FGBIO's"? Is it just running the BAM files through `CleanSam`? Or `ValidateSamFile`?
