### ISSUE TITLE
UMI in read name

### ISSUE THREAD

**Issue by ddaneels** [fulcrumgenomics/fgbio#459]
Hello,

I have a .bam file with the UMI's in the read name. This is my first read:

`A00154:125:HGKTMDMXX:2:2237:1588:24533:GTCGTA   129     chr1    10013   0       101M    chr18   78016220        0       TAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCAAACC   FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF,FFFFF,:FFFF,FFFFF,FF,FF,FF:F   MD:Z:98C2       PG:Z:MarkDuplicates     RG:Z:Panel-STHT-U226    NM:i:1  AS:i:98 XS:i:96`

GTCGTA is the UMI.

Is this .bam file usable for the tool GroupReadsByUmi? Because the UMI is not in the RX tag.

**Comment by tfenne** [comment]
Unfortunately no.  You'll need to write a quick script to extract the UMI from the read name and insert it into the `RX` tag.
