### ISSUE TITLE
Consensus caller should filter consensus calls that have too many Ns

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#46]
reported by @tfenne: `bwa mem` runs slowly with reads with even a small # of Ns.

**Comment by tfenne** [comment]
I think we can close this @nh13.  I think that between quality trimming, insert-size trimming and the cigar/alignment filtering we've solve most of this in orthogonal ways, and there's FilterConsensusReads to take care of the rest.  Do you agree?

**Comment by nh13** [comment]
@tfenne we filter _after_ we re-align, since we regenerate the nm/md/uq tags in the filtering tool (after the filters potentially mask bases).  Therefore, I still think this relevant if we are ok with having some reads filtered _during_ consensus calling.

**Comment by tfenne** [comment]
@n13 My main point here is that I think we were generating reads with a lot of Ns in them because of bugs/things not handled well in consensus calling, e.g. mis-aligned reads, not trimming adapters for duplex etc.

**Comment by n13** [comment]
You meant to mention @nh13 in this, not me ;)

**Comment by tfenne** [comment]
Doh!  My apologies @n13.

**Comment by n13** [comment]
No problem. I was a bit puzzled at first, but looks like a cool project haha
