### ISSUE TITLE
Single primer designs and TrimPrimers

### ISSUE THREAD

**Issue by jhl667** [fulcrumgenomics/fgbio#463]
Does TrimPrimers support single-primer designs?  For instance, can I just enter one set of start and end coordinates per region?  Or, could I just enter the exact same coordinates for both left and right?

Thanks!

**Comment by nh13** [comment]
It does not at this time.

**Comment by jhl667** [comment]
This would be useful functionality, for instance for the QIAseq assay that relies on single primer extension.

**Comment by nh13** [comment]
@jhl667 unfortunately we typically add functionality based on if we personally find it useful, or more often if our clients find it useful.  Feel free to reach out us if you or Qiagen think that we could be of help: http://www.fulcrumgenomics.com/contact/
