### ISSUE TITLE
a question when calling Variant 

### ISSUE THREAD

**Issue by elainebblythe** [fulcrumgenomics/fgbio#469]
hi,I used fgbio::CallMolecularConsensusReads and got the consensus reads ,then I want use the consensus.bam to find Variant  by GATK.I have a question about it.

If there are four reads, they are consensus reads,their sequences are different at one site

-----------------A----------     genome
-----------------A----------
-----------------T-----------
-----------------A-----------
-----------------A-----------

So the T is certainly not a true mutation when I calling Variant, and I wonder what fgbio would do with a point like this, would it turn this T into N?
CallMolecularConsensusReads has already handle this point? Can I directly apply this result to GATK?

**Comment by tfenne** [comment]
@elainebblythe If the four reads in your example are four reads directly from the sequencer, and they are all identified as originating from the same molecule (i.e. same `MI` tag after running `GroupReadsByUmi`) then almost certainly the consensus read that is generated will have a `A` at the position in question.  Depending on the base qualities o the `A` and `T` basecalls the base quality in the consensus BAM may be lower than surrounding bases.  So, yes, you should be able to feed this directly into the GATK and the GATK will never see the error.

If on the other hand your example is four consensus reads, that's a different problem.  In that case there was enough evidence to create a consensus read with a `T` basecall at that position, and if you feed the consensus reads to GATK it will see that.  If that's the case you have a couple of options:  a) try using `FilterConsensusReads` with various settings to see if the `T` basecall/read is lower quality or based on fewer input reads and can be filtered out, or b) tune your invocation of the GATK to only identify sites above some threshold allele fraction.

**Comment by elainebblythe** [comment]
thanks,
My analysis process is :
picard::FastqToSam-------ExtractUmisFromBam---------align------picard::MergeBamAlignment-----GroupReadsByUmi------CallMolecularConsensusReads

My goal is to find true somatic mutations by GATK,So should I use FilterConsensusReads next?



elaineylq@163.com
 
From: Tim Fennell
Date: 2019-03-12 21:17
To: fulcrumgenomics/fgbio
CC: elainebblythe; Mention
Subject: Re: [fulcrumgenomics/fgbio] a question when calling Variant (#469)
@elainebblythe If the four reads in your example are four reads directly from the sequencer, and they are all identified as originating from the same molecule (i.e. same MI tag after running GroupReadsByUmi) then almost certainly the consensus read that is generated will have a A at the position in question. Depending on the base qualities o the A and T basecalls the base quality in the consensus BAM may be lower than surrounding bases. So, yes, you should be able to feed this directly into the GATK and the GATK will never see the error.
If on the other hand your example is four consensus reads, that's a different problem. In that case there was enough evidence to create a consensus read with a T basecall at that position, and if you feed the consensus reads to GATK it will see that. If that's the case you have a couple of options: a) try using FilterConsensusReads with various settings to see if the T basecall/read is lower quality or based on fewer input reads and can be filtered out, or b) tune your invocation of the GATK to only identify sites above some threshold allele fraction.

**Comment by nh13** [comment]
Did you try using `FilterConsensusReads`?  Please re-open if you have any more questions.
