### ISSUE TITLE
CallDuplexConsensusReads  removed too many reads

### ISSUE THREAD

**Issue by yumenxx** [fulcrumgenomics/fgbio#471]
Dear Sir，i have a question that after GroupReadsByUmi we can see same consensus reads as follows:
A00202:302:HJ5KMDSXX:3:1107:19099:20635 99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTGGAACAGG       FFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFF:,::FFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFF:,FF,FFF,FF:FFFF:FF,F,:,F::,,,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:25 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1107:19099:20635 147     chr12   25398268        60      77S68M  =       25398268        -68     TTAATGATCCGGCGCCCACCGAGATCTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       ,,,,,::,,F:,F,:FF:FF:F,F,,FFFFFFFFFFFFFFF,F,FF,FFFF,:F,FFFFFFFFFFFFFFFFFFFFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1153:22987:4946  99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTTGAAAATG       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFFFFFFFFFF::FFFFF,:,:,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1153:22987:4946  147     chr12   25398268        60      77S68M  =       25398268        -68     TTAATGATACGGCGACCACCGAGATCTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       FFFFF:FFFFFFFFFFFFFF:F:FFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1167:22155:31876 99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTTGAAAAGG       FFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF:FF,:F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,:FF:F:F:FFF:F:FF:,:F,F::,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1167:22155:31876 147     chr12   25398268        60      77S68M  =       25398268        -68     AACAGGAGACGGCGCCCACCGAGATCTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       ,,,,,,:,:F,,F,,FF,FF,F,F,F:FFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:11 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1301:29559:5462  99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTTGAAAAGG       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFFFF,:FFF:FF,:F::FF,:,,,:       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1301:29559:5462  147     chr12   25398268        60      77S68M  =       25398268        -68     TTAATGATACGGCGACCACCGAGATCTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       FFFFF:F::FFFFFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1305:28302:27962 99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTTGAAAAGG       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F,FFFFFF:FF,F:F,:FF,FF,,,:,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1305:28302:27962 147     chr12   25398268        60      77S68M  =       25398268        -68     TTAAGCACCCGCCCCCCACCTCTAACTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       ,,,,,,,,,F,,,,,:::FF,,,F,,::::FFFFF:FFFF:FFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1365:2058:32205  99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCGCGTATGCCGTCTTCTGCTTGAAAAGG       FFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FF::FFFFFFFF:::F:FFF,,,,,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1365:2058:32205  147     chr12   25398268        60      77S68M  =       25398268        -68     CGAATGCACCGGCCCCCCCCGACAACTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       ,,::,,,,,F:,F,,FF,FF,,,,,FFFFFF:F,FFFFFFF,FFF,,,FFFFFFFFFFFFFFF:FF:FFFF:FFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1419:2211:12868  99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTTGAAAAGG       FFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFF:FF:FFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFF:,FFFF,FFFFFFF:FFFF,,,:,,,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1419:2211:12868  147     chr12   25398268        60      77S68M  =       25398268        -68     TTAATCACACGGCGCCACCCGAGATCTACACATATGCGCACCCTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       ,,F,:,F,,F,,F,,F,,F,,,,F,,FF:::FFFFFFF:FF,FFFFFFFFFFFFFFFFFFFFF:FFF:FFFFFFFFFFFFFFFF:FFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1546:5936:23860  99      chr12   25398268        60      68M77S  =       25398268        68      ACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATAAAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTGATCGTATCTCGTATGCCGTCTTCTGCTTGAAAAGG       FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,FFF:FFFFFFFF,::F:,FF::,,,,       ZA:Z:GGA        ZB:Z:CCC        MC:Z:77S68M
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:64 RX:Z:GGA-CCC
A00202:302:HJ5KMDSXX:3:1546:5936:23860  147     chr12   25398268        60      77S68M  =       25398268        -68     TTAATGACCCGGCGACCACCGAGATCTACACATATGCGCACACTCTTTCCCTACACGACGCTCTTCCGATCTGGAGTACTCTTGCCTACGCCATCAGCTCCAACTACCACAAGTTTATATTCAGTCATTTTCAGCAGGCCTTATA       ,,:F,,F,,F,:F::FF,FF,F,FFFFFFFFF::FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F       ZA:Z:GGA        ZB:Z:CCC        MC:Z:68M77S
     MD:Z:16C51      PG:Z:bwa        RG:Z:A  MI:Z:166290/A   NM:i:1  MQ:i:60 UQ:i:37 AS:i:63 RX:Z:GGA-CCC

They have the same UMI:GGA-CCC, and in this position have no adjacent UMI consensus them. There reads  also have a good quality.
Now, i am confused when i directly sort and alignment the output file  from CallDuplexConsensusReads(without FilterConsensusReads ) to hg19, i can not find those consensus read in IGV.
Why those reads directly discard in process CallDuplexConsensusReads instead of getting one original molecule?

The parameters as follow:

java -Xmx4g -jar /home/xiaolezhu/analysis_software/fgbio-0.6.1.jar GroupReadsByUmi --input=mappedAAA.bam --output=grouped.bam --strategy=paired --edits=1 --min-map-q=20

java -Djava.io.tmpdir=tmpDir -Xmx4g -jar /home/xiaolezhu/analysis_software/fgbio-0.6.1.jar CallDuplexConsensusReads --input=grouped.bam --output=consensus.unmapped.bam --error-rate-pre-umi=45 --error-rate-post-umi=30 --min-input-base-quality=10

Look forward to your reply

**Comment by nh13** [comment]
Can you post an example BAM (with header) and we can take a look?  My apologies for the late reply.

**Comment by jianglidu** [comment]
did you have solve the question about "CallDuplexConsensusReads removed too many reads" ? now, i have the same question. after   "CallDuplexConsensusReads",  perhaps only one read is reserved.

**Comment by nh13** [comment]
@yumenxx feel free to re-open if you can post an example BAM.

@jianglidu can you open an new issue and post a test case?
