### ISSUE TITLE
Is ExtractUmisFromBam suitable for single-strand UMI?

### ISSUE THREAD

**Issue by elainebblythe** [fulcrumgenomics/fgbio#479]
my data is paired-end sequence,but only R1 have UMI,I want to know whether fgbio can handle such data

**Comment by tfenne** [comment]
Yes, so long as each read (R1 and R2) have some template/genomic bases you'll be fine.  UMIs are seen as belonging to the template/insert/read-pair, not just the read they are sequenced in.
