### ISSUE TITLE
Losing lots of sequences

### ISSUE THREAD

**Issue by schuc041** [fulcrumgenomics/fgbio#480]
When I run the CallMolecularConsensusReads, I'm losing a lot of my sequences. I should have tons of reads based on the number of unique UMIs in the original file, but when I run it, I go from 162,000+ reads to just 48. Here's the code:

$fgbio GroupReadsByUmi -s Adjacency -i tagged_fqtobam_mapped.bam -o groupedoutput.bam -l 14

$fgbio SortBam -i groupedoutput.bam -o sortedoutput.bam -s TemplateCoordinate
$fgbio  CallMolecularConsensusReads -i sortedoutput.bam -o consensusTest.bam -M 1

I've attached the output files from each of these so you can see what I mean. If you have any ideas for what might be causing this loss, please let me know!

[OutputBams.zip](https://github.com/fulcrumgenomics/fgbio/files/3060906/OutputBams.zip)

**Comment by nh13** [comment]
There's a single group that has 160,392 reads assigned to it:

```
samtools view groupedoutput.bam | cut -f 16 | uniq -c
   2 MI:Z:0
   2 MI:Z:1
  12 MI:Z:2
   2 MI:Z:3
 298 MI:Z:4
 154 MI:Z:5
  44 MI:Z:6
   8 MI:Z:7
   8 MI:Z:8
   6 MI:Z:9
   8 MI:Z:10
  34 MI:Z:11
 190 MI:Z:12
160392 MI:Z:13
   4 MI:Z:14
 114 MI:Z:15
1030 MI:Z:16
  70 MI:Z:17
  36 MI:Z:18
  28 MI:Z:19
  78 MI:Z:20
   8 MI:Z:21
   4 MI:Z:22
   2 MI:Z:23
```

The RX for the group is `TGGAATAGATAAGG`.   There are 159,638 reads with exactly that RX value:

```
samtools view groupedoutput.bam | grep -c RX:Z:TGGAATAGATAAGG
159638
```

So I don't see a diverse set of UMIs:
```
samtools view groupedoutput.bam | cut -f 21 | sort | uniq -c | sort -n -k 1 | tail
  68 RX:Z:TTGGAATAGATAAG
  76 RX:Z:TAGAATAGATAAGG
  78 RX:Z:GAATAGATAAGGCC
  78 RX:Z:TGTAATAGATAAGG
  82 RX:Z:TGGAATATATAAGG
  92 RX:Z:TGAAATAGATAAGG
 154 RX:Z:GTGGAATAGATAAG
 178 RX:Z:ATGGAATAGATAAG
1014 RX:Z:GGAATAGATAAGGC
159638 RX:Z:TGGAATAGATAAGG
```

How did you extract the UMIs and place them in the RX tag?

**Comment by schuc041** [comment]
Hello,

Thank you for sending this along. Based on this we were able to figure out
that we were using the wrong input (a fastq file with the UMIs already
extracted vs the original) and have fixed the problem!

Thank you!
Morgan

*Morgan Meissner*
*University of Minnesota - PhD Candidate, Mansky Lab*
Molecular, Cellular, Developmental Biology, and Genetics

**Comment by schuc041** [comment]
Nils,

I am hoping to call SNPs from the consensus calls created with
CallMolecularConsensusReads and while I can run samtools view and samtools
sort on these output BAMs  and picard ValidateSamFile doesn't fine errors
neither freebayes or samtools mpileup seem to be able to parse the BAMs to
call SNPs. Freebayes gives me the following error ERROR(freebayes): Could
not get first alignment from target
and samtools/bcftools mpileup writes an empty file without giving an error.
I am curious if you have taken these consensus reads into SNP calling and
if you have any guidance.

Thanks
Morgan


*Morgan Meissner*
*University of Minnesota - PhD Candidate, Mansky Lab*
Molecular, Cellular, Developmental Biology, and Genetics

**Comment by nh13** [comment]
Absolutely we have called variants from the BAMs. Can you look in IGV and find a polymorphic site, extract those reads and share them? Can you check the version of freebayes/bcftools and post your command line?
