### ISSUE TITLE
ErrorRateByReadPosition does not work without "reference.dict"

### ISSUE THREAD

**Issue by aerijman** [fulcrumgenomics/fgbio#494]
Hi,

ErrorRateByReadPosition only works if a`<path_to_reference_genome>.dict` file has been produced, for instance with samtools dict.

__Is this intentional?__ I don't see any gain on it and also I don't think this is referenced in the documentation.

Thank you

**Comment by nh13** [comment]
This is really common with fgbio and Picard tools, though I don't think we have documented that in a lot of places, but we use the ".dict" file or (".fai" file) to get what we call the sequence dictionary, akin to the sequence header lines in the BAM file.  This ensures that all the inputs have the same set of references (ex. `SQ` lines in a SAM/BAM, `contig` lines in a VCF, the `.dict` for references). 

Use picard's `CreateSequenceDictionary` to build one.
