### ISSUE TITLE
Is there any reference to cite the use of fgbio?

### ISSUE THREAD

**Issue by kysbbubbu** [fulcrumgenomics/fgbio#504]
Hello, I have been used fgbio for UMI deduplication process.

Is there anyway to cite fgbio in the methodology session of manuscript?

Thank you for developing and sharing a nice tool

**Comment by tfenne** [comment]
Thanks for the kind words.  We haven't published any of our work, so if you could please just cite the website at either https://github.com/fulcrumgenomics/fgbio or http://fulcrumgenomics.github.io/fgbio/ that would be great.
