### ISSUE TITLE
Add tooling & docs to replace picard's SamToFastq and MergeBamAlignment

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgbio#508]
Our current UMI pipelines tend to involve going to uBAMs with UMIs in them, then using a chain of `picard SamToFastq | bwa or other aligner | MergeBamAlignment`.  Both of the picard tools have grown in complexity over the years, and can be quite intimidating for folks who haven't used them before.  In addition the need to sort BAMs into htsjdk-queryname order adds an extra time-consuming sort to the pipeline.

There's a toolkit out there, I forget which one, that does this differently by jamming all the extendeds tags and flags etc. into the fastq header before alignment, and then re-adds those to sam records on the way back out.  I really like this approach because it a) makes things vastly simpler due to not needing to sync up the uBAM and aligned BAM and b) enables a streaming approach since the uBAM needs to be read only once.

I think we should develop a pair of tools in fgbio that use that approach and have the functionality we need, so that we can document a pipeline from raw FASTQs through to mapped/filtered consensus reads that relies solely on fgbio + an aligner.

- Both tools should have a capability similar to FifoBuffer in picard, to cache data on the way to/from the aligner to speed up that connection point
- BamToFastq should:
  - Take any query-sorted or query-grouped BAM file
  - Unmap / revcomp reads as needed
  - Optionally, but defaulting to true, pack all data from a BAM record into the FQ header
  - Be able to produce a single interleaved fastq, or a pair of fastqs
- PreprocessAlignedBam (better names appreciated) should:
  - Take the aligned BAM stream and unpack any info in the FQ header back into the SAM record
  - Clip FR reads that extend beyond the end of their insert (might require re-calcing some tags)
  - Optionally sort the data into a chosen (default coordinate?) order
  - Be able to reverse and revcomp extended tags based for reads that are mapped to the R strand

Questions:
- Do we want to handle adapter clipping like Picard does with the `XT` tag?

**Comment by ShengyaoChen** [comment]
>There's a toolkit out there, I forget which one, that does this differently by jamming all the extendeds tags and flags etc. into the fastq header before alignment, and then re-adds those to sam records on the way back out. I really like this approach because it a) makes things vastly simpler due to not needing to sync up the uBAM and aligned BAM and b) enables a streaming approach since the uBAM needs to be read only once.

I have a related question here. I am trying to use a cmd below to achieve what you mentioned here. However, it looks like samtools fastq -T doesn't support B (numeric-array-type) tags like cd and ce (The other tags works well). I am wondering if there is some updates on your side to have a fgbio tool for this functionality as you described here? 
~~~
samtools fastq -T MI,QX,RX,cD,cE,CM,cd,ce $ubam | bwa mem -pC $ref - > $out
~~~

Thank you so much!

**Comment by nh13** [comment]
@ShengyaoChen take a look at the workflow here: https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md.  Create an unmapped BAM with `fgibo FastqToBam`, then map with `samtools fastq | bwa mem | fgbio ZipperBams`.

**Comment by ShengyaoChen** [comment]
@nh13 Thank you so much!
