### ISSUE TITLE
Efficient computation of "or" with an array of log probabilities.

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#51]
The previous implementation of `NumericTypes.or(values: Array[LogProbability]): LogProbability` did not use a rolling sum, but now we do:  https://github.com/fulcrumgenomics/fgbio/pull/50

Figure out a way to make this more efficient.  Likely the array is only a few elements long (four in a lot of cases).  See the use of this method in the `ConsensusCaller`.

**Comment by tfenne** [comment]
@nh13 Do you still care about this? 18 months later I'm tempted to just close it.

**Comment by nh13** [comment]
Lets close it until it is an issue.
