### ISSUE TITLE
unwanted trimming of overhanging reads during CallMolecularConsensusReads

### ISSUE THREAD

**Issue by tomSimonet** [fulcrumgenomics/fgbio#526]
Hello,
I'am using GroupReadsByUmi followed by CallMolecularConsensusReads on personal paired-end data;
in some amplicons, paired reads overlap and even overhang, eg the 3'end of the reverse read ends before the 5' end of the forward read :
.....----->
<---------
this is potentially due to primer trimming on F1 read, in the fastq;
in these cases, CallMolecularConsensusReads trim the reads to just the overlapping part:
.....----->
.....<-----
the pb is that this makes me loosing some wanted dna variant is the following variant calling;
- is this happens for an obvious reason?
- is there a way to avoid it ?

thanks!!

cmd and example:

1) GroupReadsByUmi :
java -jar ./fgbio-1.0.0.jar GroupReadsByUmi --input=S1_setMQ.bam --output=S1_umiGrp.bam --family-size-histogram=S1_hist.txt  --raw-tag=RX --assign-tag=MI --strategy=adjacency --edits=1 --min-map-q=20
samtools view S1_umiGrp.bam | grep "RX:Z:CGAAGGGCTATG"
NB501480:383:HK2MCAFXY:1:11306:24370:4112	99	chr1	120465271	60	79M	=	120465226	79	CAAGAGGGTATGACAGGGTCCCCTGAATGGCGTGAGAGGCCAGGAGAGCTGCTGCTGCATCCGTGTTCTTGAAGCAGTG	EEE6EE//AEAE/E/EEE/E/EEE/A/EEA/EE/E/EEE<A///EEE/EE6EAA<E/EEEEAEAEEAA<A/A/EEEE//	MC:Z:4S124M	MD:Z:25T53	RG:Z:19SL00999_S11_1	MI:Z:350549	NM:i:1	MQ:i:60	AS:i:74	XS:i:20	RX:Z:CGAAGGGCTATG
NB501480:383:HK2MCAFXY:1:11306:24370:4112	147	chr1	120465226	60	4S124M	=	120465271	-79	TTTGGCCACCTTTCCCCTTTACACCAGTGCCACTCACTGTCGACTGACACAAGAGGGTATGACAGGGTCCCCTGTTGGGCGTGAGAGGCCAGGAGAGCTGCTGCTGCATCCGTGTTCTTGAAGCAGTG	</A//A<6<EEEE/<</</</EE/EAEEA/EA/</AE/E///6/AAEEA//E</E/EAEEE<<EE/E//EEE/AA//EA/EEAEA//E/EAEE<AAE6EE//EA/EA</E/E/E/66EEEE/E/EEEE	MC:Z:79M	MD:Z:35A4A30A0T51	RG:Z:19SL00999_S11_1	MI:Z:350549	NM:i:4	MQ:i:60	AS:i:104	XS:i:20	RX:Z:CGAAGGGCTATG

2) CallMolecularConsensusReads:
java -jar ./fgbio-1.0.0.jar CallMolecularConsensusReads --input=S1_umiGrp.bam --output=S1_umiCss.bam --tag=MI --read-name-prefix=csr --error-rate-pre-umi=30 --error-rate-post-umi=30 --min-reads=1 --min-input-base-quality=10 --min-consensus-base-quality 0
samtools view S1_umiCss.bam | grep "RX:Z:CGAAGGGCTATG"
csr:350549	77	*	0	0	*	*	0	0	CAAGAGGGTATGACAGGGTCCCCTGTATGGCGTGAGAGGCCAGGAGAGCTGCTGCTGCATCCGTGTTCTTGAAGCAGTG	???>??>>????>?>???>?>???>$>???>??>?>?????>>>???>??>?????>?????????????>?>????>>	cD:i:2	cE:f:0.00632911	RG:Z:19SL00999_S11_1	MI:Z:350549	cM:i:2	RX:Z:CGAAGGGCTATG
csr:350549	141	*	0	0	*	*	0	0	CACTGCTTCAAGAACACGGATGCAGCAGCAGCTCTCCTGGCCTCTCACGCCATACAGGGGACCCTGTCATACCCTCTTG	????>?>????>>>?>?>?>???>??>>??>????????>?>>?????>??00??>??>>>?>?????????>?<??>>	cD:i:2	cE:f:0.0126582	RG:Z:19SL00999_S11_1	MI:Z:350549	cM:i:2	RX:Z:CGAAGGGCTATG

**Comment by nh13** [comment]
@tomSimonet can you share a SAM/BAM that's been subsetted to just the reads with the `MI` tag `350549` from the `GroupReadsByUmi` BAM (please included the SAM header lines too)?  This would help us debug the issue. 

```
samtools view -H <in.bam> > test.sam
samtools view <in.bam> | grep "MI:Z:350549" >> test.sam
```

**Comment by tomSimonet** [comment]
Hello,

Here is the sam for the group 350549, and , in case it might help, another sam for the whole UMI CGAAGGGCTATG it is derived from.

Many thanks

Thomas

 

De : Nils Homer [mailto:notifications@github.com] 
Envoyé : mercredi 4 septembre 2019 19:25
À : fulcrumgenomics/fgbio
Cc : tomSimonet; Mention
Objet : Re: [fulcrumgenomics/fgbio] unwanted trimming of overhanging reads during CallMolecularConsensusReads (#526)

 

@tomSimonet <https://github.com/tomSimonet>  can you share a SAM/BAM that's been subsetted to just the reads with the MI tag 350549 from the GroupReadsByUmi BAM (please included the SAM header lines too)? This would help us debug the issue.

samtools view -H <in.bam> > test.sam
samtools view <in.bam> | grep "MI:Z:350549" >> test.sam

**Comment by nh13** [comment]
@tomSimonet I see the place where it is trimming: https://github.com/fulcrumgenomics/fgbio/blob/master/src/main/scala/com/fulcrumgenomics/umi/UmiConsensusCaller.scala#L247-L256.  I could add an option to skip this step, but I am genuinely curious about your experiment.  My intuition is that if the 3' end of R2 reads beyond the 5' end of R1 (forward/reverse read pairs), then the 3' end R2 reads into the UMI/adapter/primer of R1.  Could you tell us more about your experiment where this wouldn't be the case?

**Comment by tomSimonet** [comment]
You're right, it falls within the R1 specific primer, which I have trimmed only from the R1 read, in order to keep this region (amplicons are in some place not sufficiently overlapping) and to get a less biased estimation of the allelic depth of any variant embedded within it (so only based on the R2 read).

![qiaseq](https://user-images.githubusercontent.com/43646785/65695127-3c5d7a80-e077-11e9-93e9-36803f03bd95.png)

but may be I was wrong to do so?
If no, an option to disable this trimming would be great, in this case

**Comment by nh13** [comment]
@tomSimonet if your amplifying products based on the gene specific primer, then all products will contain the complementary sequence of the GSP .   So when you sequence from read 2, you'll read through the template (sample DNA fragment) and into the primer sequence.  If there's a variant under primer, you get worse amplification (i.e. allele amplification bias), but the products themselves will always have the same sequence as the primer.  So you'll need to trim it off on both ends of the read: for read one, it's at the start of the read, and for read two, it can be variably at the end of the read. It's the same principle when you have short inserts and reading into adapters.  I would not use any of the synthetic (i.e. primer) bases as part of my allele depth for the sample (or for variant calling).
