### ISSUE TITLE
Overzealous filtering of reads during CallDuplexConsensusReads

### ISSUE THREAD

**Issue by theisaacwong** [fulcrumgenomics/fgbio#527]
Hi,

I'm using `GroupReadsByUmi` followed by `CallDuplexConsensusReads` on high read depth, high quality paired end reads. `GroupReadsByUmi` creates a 25GB bam file. When I then call `CallDuplexConsensusReads`, the ouput is only about 500MB. I was expecting a similarly sized ouput file. 

Here's the commands I run
> `java -Xmx64g -jar fgbio.jar GroupReadsByUmi --strategy=paired --input=my_sample_mapped.bam" --output=my_sample_groupedUMI.bam" --raw-tag=RX --assign-tag=MI --min-map-q=10 --edits=1` 

> `java -Xmx64g -jar fgbio.jar CallDuplexConsensusReads --input=my_sample_groupedUMI.bam" --output=my_sample_ds_consensus_unaligned.bam" --error-rate-pre-umi=45 --error-rate-post-umi=30 --min-input-base-quality=10 --threads=12`

Am I misunderstanding the output of `CallDuplexConsensusReads` ?
Is there a next step I need to do such as merging the `CallDuplexConsensusReads`'s output with some other bam file in order to get a bam with all duplex consensus reads?

**Comment by tfenne** [comment]
Hi @theisaacwong I think you are indeed misunderstanding the results here.  `CallDuplexConsensusReads` generates a single consensus read from multiple input reads.  I.e. if you have 6 F and 6 R reads from the same molecule (i.e. with the same duplex UMI) then you'll see a 6->1 reduction in reads for that molecule in the output.  Generally the goal for duplex experiments is to have 2-3 reads per strand, so 4-6 reads per duplex, so a reduction of 5-10 fold would be totally normal.  Depending on the actual coverage of the molecules in your library it could be much higher.

Can you run `GroupReadsByUmi` with the `--family-size-histogram` option?  That will give a nice histogram of raw reads per duplex molecule, which would help inform this.

**Comment by tfenne** [comment]
The other possibility here is that the `--min-reads` defaults are causing a lot of reads to be discarded.  By default it requires at least 1 read from each strand to form a duplex consensus.  If you have a lot of molecules with only reads from one of the two original strands, then a lot of your data will be discarded/filtered and not make it into consensus.
