### ISSUE TITLE
Unmapped reads dropped out with GroupReadsByUmi 

### ISSUE THREAD

**Issue by chadisaad** [fulcrumgenomics/fgbio#529]
Why unmapped reads are removed from BAM file when doing GroupReadsByUmi ? even with "--min-map-q 0" param

**Comment by nh13** [comment]
@chadisaad see [the tool documentation for `GroupReadsByUmi`](http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html

The tool was designed for the case where the same UMI could be present in two or molecules, so we need to use the genomic coordinates.  I suppose if you'd like it to ignore coordinates, you could assign all reads to the same coordinate (ex `chr1:1`), but I would bet you get a ton of collisions.  It's the same reason why when we perform PCR duplicate marking/removal, we use genomic coordinates (and UMI if we have it).
