### ISSUE TITLE
AnnotateBamWithUmis 

### ISSUE THREAD

**Issue by hustal** [fulcrumgenomics/fgbio#536]
Hi,

I used the following command to annotate UMI in bam files,

java -jar ~/My_Tools/fgbio-1.0.0.jar AnnotateBamWithUmis -i ~/Test_Output/SRR4238351s.bam -f ~/Test_Data/SRR4238351s_umi.fastq -o ~/Project/UMI/SourceCode/test.bam

Sometime it works fine but sometime I got the following error,

[2019/10/10 13:45:00 | FgBioMain | Info] Executing AnnotateBamWithUmis from fgbio version 1.0.0 as husain.talukdar@husaintmbp on JRE 12.0.2+10 with snappy, JdkInflater, and JdkDeflater
[2019/10/10 13:45:00 | AnnotateBamWithUmis | Info] Reading in UMIs from FASTQ.
[2019/10/10 13:45:00 | AnnotateBamWithUmis | Info] Reading input BAM and annotating output BAM.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000108bd8ea7, pid=14489, tid=6915
#
# JRE version: Java(TM) SE Runtime Environment (12.0.2+10) (build 12.0.2+10)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (12.0.2+10, mixed mode, sharing, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libgkl_compression6831549093918918270.dylib+0x6ea7]  deflate_medium+0x867
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/husain.talukdar/Project/UMI/SourceCode/hs_err_pid14489.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6
  
I appreciate your help to solve this problem.

Thanks.

Best,
Husain

**Comment by nh13** [comment]
See both https://github.com/fulcrumgenomics/fgbio/pull/534 and See: https://github.com/Intel-HLS/GKL/issues/101. It looks like Intel has a bug in their code that makes it not work on Mac 10.14+
