### ISSUE TITLE
DemuxFastqs --illumina-standards isn't adding barcode or Umi

### ISSUE THREAD

**Issue by hydriniumh2** [fulcrumgenomics/fgbio#540]
Hi,
I'm currently trying to demultiplex some paired end 300bp samples with the UMI integrated in index2 and I found your DemuxFastqs tool, which seems like it would fit our use case very well. However, our workflow currently uses fastq input rather than uBams, and it seems that if you set --illumina-standards it doesn't include the barcode or umi in the header, despite appearing in the uBAM output.
For example the command 
`fgbio DemuxFastqs --inputs R1.fastq.gz I1.fastq.gz I2.fastq.gz R2.fastq.gz --read-structures 300T 8B 8B10M 300T --metadata SampleSheet.csv --metrics metrics.txt --output Demux --output-type fastq  --threads 4 --illumina-standards true --include-all-bases-in-fastqs true`
Returns this output:
`@M02528:282:000000000-CLLT6:1:1101:17214:1109 2:N:0:0`
When I would expect something like this:
`@M02528:282:000000000-CLLT6:1:1101:17214:1109:TTTTCTCCTC 2:N:0:AACACAGA+CTAAGCCT`
The corresponding line in the uBAM includes the barcode and umi in `BC` and `RX` respectively.
Am I missing a setting in the command or is this a bug? Any insight would be appreciated.
Thank you

**Comment by nh13** [comment]
Please read the usage of the tool, in particular the section "Illumina FASTQ File Naming" copied here

```

The output FASTQs will be written according to Illumina naming standards when the '--illumina-standards' option is
specified. This requires that the input fastq files contain Illumina format read names with comments containing
'<ReadNum>:<FilterFlag>:<0>:<SampleNumber>' (no angle brackets). The output create output files with Illumina names:

  1. The file extension will be '_R1_001.fastq.gz' for read one, and '_R2_001.fastq.gz' for read two (if paired end).
  2. The per-sample output prefix will be '<SampleName>_S<SampleOrdinal>_L<LaneNumber>' (without angle brackets).
```

**Comment by nh13** [comment]
Also, the purpose of this option was to enable upload of the FASTQs to BaseSpace, which requires read names to be in a particular format: https://help.basespace.illumina.com/articles/descriptive/fastq-files/

```
@<instrument>:<run number>:<flowcell ID>:<lane>:<tile>:<x-pos>:<y-pos> <read>:<is filtered>:<control number>:<sample number>
```

**Comment by hydriniumh2** [comment]
I see, thank you for clarifying

**Comment by hydriniumh2** [comment]
Its not a problem. `samtools fastq` and some awk can convert the uBAM to the desired format, but I wanted to check if I could cut down on some steps.
