### ISSUE TITLE
CollectDuplexSeqMetrics needs raw-tag argument

### ISSUE THREAD

**Issue by danielnavarrogomez** [fulcrumgenomics/fgbio#547]
Hello!

I use different tags than "RX" on my bam files and that works fine for all the tools I use from fgbio but CollectDuplexSeqMetrics which doesn't have an option to change it from the default one.

As an example, if I use this command:
java -jar fgbio GroupReadsByUmi --input=INPUT.bam --output=OUTPUT.bam --strategy=paired --raw-tag=XD --min-map-q=30

The output file is not usable for CollectDuplexSeqMetrics

**Comment by nh13** [comment]
@danielnavarrogomez see #548
