### ISSUE TITLE
CorrectUmis  --umi-files  Q: what is the rules of the umi sequence in “umis.txt” 

### ISSUE THREAD

**Issue by fengshuaisheng** [fulcrumgenomics/fgbio#559]
hi : 
   I hava a question while using the CorrectUmis, The parameter --umi-files of CorrectUmis can specify a file eg: umis.txt, the description of the umi file is "File of UMI sequences, one per line."  but I don't know how to definition of one UMI sequence, eg: the ahead of 12bp is UMI(random sequences) and 13-20bp is common seq (AATGTACAGTATTGCGTT) my fastq files of read1, and 21bp is  common seq in  fastq files of read2. So how can I editor my  "umis.txt" or what is the rules when editor UMI sequence ??? 

Thank you very much!!!

**Comment by nh13** [comment]
The tool expects the UMIs to already be in the `RX` tag to correct them.  You can use `ExtractUmisFromBam` to set the tag on each read prior to correcting them.
