### ISSUE TITLE
Unable to execute CallMolecularConsensusReads

### ISSUE THREAD

**Issue by ichorny** [fulcrumgenomics/fgbio#566]
I would like to collapse my reads using CallMolecularConsensusReads but have been unsuccessful. 

I converted my bcl2fastq tagged and bwa mem aligned reads to have an RX tag for the UMI.

I also tested my uncollapsed data with umi_tools and was able to collapse the reads using both the native tag from bcl2fastq and the RX tag I inserted into the BAM file. 
https://github.com/CGATOxford/UMI-tools

I am running the following command. 

logFile=$prefix.log
minMQ=50
minBQ=10
tag='RX'
minreads=3
sortType='TemplateCoordinate'

java -jar $jarFile SortBam -s $sortType -i $bamName -o $prefix.sorted.bam
java -jar $jarFile CallMolecularConsensusReads -i  $prefix.sorted.bam -o $prefix.collapsed.bam -M $minreads -t $tag -m $minBQ

I get the following log out. I replaced the number of reads below with N

[2020/02/13 22:25:14 | CallMolecularConsensusReads | Info] Total Raw Reads Considered: N.
[2020/02/13 22:25:14 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Orphan Consensus Created: N (0.9059).
[2020/02/13 22:25:14 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Mismatching Cigars: N (0.0027).
[2020/02/13 22:25:14 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Low Base Quality: N (0.0000).
[2020/02/13 22:25:14 | CallMolecularConsensusReads | Info] Raw Reads Filtered Due to Insufficient Support: N (0.8850).
[2020/02/13 22:25:14 | CallMolecularConsensusReads | Info] Consensus reads emitted: N
[2020/02/13 22:25:14 | FgBioMain | Info] CallMolecularConsensusReads completed. Elapsed time: 5.77 minutes.

On the plus side it runs really fast!

Thanks in advance for your help.

**Comment by nh13** [comment]
@ichorny did you run `GroupReadsByUmi` to set the molecular identifier (i.e. the `MI` tag)?  You'll need to do that before running `CallMolecularConsensusReads`.

**Comment by ichorny** [comment]
I did not but can you provide the reasoning since I already have the UMI in the RX tag. Why the extra step? 

Thanks for you help!

**Comment by nh13** [comment]
The first tool uses the RX tag to identify reads from the same source molecule (setting the MI tag). The second tool takes groups of reads from the same source molecule (using the MI tag) and calls consensus reads. The need for the first is the bases in RX may have errors due to sequencing or library prep (ex PCR).

**Comment by ichorny** [comment]
I'm cleary still doing something wrong. I got the code to run but my output BAM has not coordinates:

read-group:UMI	77	*	0	0	*	*	0	0

This is what I ran.

java -jar $jarFile SortBam -s $sortType -i $bamName -o $prefix.sorted.bam 
java -jar $jarFile SetMateInformation -i $prefix.sorted.bam  -o $prefix.MQfixed.bam 
java -jar $jarFile GroupReadsByUmi -i $prefix.MQfixed.bam  -o $prefix.umigrouped.bam -m $minMQ -s $strategy
java -jar $jarFile CallMolecularConsensusReads -i  $prefix.umigrouped.bam -o $prefix.collapsed.bam -M $minreads -t $tag -m $minBQ

**Comment by ichorny** [comment]
Found my issue in a closed thread
https://github.com/fulcrumgenomics/fgbio/issues/530

**Comment by nh13** [comment]
@ichorny closing this issue, feel free to re-open if you disagree
