### ISSUE TITLE
Raw and unique observations for duplex-umi-counts

### ISSUE THREAD

**Issue by fmarinn** [fulcrumgenomics/fgbio#577]
I have been using fgbio tools to process sequencing data with duplex UMIs. I have run CollectDuplexSeqMetrics  with option duplex-umi-counts=true on BAM output by GroupReadsByUmi tool to generate the metrics describing the set of observed duplex UMIs. 

I have read the description of the metrics and I understand that raw_observations is the number of read pairs with the observed duplex UMI, and unique_observations is the number of families (ds source molecules) that contains the observed duplex UMI. 

In my set of samples, the ratios raw_observations / unique observations for observed UMIs are always very similar in each sample, e.g all UMIs ratios 3.2-3.4 in one sample or 7.5-9.5 in another. I would expect a more different distribution of UMIs raw observations / unique observations in a sample but I am not sure if I am interpreting the metrics correctly. It would be possible to clarify the meaning of these metrics?

There are also UMIs with Ns in the sequence (e.g TAT-GNA), although they account for a very small percentage of the total raw observations. In these cases, raw_observations equal raw_observations_with_error and that is what I would expect if  Ns are errors. Ratios of UMIs raw_observations / unique observations are always 2 (or very close to 2) in all these cases and all samples. CallDuplexConsensusReads is using these reads with UMIs including Ns to generate the consensus, is there an option for filtering out these reads?

Thanks in advance for your help.

**Comment by nh13** [comment]
@fmarinn my apologies for the delay, but it looks like you're sequencing each family more deeply in one sample (7.5-9.5 raw reads per family) than the other sample (3.2-3.4).  Can you post the output metrics of `GroupReadsByUmi` and `CollectDuplexSeqMetrics`?
