### ISSUE TITLE
WES analysis and consensus of group of two reads

### ISSUE THREAD

**Issue by denise0593** [fulcrumgenomics/fgbio#578]
Dear Author, 

I'm using fgBio for exome analysis, I've used CallMolecularConsensus with min-reads=1. 
I'm wondering if you have suggestion for the FilteringConsensusReads?
Another question, how do you deal in the creation of consensus if you have only 2 duplicates and in the same position they disagree?

Thank you in advance,
Best Regards
Denise

**Comment by tfenne** [comment]
@denise0593 Recommendations for filtering are hard - it depends on a lot on the technology, the dataset and how you're planning to use it downstream.  Presuming that your library is sufficiently deeply sequenced that you have multiple reads for most molecules, we generally recommend a min-reads of 3 or perhaps 2 in lower coverage datasets .. though for the most stringent uses there is value in pushing that up to 4 or 5.

Generally we'd recommend trying min-reads=[2..5] and also experimenting with the error rate parameters, generating plots and evaluating.

The math for when there are only two observations and they disagree is pretty simple.  The full math is [here](https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Consensus-Reads).  But it more or less boils down to the following:
* If the two bases have equal quality call `N` at Q=2 (or maybe Q=0?)
* If the two bases have differing quality, call the higher quality base with Q = `max(Q1, Q2) - min(Q1, Q2)`.
