### ISSUE TITLE
SV calling on Consensus BAMs

### ISSUE THREAD

**Issue by kanika-arora** [fulcrumgenomics/fgbio#594]
I am testing fgbio for collapsing duplex reads. I run GroupReadsByUmi with paired strategy, followed by CallDuplexConsensusReads and FilterConsensusReads to get duplex BAM files. We are interested in calling SVs from duplex BAMs. I wanted to know if that is feasible. 

Could you please elaborate on how fgbio deals with split reads and discordant read-pairs? I saw an older [issue](https://github.com/fulcrumgenomics/fgbio/issues/434), where it says that fgbio filters out reads that map cross-chromosomally. Is that still the case?
How does it deal with read-pairs with one read unmapped, and soft-clipped bases of reads?

Thank you!
Kanika

**Comment by tfenne** [comment]
Hi @kanika-arora - as it stands `GroupReadsByUmi` does still filter out both a) cross-chromosomal reads pairs and b) read-pairs where one or both ends are unmapped.  We made these decisions a long time ago when first working on this and chose to be conservative.   I see no reason that one or both restrictions couldn't be relaxed but it would take some work.

Soft-clipped bases generally don't affect the grouping (or consensus) step.

**Comment by kanika-arora** [comment]
Thank you for the clarification @tfenne. I think it will be great to be able to call SVs from the consensus BAMs. If there is a future version that will enable that, we'd be very interested in it.
Thank you for help!

**Comment by 10-m** [comment]
I have deleted the following code to detect SV. That would work well for me.
How does @tfenne think about? Is there any problem what you think?

GroupReadsByUmi.scala:
require(rec.refIndex == rec.mateRefIndex, ....) x 2 places
.filter(r => (r.unpaired || r.refIndex == r.mateRefIndex)

Thanks.

**Comment by nh13** [comment]
@10-m I think that should work fine, but it is unsupported, so a PR is welcome.

**Comment by tyyiyi** [comment]
So at present I cannot use GroupReadsByUmi if I want to detect structural variation. So I can just ExtractUmisFromBAM, and do BWA comparisons and mergers, right? It is sincerely expected that structural variations can be detected from consensus BAMs!


Thank you very much!
Tang
