### ISSUE TITLE
When to use --reverse-per-base-tags for FilterConsensusReads

### ISSUE THREAD

**Issue by jurhoades** [fulcrumgenomics/fgbio#596]
We're currently using fgbio to process paired end Illumina data with duplex UMI adapters. Our current workflow goes `GroupReadsByUmi` > `CallDuplexConsensusReads` > Realign (Picard `SamToFastq`, `bwa mem`, Picard `MergeBamAlignment`) > `FilterConsensusReads`. We noticed in our BAMs going into `FilterConsensusReads` that the per-base tags for reads mapped to the reverse strand were reverse complimented. If this is the case, should we be using `--reverse-per-base-tags true` for masking/filtering of individual bases to work properly? The default appears to be `false`. Thanks!

**Comment by nh13** [comment]
Great question!

See the tool documentation: http://fulcrumgenomics.github.io/fgbio/tools/latest/FilterConsensusReads.html.  In particular:

> The --reverse-tags-per-base option controls whether per-base tags should be reversed before being used on reads marked as being mapped to the negative strand. This is necessary if the reads have been mapped and the bases/quals reversed but the consensus tags have not. If true, the tags written to the output BAM will be reversed where necessary in order to line up with the bases and quals.

Feel free to re-open if this doesn't solve your issue.

**Comment by jurhoades** [comment]
Thanks for the quick response! From the documentation it looks like we do need to set that flag for our workflow.
