### ISSUE TITLE
Add an option to ErrorRateByReadPosition not to collapse substitution types

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#599]
Currently, `ErrorRateByReadPosition` collapses substitution types based on the reference base.

>Substitution types are collapsed based on the reference or expected base, with only six substitution types being reported: A>C, A>G, A>T, C>A, C>G and C>T. For example, T>G is grouped in with A>C.

The example is illustrative.  If we care about variant calling a SNV at a `A` (or `T`) reference positions, then we really don't care if the read (in sequencing order) had a `A>C` or `T>G`, since we can observe that reference base on either strand.

But if we care about the fidelity of sequencing, in sequencing order, we do not want to collapse `A>C` and `T>G`.   It may be the sequencer has much harder time reading through the top strand of the genome versus the bottom strand at the same SNV site above.

I think it should be as simple as adding some logic around these two lines:
https://github.com/fulcrumgenomics/fgbio/blob/c4b778baf0c780fa60a894c578804cec5398b829/src/main/scala/com/fulcrumgenomics/bam/ErrorRateByReadPosition.scala#L145-L146

@tfenne any objections?

**Comment by tfenne** [comment]
No real objections.  I'd like the default to remain as it is though please.

I think the bulk of the work is really going to be in writing tests.  I think we essentially need to cover all combinations of:
* Reads mapped to the positive and negative strands
* Reads with A>N, C>N, G>N, T>N
And just make sure they all come out as expected.
