### ISSUE TITLE
remove duplicate after CliPBAM

### ISSUE THREAD

**Issue by tyyiyi** [fulcrumgenomics/fgbio#603]
I intend to detect structural variation in UMI data, So want to use fgbio to process the raw data, I conducted  FastqToSam ExtractUmisFromBAM, SamToFastq, bwa mem, MergeBamAlignment, GroupReadsByUmi, CallMolecularConsensusReads, SamToFastq, bwa Mem, MergeBamAlignment FilterConsensusReads, ClipBam. This process is ok? After I conducted a ClipBam (- clipping - mode = Soft - clip - overlapping - reads = true), do I still need to use PICARD to remove duplicate? Or can I detect structural variation directly?

Thank you!
tang

**Comment by nh13** [comment]
`GroupReadsByUmi` will not not group the reads you're interested in.  See the discussion: https://github.com/fulcrumgenomics/fgbio/issues/594

I would not remove duplicate consensus reads, unless you're absolutely sure they're duplicates.
