### ISSUE TITLE
ErrorRateByReadPosition

### ISSUE THREAD

**Issue by chelauk** [fulcrumgenomics/fgbio#606]
I am building a UMI-variant calling pipeline which uses fgbio and I noticed that the tool [ErrorRateByReadPosition](http://nilshomer.com/2017/08/04/sequencing-error-reduction-through-consensus-calling-reads-from-the-same-source-molecule/) is recommended.  It isn't obvious to me at what stage of the pipeline I should use it? Would it be before calling and filtering consensus or after.  Any insight gratefully received.

**Comment by tfenne** [comment]
We tend to run it at several stages to help illustrate how the consensus building process improves things.  What I would suggest is running it on a) a BAM file of raw (deduped) reads, b) the re-aligned consensus BAM and also c) the filtered consensus BAM.  The expectation is that error rates should be improving significantly at each step, and it is nice to confirm.

**Comment by chelauk** [comment]
That is really useful, thank you very much!
