### ISSUE TITLE
MolecularConsensus with a pileup of N

### ISSUE THREAD

**Issue by ruolin** [fulcrumgenomics/fgbio#628]
Hello, the current consensus algorithm is basically ignoring N bases which cause some problems for our data.  See the circle column in the picture, where there are hundreds of Ns, but just one T. The consensus bases should be obvious be N. However, the consensus base is T. I understand that you want the most confidence bases into the consensus. But Could you add an option allowing N to be counted as well?
![Screen Shot 2020-09-22 at 1 06 23 PM](https://user-images.githubusercontent.com/4268335/93914399-80a84880-fcd4-11ea-8bcf-326934fb56db.png)

**Comment by nh13** [comment]
Do you run FilterConsensusReads after calling the consensus reads? You could see if an option there works (eg. min-bases or max error rate).  If none of these work, I’d be open Investigating further.

**Comment by ruolin** [comment]
Yes, I did run FilterCOnsensusReads. But it does not work for us. The filters you mentioned affect other reads as well. For example, we have a bunch of family size 1 reads.

**Comment by nh13** [comment]
Why do you want to count depths of reads that don't contribute to the consensus?  If this is still an issue, feel free to re-open the issue.
