### ISSUE TITLE
 More than one value for the flag option

### ISSUE THREAD

**Issue by mpiyush21** [fulcrumgenomics/fgbio#629]
Hi,

I have a targeted sequencing data with UMI. Both paired-end Fastq and Indexes are in separate files, resulting in 4 different files. 

Just to test the tool, I am running a single fastq files from a lane without index files to generate an unmapped BAM file. Here is the command. 

java -jar /home/piymun/Software/fgbio/target/scala-2.13/fgbio-1.4.0-57988d6-SNAPSHOT.jar FastqToBam --input S1-B2-0-0025_S5_Total_AdapClippd_R1_Trimmd_sorted.fastq.gz  -o S1-B2-0-0025_S5_L003.bam -sample S1-B2-0-0025_S5 -library xGen

This is throwing following error, that I am unable to understand. Can you please advice?  

**Trying to add more than one value for the flag option: 's'**

Thank you in advance,

Cheers,
Piyush

**Comment by tfenne** [comment]
Long options need to be specified with double dashes, e.g. `--sample`.  When you specify `-sample` it's interpreting that as `-s ample S1-B2-0-0025_S5`.
