### ISSUE TITLE
Duplex sequencing: --min-reads 1 2 2

### ISSUE THREAD

**Issue by gabeng** [fulcrumgenomics/fgbio#632]
The documentation suggests that an option of `--min-reads 1 2 2` could be provided to `FilterConsensusReads`. 
```
In each case if fewer than three values are supplied, the last value is repeated (i.e. 80 40 -> 80 40 40 and 0.1 -> 0.1 0.1 0.1. 
The first value applies to the final consensus read, the second value to one single-strand consensus, and the last value to the other single-strand consensus. 
It is required that if values two and three differ, the more stringent value comes earlier.
```

This would mimic treating the duplex barcodes as regular barcodes, would it not?
However, I get an error message that the most stringent value must come earlier.

**Comment by nh13** [comment]
@gabeng from my reading, the first value applies to the final consensus (both strands), so if you say you only want at least one raw read for the final consensus but at least two for each of the two single-strand consensuses, then the latter implies at least four for the final consensus.  Can you try `--min-reads 4 2 2`?

**Comment by gabeng** [comment]
Hi @nh13, 

I think I am misunderstanding the process and the meaning of the parameters. Maybe you could clarify that for me:
I think, I understand `--min-reads 1 1 1` now: Two consensus reads (one for top and bottom each) are generated while even considering reads that are present with only one copy. Then, from these two reads, a duplex consensus reads is generated. If either top or bottom consensus read is missing, all the data from this molecule is omitted, correct?
What does `--min-reads 2 1 1` mean, then? I will always have only one consensus read for top and bottom strand. Which reads will the "2" be applied to? To the sum of reads that went into calculating the strand specific consensus reads?
Then `--min-reads 2 1 1` would lead to no other result than `--min-reads 1 1 1` - is that correct?

--
Ben

**Comment by nh13** [comment]
the first value applies to the total coverage of the consensus molecule, the second value to one single-strand consensus,
and the last value to the other single-strand consensus.  So `--min-reads 2 1 1` is the same as `--min-reads 1 1 1` since to have 1x on each consensus strand implies a total coverage of 2x, which is always greater than 1x.
