### ISSUE TITLE
GroupReadsByUmi mapping issues

### ISSUE THREAD

**Issue by laurabaxter21** [fulcrumgenomics/fgbio#633]
Hi,

During the GroupReadsByUmi step of my pipeline, the majority of my reads are being filtered due to "mapping issues".

Is there a common reason/explanation for this happening?  

The paired end reads were aligned using BWA, followed by running AnnotateBamWithUmis, SortBam, and SetMateInformation prior to the GroupReadsByUmi step.

The relevant log information is here:
[2020/10/07 11:10:15 | GroupReadsByUmi | Info] Filtering and sorting input.
[2020/10/07 11:10:18 | GroupReadsByUmi | Info] Seen many non-increasing record positions. Printing Read-names as well.
[2020/10/07 11:10:33 | GroupReadsByUmi | Info] Accepted 24,476 reads for grouping.
[2020/10/07 11:10:33 | GroupReadsByUmi | Info] Filtered out 8,761,304 reads due to mapping issues.
[2020/10/07 11:10:33 | GroupReadsByUmi | Info] Filtered out 0 reads that contained one or more Ns in their UMIs.
[2020/10/07 11:10:33 | GroupReadsByUmi | Info] Assigning reads to UMIs and outputting.

Thanks,

Laura

**Comment by ruolin** [comment]
We are also playing around with GroupBreadsByUmi. In the notes it says 

> Reads are aggressively filtered out so that only high quality reads/mappings are taken forward. Paired-end reads must have both reads mapped to the same chromosome with both reads having mapping quality >= min-mapq. (Note: the MQ tag is required on reads with mapped mates). 

However, we are particularly interested in the discordant pairs as we are looking for SVs. Is it possible to add a switch to loosen this restriction?

**Comment by nh13** [comment]
@laurabaxter21 could you detail your experiment?  Do you expect chimeric reads (eg. SVs)?  If you could share a snippet of your input, we can take a look when we get the chance.

@ruolin can you open up a separate issue and we can take a look at your request there?  I don't see why we couldn't add the option to allow chimeric reads, but I think it's all an issue of bandwidth on our end.

**Comment by laurabaxter21** [comment]
Thanks for the reply - I managed to track down the source of the error, which turned out to be malformed bwa index files for the reference genome.
(Oddly the bwa mapping, AnnotateBamWithUmis, SortBam, and SetMateInformation steps all appeared to complete without error despite the problem with the reference, and looked fine in IGV) - it was just the GroupReadsByUMI which caught the error. I re-ran bwa index on the reference genome, re-ran everything, and the GroupReadsByUMI now accepts the majority of reads for grouping, and filters out very few.
Best wishes,
Laura
