### ISSUE TITLE
Accepting discordant pairs in GroupReadsByUmi

### ISSUE THREAD

**Issue by ruolin** [fulcrumgenomics/fgbio#634]
Hello, 
This is a new feature request. 
In the note of `GroupBreadsByUmi`, it says

> Reads are aggressively filtered out so that only high quality reads/mappings are taken forward. Paired-end reads must have both reads mapped to the same chromosome with both reads having mapping quality >= min-mapq. (Note: the MQ tag is required on reads with mapped mates).

However, we are particularly interested in the discordant pairs as we are looking for SVs. Is it possible to add a switch to loosen this restriction? 

I hope this new feature also propagate to `CallMolecularConsensusReads` and `CallDuplexConsensusReads`

**Comment by nh13** [comment]
@ruolin this is a feature we haven't relaxed, but could at some point make if we have a motivating project.
