### ISSUE TITLE
`DemuxFastq` using non-unique barcodes

### ISSUE THREAD

**Issue by BenSolomon** [fulcrumgenomics/fgbio#635]
Hi!

I am trying to use `DemuxFastq` to deumultiplex single cell fastq files that contain data from multiple cells and multiple samples. I would like to create output fastq files that split apart the samples, while keeping cells together as long as they are from the same sample. However, the barcodes that I have to use are cell-specific (there are no sample specific barcodes based on how the library was made). 

Ideally, my metadatafile would look like this and I would get a single fastq for each of the unique samples:

Sample_ID<chr> | Sample_Name<chr> | Library_ID<chr> | Sample_Barcode<chr> |  
-- | -- | -- | -- | --
INCOV013 | INCOV013 | INCOV013 | AAACCTGAGAACAATC |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGAGACTAGAT |  
INCOV015 | INCOV015 | INCOV015 | AAACCTGAGCCATCGC |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGAGCTAAGAT |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGAGTGGAGAA |  
INCOV015 | INCOV015 | INCOV015 | AAACCTGCAATGGATA |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGCAGATGAGC |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGCAGGGTTAG |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGGTAGAAGGA |  
INCOV013 | INCOV013 | INCOV013 | AAACCTGTCCCGACTT

However, as expected, this will result in an error: `Error: requirement failed: Sample identifiers were not unique: INCOV013, INCOV015`

----

If I name cells arbitrarily to `Sample_ID` and `Sample_Name` and instead assign the sample info to `Library_ID` , I can generate a metadata table that will work with `DemuxFastq`:

Sample_ID<int> | Sample_Name<int> | Library_ID<chr> | Sample_Barcode<chr> |  
-- | -- | -- | -- | --
1 | 1 | INCOV013 | AAACCTGAGAACAATC |  
2 | 2 | INCOV013 | AAACCTGAGACTAGAT |  
3 | 3 | INCOV015 | AAACCTGAGCCATCGC |  
4 | 4 | INCOV013 | AAACCTGAGCTAAGAT |  
5 | 5 | INCOV013 | AAACCTGAGTGGAGAA |  
6 | 6 | INCOV015 | AAACCTGCAATGGATA |  
7 | 7 | INCOV013 | AAACCTGCAGATGAGC |  
8 | 8 | INCOV013 | AAACCTGCAGGGTTAG |  
9 | 9 | INCOV013 | AAACCTGGTAGAAGGA |  
10 | 10 | INCOV013 | AAACCTGTCCCGACTT

However, this will create hundreds of individual fastq files, one for each cell, which don't include `Library_ID` in the name (i.e. the actual sample info), which means I need to go through another step of matching and concatenating these fastq files myself.

Is there anyway around this using `DemuxFastq` directly?

For reference, my command line call is
```
fgbio DemuxFastqs --inputs $I1 $R1 $R2 \
    --read-structures 8S 16B10M 100T \
    --metadata $EXPORT_PATH/SampleSheet.csv \
    --metrics metrics.txt \
    --output $EXPORT_PATH/
```

Thanks!

**Comment by nh13** [comment]
@BenSolomon I see what you're trying to do.  I think it's a non-trivial amount of effort to support what you're doing, but possible.  Is this something you still need?

Another way to do this would be to use `ExtractUmisFromBam --single-tag --read-structure 8S 16M10M 100T -- molecular-index-tags BC RX` to pull out the 16bp barcode and 10bp UMI into the `BC` and `RX` tags respectively into one BAM.  You can then annotate write a little script to lookup `BC` based on your table above and a new tag (ex. `SM`), then split the BAM by the `SM` tag, one per sample.

**Comment by BenSolomon** [comment]
Hey @nh13, thanks for the reply and looking in to this! I think I found the solution I needed. `UMI tools` has some parameters that were able to accomplish this with minimal tweaking, so that should work for me. Thanks for your suggestion too, I think that would have worked as well!
