### ISSUE TITLE
error rate

### ISSUE THREAD

**Issue by aspitaleri** [fulcrumgenomics/fgbio#642]
Hi
I have run 
`java -Xmx4g -XX:+AggressiveOpts -XX:+AggressiveHeap -jar /usr/local/fgbio/target/scala-2.13/fgbio-1.4.0-37fbb49-SNAPSHOT.jar ErrorRateByReadPosition -i Phix.sort.bam -r phix74.fasta
`
and it run only if the .dict is present as reported in #494 
nowhere it is reported this.

As far I understood the output error_rate_by_read_position.txt reports the error per read position, both forward (1) and reverse (2). I have some questions:
1. averaging the error_rate (column 5) should be considered the average error rate for the run? 
2. this is request probably. I'd like to have the error rate per genome position, i.e. Phix genome length. Is this possible in somehow?  I'd like to use the information of error rate in order to detect low frequency variant, and I am wondering how to associate the information from the read position to the whole genome.

Thanks for any help
Best

**Comment by nh13** [comment]
(1) I don't think that will work, as there may be more bases observed in read 1 vs read 2 (or vice versa).  This can happen if adapter or quality trimming has been applied for example.  So if you want a total error rate, I think you'll want to compute the weighted average:

```
(errors_1 + errors_2) / (bases_total_1 + bases_total_2)
```

(2) I'd use `samtools mpileup` to generate the bases piled up at a genomic position and post-process.  It has a few output options to example (like `-O` to output read positions).  We typically use `VarDictJava` for low-frequency variant detection (with UMIs) in pileup mode, so you can try that too.
