### ISSUE TITLE
FilterConsensusReads filter UMI sequence by hamming distance and maybe N content

### ISSUE THREAD

**Issue by mmterpstra** [fulcrumgenomics/fgbio#647]
First thank you for writing the software,

FilterConsensusReads filter UMI sequence by hamming distance.
I have an issue which could be solved up front or downstream but the UMI sequences are also subject to PCR bias and the likes. To reduce error even more it might be interesting to filter UMI's by hamming distance like the MAX_EDIT_DISTANCE_TO_JOIN from the picard tool UmiAwareMarkDuplicatesWithMateCigar. when a umi consensus has > 20 copies this really adds something the error rate and overall robustness. (you could also implement this on the CallMolecularConsensusReads but this might be a scalability rabbit hole). 

FilterConsensusReads filter UMI sequence by N content.
This is a more generic way of filtering and might even overlap with the first option. Up front filtering of reads is another solution for this problem though.

Good luck!

**Comment by nh13** [comment]
This is solved in the GroupReadsByUmi tool where UMIs are collapsed, accounting for sequencing and PCR errors and the like.
