### ISSUE TITLE
Duplex consensus and strand labeling

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#651]
Hi,
I'm interested in using the CallDuplexConsensusReads tool. However, it is unclear to me how GroupReadsByUmi preserves read 1 vs read 2 information.

GroupReadsByUmi expects the RX tag to contain the UMI pairs separated by a hyphen. For example:
 - Strand 1: AAAA-GGGG
 - Strand 2: GGGG-AAAA

These are then converted by GroupReadsByUmi to 1/A and 1/B (note there is an error in your documentation that says it is converted to 1/AB and 1/BA here: http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html, even though this page says it is converted to 1/A and 1/B: https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling)

But where is the read 1 vs read 2 information stored? And where does CallDuplexConsensusReads obtain the read 1 vs read 2 information? Is that obtained from the standard SAM flag 0x40? This isn't specified in fgbio's documentation.

Thank you.

**Comment by nh13** [comment]
That’s right, the standard SAM flag fields are used (as they should) to determine and store read 1 vs. 2.
