### ISSUE TITLE
Duplex consensus documentation questions

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#652]
Hi,
There are a few things that are unclear in this duplex consensus documentation: https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads

1. "Reads are filtered based on their Cigar (alignment structure) to ensure reads are always in phase (in two groups: A1s and B2s, and A2s and B2s)."
  - Groups mention A1s, B2s, and A2s and B2s, but not B1s?
  - It is not clear why CIGAR alignment phasing is checked between strands instead of between the two reads of the same strand?

2. "Two duplex consensus reads are generated by combining the A1 and B2 consensus reads, and the A2 and B1 consensus reads"
 - This states that duplex consensus is created from A1 and B2, and then A2 and B1. Is this the case? I would have thought that duplex consensus sequences should be made from read 1 and read 2 of strand A, and then read 1 and read 2 of strand B, which would be A1 and A2, and then B1 and B2. Am I misunderstanding something?

3. I'm unclear how the process goes from 4 single-strand consensus sequences to 1 final duplex consensus:
  "7. Four single-strand consensus reads are generated, one each for A1s, A2s, B1s, and B2s
   8. Two duplex consensus reads are generated by combining the A1 and B2 consensus reads, and the A2 and B1 consensus reads"
  - I understand the first step would be to generate a consensus for A1, A2, B1, and B2.
  - However, the next step would be to generate a consensus for each strand; i.e. A1 + A2, and B1 + B2.
  - Only then would a duplex consensus be determined by comparing the consensus for A vs the consensus for B.
  - But the documentation seems to suggest that it goes straight from 4 single-strand consensus sequences to the final duplex consensus. How would that be possible without first generating a consensus for each strand?
  - Alternatively, why not make two single-strand consensus sequences directly from all the reads of A1+A2, and B1+B2? What is the benefit of making 4 single-strand consensus sequences?

Thanks.

**Comment by nh13** [comment]
Thank you reading the documentation!

1-1: fixed typo

1-2: A1 and B2 overlap the same genomic coordinates so should have the same CIGAR. Same for A2 and B2. Probably the typo you found above confused things, but also see the diagram in: https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling#top-and-bottom-strand-for-raw-reads

The general idea is to group reads by strand, create a single strand consensus for each, then a final duplex consensus. See the figures from: https://pubmed.ncbi.nlm.nih.gov/25299156/

Hopefully the remaining questions follow from the clarifications above.

**Comment by gevro** [comment]
Thanks. Regarding 1 - great.

Regarding questions 2 and 3: I think I understand now, but it raises a different question: Imagine that the insert size is always smaller than the read length. In terms of the terminology shown in this page https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling#top-and-bottom-strand-for-raw-reads, that means that after adaptor trimming:
- R1 and R2 of read x will both reflect data from strand A
- R1 and R2 of read y will both reflect data from strand B

In this situation, the correct process would be:
- Make a single strand consensus from all the A1 reads that share a UMI plus all the A2 reads that share a UMI, all together.
- Same as above but for B1 and B2 reads.
- Then make a duplex consensus from the A1+A2 consensus and the B1+B2 consensus.

Note how this process comes out differently from the process you describe of making four single strand consensus and then duplex consensus of A1+B2 and A1+B1.

How do you suggest to handle a situation where most of the insert sizes are smaller than the read length; i.e. the above situation? Am I correct that standard CallDuplexConsensusReads may not work? Is there a way to tweak it, or should I come up with a custom solution that artificially creates UMI pairs that forces it to work, or should I figure out how to do this with just CallMolecularConsensusReads?

**Comment by nh13** [comment]
It will work, just that the resulting consensus reads will also have overlapping regions of R1 and R2. I’d then use ClipBam to trim the overlapping region using the --clip-overlapping-reads option: http://fulcrumgenomics.github.io/fgbio/tools/latest/ClipBam.html

If you think you’ll be always generating read pairs with significant overlap, I’d have to think about it a lot more, since I’d want to perhaps join R1 and R2 prior to consensus calling. There are lots of tools for this but you could also do that after single strand consensus calling.  And once you have a single contiguous read (R1+R2 joined) per strand you can again consensus call to generate the final duplex read. So you’d group reads, call single strand consensus per strand, then join R1 and R2, and do one final consensus. This would all be custom and you’d lose some info along the way.

**Comment by nh13** [comment]
@gevro I’d also mention we’d be happy to automate this in a tool or pipeline (or both) but also like to get fairly and equitably compensated for our work, so if you’re in a position to do so, contact us: https://www.fulcrumgenomics.com/contact/

**Comment by gevro** [comment]
Thanks so much. I will give it a shot myself first, and if we struggle, I may have questions or consider a custom order via Fulcrum.
