### ISSUE TITLE
VCF from CIGAR of final consensus

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#654]
Hi,
Since the accuracy of duplex sequencing is extremely high, and it can be performed with shallow sequencing that does not allow standard variant calling that utilizes multiplex UMI coverage of a given locus, is there a tool to create a VCF directly from the final duplex consensus BAM file using just the CIGAR? This would then allow easy comparison to VCF files of germline variants obtained by standard non-duplex sequencing.

Maybe bcftools mpileup? Or do you have another recommendation?

Thanks.

**Comment by nh13** [comment]
For somatic calling you want high final depth, so disagree with your assumption in low depth. Even so, don’t trust the CIGARs, especially for large indels or complex variants, some which need assembly! Try VarDictJava in pileup mode. We have it implemented in dagr but it’s not hard to implement it in WDL/Nextflow/Snakemake too. https://github.com/fulcrumgenomics/dagr/blob/7c31adfd4a979e66efd70209c8836e146d618acc/tasks/src/main/scala/dagr/tasks/vc/VarDictJava.scala
