### ISSUE TITLE
Calling duplex molecules using assembled paired end reads

### ISSUE THREAD

**Issue by tahuh** [fulcrumgenomics/fgbio#659]
Hi team.

My paired end fastq data consist of UMIs in both reads (R1 and R2) and I have assembled paired reads using several softwares
([pear](https://cme.h-its.org/exelixis/web/software/pear/) , [FLASH](https://ccb.jhu.edu/software/FLASH/) ).

When I try CallDuplexConsensusReads, the fgbio complains that GroupReadsByUMIs using `paired` strategy.

But the paired strategy does not work when I tried GroupReadsByUMIs.

Is there ways that I can make duplex sequences using assembled paired end reads?

**Comment by nh13** [comment]
@tahuh `GroupReadsByUmi` currently expects the reads to paired end and not merged.  So merging the paired end reads (presumably they overlap) wont work.  The other option that wouldn't require any modification is to merge the paired end reads after consensus calling.  

That being said, I don't think it would be too hard support it.  I assume you've already extracted the UMIs and they are stored in the RX tag like `AGTC-GTCA`, where `AGTC` is from R1 and `GTCA` is from R2?  If so, I think this PR should work: https://github.com/fulcrumgenomics/fgbio/pull/660.  Can you give it a try?  Or can you send me some data that I test it out on?

**Comment by tahuh** [comment]
@nh13 

Thanks for fast reply.

I will try that and let you know what happened.

**Comment by nh13** [comment]
@tahuh can you let us know if this worked?

**Comment by tahuh** [comment]
@nh13 Sorry for late reply.

I tried to use the method you have suggested for my research project but unfortunately me and colleagues decided not to use the read pair assembly option.

I really appreciate your kind help and feel sorry for not using the option.

I think you can close this issue.

**Comment by nh13** [comment]
No worries. Thank you for reporting back!
