### ISSUE TITLE
max-read-error-rate explanation

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#664]
Hi,
Regarding max-read-error-rate documentation in FilterConsensusReads, the documentation says:
"Reads with an average consensus error rate higher than max-read-error-rate are filtered out"

What tag does this correspond to? cE? 
cE is defined as: "the fraction of bases in raw reads disagreeing with the final consensus calls"

But I'm not clear what "average consensus error rate" means exactly relative to cE, if it is related to cE at all.

**Comment by nh13** [comment]
It's `cE`.  I'd ask you take a look at the source and trace back to verify:

* https://github.com/fulcrumgenomics/fgbio/blob/29132fbf1c1ea43c9923547b74d1d1a902536b14/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala#L106
* https://github.com/fulcrumgenomics/fgbio/blob/29132fbf1c1ea43c9923547b74d1d1a902536b14/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala#L138
* https://github.com/fulcrumgenomics/fgbio/blob/29132fbf1c1ea43c9923547b74d1d1a902536b14/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala#L250
* https://github.com/fulcrumgenomics/fgbio/blob/29132fbf1c1ea43c9923547b74d1d1a902536b14/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala#L245
* https://github.com/fulcrumgenomics/fgbio/blob/57988d615fa6188e0028faedfdf65ed13cf645e7/src/main/scala/com/fulcrumgenomics/umi/ConsensusTags.scala#L95
