### ISSUE TITLE
Linking input - UMI non-collapsed reads - to UMI collapsed consensus reads

### ISSUE THREAD

**Issue by madsheilskov** [fulcrumgenomics/fgbio#671]
Is there a way using fgbio commands to see which original reads that goes into individual UMI collapsed reads, effectively linking reads from GroupReadsByUmi to CallMolecularConsensusReads. This would be helpful in adjusting GroupReadsByUmi settings (as well as other settings). 
In its most simple form this would be a table with input read name and output (collapsed) read names, or a table with input UMI (e.g. BX tag), genomic position and collapsed UMI (e.g. MI tag).

**Comment by nh13** [comment]
@madsheilskov good question, there is no command or tool for this in fgbio, but all the information should be there, as the raw reads are annotated with `MI` by `GroupReadsByUmi` and the collapsed/consensus reads will have the same `MI` too.

**Comment by tfenne** [comment]
I think actually it's even easier than that.  I believe we name the consensus reads by the `MI` tag, and the output of GroupReadsByUmi is sorted by the `MI` tag, so it really is just looking at that BAM and taking consecutive read names that share the MI tag.

**Comment by madsheilskov** [comment]
Thanks - @tfenne  you are right - the GroupReadsByUmi output has the input and output UMI (as well as read name and position of cause).
