### ISSUE TITLE
ExtractUmisFromBam: difficulty with specifying two read structures for paired-end reads

### ISSUE THREAD

**Issue by ISmolicz** [fulcrumgenomics/fgbio#673]
Dear fgbio Team,

I am aiming to extract UMIs from an unmapped BAM using ExtractUmisFromBam, which contains paired-end sequencing data. For the overall sequencing run, I confirm the read structure is 148T8B10M148T, which I have used with e.g. IlluminaBasecallsToSam (Picard).

However, although I have read the relevant fgbio read structure [documentation](https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures), I cannot seem to clearly apply the examples to my situation to create the two read structures required to run ExtractUmisFromBam.

Please could you advise?

Thank you for your help.

**Comment by nh13** [comment]
For `IlluminaBasecallsToSam` I believe you specify the read structure for both reads in one string, whereas for `ExtractUmisFromBam` you need to provide a read structure, one for each read.  So something like `148T` and `8B10M148T` depending on your inputs.  You can then use the [online tool](https://fulcrumgenomics.github.io/fgbio/validate-read-structure.html) to validate your structures

**Comment by ISmolicz** [comment]
Thank you for your advice @nh13. With only one unmapped BAM file as input, I was uncertain as to how the single read structure should be separated into a set of read structures to ensure both forward and reverse reads are assigned a tag containing the UMIs.

**Comment by nh13** [comment]
@ISmolicz if you
