### ISSUE TITLE
reopen: fgbio and umi-tools, and called variant with vardict, umi-tools get 8 times variants than fgbio

### ISSUE THREAD

**Issue by worker000000** [fulcrumgenomics/fgbio#688]
because the first question is closed, so I need to reopen it 

This isssue related to #683 
#  
Thanks a lot for your kind and helpful suggestion.@nh13 @fleharty
1 I am doing somatic calling of paired samples of PE sequencing, I have Umi in both reads,

2 I call variants after do consensus
3 there are so many variants here, I do not have truth dataset, but both tools may have done this before I guess.
4 strategy are you using in GroupReadsByUmi
java -Djava.io.tmpdir=TMP -Xmx100G -jar bin/fgbio-1.1.0.jar GroupReadsByUmi --input=K123.UMI.merged.bam --output=K123.UMI.group.bam --strategy=paired --min-map-q=30 --edits=1 --raw-tag=RX

5 umitools do like such
umi_tools extract --bc-pattern=CNNNC --bc-pattern2=CNNNC --log=processed.log -I T_out.R1_TMP.fq.gz -S C_out.R1_TMP_umitools.fq.gz --read2-in=T_out.R2_TMP.fq.gz --read2-out=C_out.R2_TMP_umitools.fq.gz
# then do bwa and samtools
umi_tools dedup -I ${dir1}_T.sorted.bam --output-stats=deduplicated -S ${dir1}_T_deduplicated.bam

**Comment by nh13** [comment]
Without (1) having access to the data, (2) understanding UMI tools, and (3) having some spare time to help debug this, I’m not sure I’ll be much help. Can you look at the different variants in IGV or your favorite genome browser along with the reads and see if you can spot a pattern. You’ll have to spend time digging into why some consensus reads and variants. are present in one versus another. I won’t be able to do this for you. I know you probably want a quick answer, but debugging these things are time intensive, so if you can show a few small examples (e.g. a single variant or single UMI family) where you believe one is doing something different than the other, perhaps then we can revisit. Sorry that this is not the answer you probably want to hear.

**Comment by nh13** [comment]
I’ll also say that if you do want us to spend the significant time it takes to look into this issue, you can contact us at www.fulcrumgenomics.com and tell us the budget you have for this issue and we can discuss.

**Comment by worker000000** [comment]
@nh13 
Thanks a lot for the help, it is really not that easy, I will contact the email in the website
