### ISSUE TITLE
fgbio-1.3.0.jar Demux Fastqs JAVA runtime error 

### ISSUE THREAD

**Issue by alleeBio** [fulcrumgenomics/fgbio#690]
Issue with DemuxFastqs while running java version "15.0.1"
![image](https://user-images.githubusercontent.com/88105654/127365684-4621e7a0-7a22-4bb3-859a-583f47de2ba9.png)

**Comment by nh13** [comment]
@alleeBio looks like an issue with the https://github.com/Intel-HLS/GKL library we use.  Let us know if you still have this issue.
