### ISSUE TITLE
CallMolecularConsensusReads on a bam with both PE and SE reads?

### ISSUE THREAD

**Issue by cnk113** [fulcrumgenomics/fgbio#694]
Hello,

I'm running into issues with CallMolecularConsensusReads b/c I have a mixed library sequenced separately with both SE and PE. When I do SetMateInformation I'll lose my SE library if I try to do `-x` I can't since CallMolecularConsensusReads will throw an error on missing mates on my SE reads. 

Would you recommend splitting the library to both SE and PE and run CallMolecularConsensusReads separately and then merge and rerun it again on the merge BAM?

Best,
Chang

**Comment by nh13** [comment]
Yes, for now splitting the SE and PE into two and processing them independently until variant calling makes sense.
