### ISSUE TITLE
GroupReadsByUmi issue

### ISSUE THREAD

**Issue by liuhepkk** [fulcrumgenomics/fgbio#695]
Dear engineer：

There are some fusion templates  which R1 R2 may be from different chr in pair end reads.
question1:
                Are these  templates can be passed after GroupReadsByUmi ?
I was confused of the docs:
 " Reads are aggressively filtered out so that only high quality read pairs with both ends mapped are taken forward."

question2:
               It is that mean only the templates which R1 R2 from the same chr can be passed ？ Will the fusion analysis results can be  influenced ?

Thanks.
Look forward to your favourable reply!

**Comment by nh13** [comment]
The support for grouping R1 and R2 across contig was added here: https://github.com/fulcrumgenomics/fgbio/pull/648

I don’t think we’ve done a release with it, so you’ll need to build off master.
