### ISSUE TITLE
CallDuplexConsensusReads didn't subtracts base quality by 20, instead subtracts by 19.

### ISSUE THREAD

**Issue by roh329** [fulcrumgenomics/fgbio#697]
I'm trying to rescue more nucleotides when making DCS from a very small family size.

In my case, the nt was masked by base quality. And I'm looking back to the consensus algorithm.

I found it looks like the base qualities were adjusted by subtracting by 19 phred score.

Could you check this issue? 

I'm using fgbio latest version 1.3.0.

**Comment by nh13** [comment]
Can you provide a small reduced SAM file for us to reproduce the issue along with what you expected?

**Comment by roh329** [comment]
I'm sorry, I was confused. It is working perfectly.
