### ISSUE TITLE
UMI collision

### ISSUE THREAD

**Issue by emissiaglia** [fulcrumgenomics/fgbio#701]
Hi,
Using a UMI with just 9nt generates a large number of UMI collisions in our library. In fact, in our libraries we observed up to 10-20 different groups of reads (based on genomic positions) sharing the same UMI. It seems that the complexity of our libraries is far higher than the number of unique UMI provided by the company.  Therefore, I would like to make sure to understand correctly how GroupReadsByUmi is handling reads derived from different template fragments but marked with the same UMI.
From this Amplicon collapsing #270, it seems that GroupReadsByUmi takes in to account both UMI and positions in order to create consensus groups. Therefore, if two reads share the same UMI, but map in two locations they are placed in two groups. Is that correct?
Do you think that GroupReadsByUmi is able to handle a situation like our, where multiple unique fragments are marked with the same UMI? 
Is there any modification in the setting you would suggest to minimize the loss of reads?
Many thanks in advance for your help,
edoardo

**Comment by nh13** [comment]
> From this Amplicon collapsing #270, it seems that GroupReadsByUmi takes in to account both UMI and positions in order to create consensus groups. Therefore, if two reads share the same UMI, but map in two locations they are placed in two groups. Is that correct?

That's correct, for paired end reads it looks at the start and stop/end positions of the template (outer coordinates) along with the UMI.  So if any of the UMI bases, start, or stop/end differ, they are assigned a different unique molecule (MI tag).

> Do you think that GroupReadsByUmi is able to handle a situation like our, where multiple unique fragments are marked with the same UMI?

Collisions will occur if two reads are derived from difference source molecules but have the same UMI _and same start and stop/end_.  In that case, a longer UMI is needed (or dual UMIs).

> Is there any modification in the setting you would suggest to minimize the loss of reads?

You can try the `--edits` option to increase or reduce stringency, though sequencing error in the UMI could cause one read to be assigned to the wrong source molecule when `--edits=0`.

The `GroupReadsByUmi` adopts a similar approach to UMI-tools, see their paper: https://genome.cshlp.org/content/early/2017/01/18/gr.209601.116.abstract

**Comment by emissiaglia** [comment]
Many thanks for your clarifications and help.
I was wondering if the presence of different reads (with different starting or ending positions) with the same UMI would impact the computational time required by the algorithm to assign them to different families. In other words, if we increase the length of our UMI to minimize the risk of having different reads labeled with the same UMI, would that decrease the time require for UMI processing?
Thanks
edoardo

**Comment by nh13** [comment]
@emissiaglia if two reads have the same UMI but different coordinates, then computational performance wont be affected since reads are split by coordinates first.  If we have many many reads with the same start/stop positions, then computational performance degrades significantly as we have to compare UMI sequences across all reads with the same start/stop positions.  We have a few novel ideas to improve the performance in this case, but have no organization yet willing to sponsor that work.
