### ISSUE TITLE
WES data with UMI

### ISSUE THREAD

**Issue by Nickier0510** [fulcrumgenomics/fgbio#707]
Hi ~ I get a WES data set, each sample contains 3 fastq files, 1.fastq.gz, 2.fastq.gz and *umi.fastq.gz, as shown in the figure below. I know the workflow of WES data, but I don't know what the UMI file does. Whether there is a related tutorial?  I know the non-UMI WES data workflow: BWA-MarkDuplicates-BQSR-Call Variant, but I don't know how to analyze UMI-WES data, such as how to Call Variant. What's more, the second base is N in the 1.fastq.gz . Why? Could it be related to UMI?
Thank you~

![image](https://user-images.githubusercontent.com/52686760/133066529-014e212c-1ba5-4aaa-99e8-3cc98e68d777.png)

**Comment by nh13** [comment]
@Nickier0510 this question is a little too broad for this venue.  Have you tried posting this question to [Biostars](https://www.biostars.org/)?  If there are questions about specific fgbio tools, feel free to re-open and we're happy to continue the discussion.

**Comment by Nickier0510** [comment]
Hello, I saw that fgbio has a tool FastqToBam. I want to know whether my data needs to be preprocessed by this tool. Or how should I use fgbio's best practice workflow to process my data. I have asked this question on biostars, and someone answered using umi_tools, I am trying.
