### ISSUE TITLE
readstrcuture puzzle

### ISSUE THREAD

**Issue by asmlgkj** [fulcrumgenomics/fgbio#721]
Dear author,
thanks a  lot for this tool.
1   I want to know if umi data needed to do adpter trim before umi extract(I think should do extract umi first)
2 if I set  fgbio ExtractUmisFromBam  3M2S146T 3M2S146T, if a read not has 146T, will it be filtered?

**Comment by nh13** [comment]
1. If you want to adapter trim, then do so after alignment, which may just not align adapters anyhow.
2.  `3M2S146T` will require the given read to have 151bp.  You can also use `3M2S+T` to capture reads of any length but with a leading fixed set of 5bp.  See the [read structures on the wiki](https://github.com/fulcrumgenomics/fgbio/wiki/Read-Structures) and [this handy web-tool for validating your read structures](https://fulcrumgenomics.github.io/fgbio/validate-read-structure.html)

**Comment by asmlgkj** [comment]
@nh13 
thanks  a lot
I am not clear about do trim after align, tools like fastp fastqc do trim on fastq

**Comment by nh13** [comment]
@asmlgkj you could run `picard MarkIlluminaAdapters`, but that doesn't trim, only mark.  It may not be necessary to trim your adapters based on your application, as likely the aligner (.g. `bwa`) will soft-clip them.  Nonetheless, the question of soft-clipping is a bit beyond the scope of `fgbio` tools, so I'd refer you to a more general help forum like https://www.biostars.org/.

**Comment by asmlgkj** [comment]
thankas  alot
for the non-umi data, we oftern run fastp and then bwa, 
I am not very sure about umi data, whether extract umi; fastp and then bwa,  is a suitable process
