### ISSUE TITLE
Using CallMolecularConsensusReads output with Picard CollectHsMetrics

### ISSUE THREAD

**Issue by caitloh** [fulcrumgenomics/fgbio#727]
I am trying to use an output .bam from CallMolecularConsensusReads as the input for Picard CollectHsMetrics, but I get the error "Sequence dictionaries are not the same length". 

I looked at the header of the CMCR .bam and saw that there is no sequence dictionary in that file, whereas the original .bam had one. I assume this is causing the issue with Picard.

Is it possible to remedy the sequence dictionary issue so I can use the CMCR output in the Picard tool?

**Comment by nh13** [comment]
@caitloh you'll need to map the reads coming out of `CallMolecularConsensusReads` as we do not retain mapping information.  Hopefully since there are far fewer consensus reads than input raw reads, that isn't too much of a burden.
