### ISSUE TITLE
improve ClipBam speed?

### ISSUE THREAD

**Issue by eboyden** [fulcrumgenomics/fgbio#746]
The output of most aligners is already name-collated, but ClipBam still re-sorts name-collated input into queryname order - is this necessary?

Additionally, after clipping it sorts the output into coordinate order, which is a nice feature but perhaps should be optional, in case either the output needs to be in name-collated order or a faster sort tool is desired.

**Comment by nh13** [comment]
@eboyden 
1. `ClipBam` will only re-sort if the SAM header is neither `queryname` sorted nor `query` grouped.  (e.g. `@HD\tVN:1.5\tSO:quername` or `@HD\tVN:1.5\tSO:unsorted\tGO:query`).  So if the header is correct, the input will not be resorted.  If you're using `bwa mem`, consider using the `-H` option to specify a `@HD` line, and lend support to this PR: https://github.com/lh3/bwa/pull/336
2. @eboyden I think the output not being sorted is a totally fine request.  We also re-sort to coordinate order so we can reset/update the NM/UQ/MD tags, which are MUCH easier to recalculate when iterating through in coordinate sort (we can load one reference contig at a time).  If you have a need for this, feel free to make a PR or keep this issue open.  For the latter, I am not sure we'll get to it in any reasonable time.

**Comment by eboyden** [comment]
That makes sense, I wasn't aware that the file needs to be _explicitly_ sorted or collated according to the `@HD` line (rather than e.g. fgbio auto-detecting and crashing if it incorrectly decides that the file is already sorted).  We do use `bwa mem` and appreciate the PR (+1'd) but we also use several other aligners including `bwa-mem2`, `minimap2`, and `bowtie2`; getting everyone on the same page with respect to the importance of a properly formatted `@HD` line according to the latest SAM spec is a sisyphean task and certainly not your responsibility to enforce.

And for the output order, it wasn't clear to me that resetting those tags benefited from coordinate sorting.  If resetting the tags without sorting would end up taking as long as resorting the output if coordinate-sort isn't desired, then it doesn't seem like adding this functionality makes much sense after all.

Thanks for the excellent software and diligent maintenance!

**Comment by eboyden** [comment]
@nh13 Thanks for the tip!  It looks like Samtools `reheader` can also do this, and with the `-c` option it can edit a header rather than replace the entire thing.
