### ISSUE TITLE
GroupReadsByUmi not assigning correct strand information

### ISSUE THREAD

**Issue by Alexander-Palmer** [fulcrumgenomics/fgbio#756]
Hi team, 

I’m trying to group paired end reads as part of a duplex sequencing experiment using _GroupReadsByUmi_. 

However, instead of assigning the forward and reverse strands of each molecule as #/A & #/B in the MI tag, the program calls both strands as #/A **OR** #/B. As a result, it artificially increases the total number of UMI groups and prohibits grouping of identical reads with _CallDuplexConsensusReads_.

This is a sample from my file:

A00133:442:HM5MFDSX2:3:1602:16966:18443 97      11      32646552        60      145M    =       32646621        214    TGTGTTAGTTGTCCTGCCTCTGACAGCAGACTTGGTGATTCCAATGTCTGTTCTGGCTACTGCTTGGAGAGGCACAAGGCAGTGCCAGGCTTTGTTTACCTTTCTGCTGTGTCTATGCCTTCAGGTTTGCTGAGCGCCTGACTGC     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF                                           ZA:Z:CAG ZB:Z:CAC        MC:Z:145M       MD:Z:145        PG:Z:bwa        RG:Z:A  **MI:Z:0/A**        NM:i:0  MQ:i:60 UQ:i:0 AS:i:145                                                                                                     RX:Z:CAG-CAC

A00133:442:HM5MFDSX2:3:1602:16966:18443 145     11      32646621        60      145M    =       32646552        -214   AGGCACAAGGCAGTGCCAGGCTTTGTTTACCTTTCTGCTGTGTCTATGCCTTCAGGTTTGCTGAGCGCCTGACTGCCCAAGTGACCCAGTCTGCCCTTTGACCTCATGCCTTGTGTCCTGCAGCTTTGCTATACATGTATTACTT     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFFFFF:FFFFFFFFFFFFFF                                           ZA:Z:CAG ZB:Z:CAC        MC:Z:145M       MD:Z:145        PG:Z:bwa        RG:Z:A  **MI:Z:0/A**        NM:i:0  MQ:i:60 UQ:i:0 AS:i:145                                                                                                     RX:Z:CAG-CAC

Could this be a bug? After checking the original .fq files, UMIs and SAM flags everything seems to be normal.
I can provide some of my files if that makes things any easier to troubleshoot.

Cheers,
Alex

**Comment by nh13** [comment]
The two examples you gave are reads from the same read-pair (template), so they should have the same molecular identifier suffix (eg. `/A`).  In this case you have R1 at `chr11:32646552+` and R2 at `chr11: 32646621-`.   If you see another read-pair with **R2** at `chr11:32646552-` and **R1 at `chr11: 32646621+` (note the R1/R2 swapped and strand swapped versus the first read-pair), then this latter template should have suffix `/B`).  The `/A` and `/B` identify which strand of the source molecule the read-pair (template) originates, not the individual ends of a read-pair.  

More resources:
* Definition of `/A` and `/B`: https://github.com/fulcrumgenomics/fgbio/blob/ccb2a76b1b73ae10f6680530205c3e7e51264e01/src/main/scala/com/fulcrumgenomics/umi/GroupReadsByUmi.scala#L57-L63
* https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads

**Comment by Alexander-Palmer** [comment]
Thanks for getting back to me so quickly! I didn't realize that the `/A` and `/B` strands were dependent on the original sense as predicated in the SAM flags. My issue with UMI groups must be a result of insufficient amplification on my end. Again, thanks for the help.
