### ISSUE TITLE
The reads in family-size-histogram do not add up to what is present in consensus mapped BAM?

### ISSUE THREAD

**Issue by EwaMarek** [fulcrumgenomics/fgbio#765]
Hi,

I'm confused about the content of family-size-histogram produced by GroupReadsByUmi. I was expecting it to report how many reads there are with a given family size but it doesn't add up to the total number of reads in my consensus mapped BAM:

test_sample.consensusMapped.bam total number of reads: **468 344**

| family size | histogram | consensus mapped BAM^ |
|-------------|-----------|-----------------------|
| 1           | 224398    | 450719                |
| 2           | 8551      | 16900                 |
| 3           | 355       | 698                   |
| 4           | 13        | 25                    |
| 5           | 1         | 2                     |
| SUM         | 233318    | 468344                |

^ obtained using `samtools view test_sample.consensusMapped.bam | grep -c "cD:i:X"`, where X is family size

So it seems to me that histogram reports roughly half of the reads with given family size present in the consensus mapped BAM, is there some filtering going on just to produce histogram values?

Many thanks,
Ewa

**Comment by nh13** [comment]
@EwaMarek The counts coming out of `GroupReadsByUmi` are per-template, where as your command counts R1 and R2 twice.  You'll want to run `samtools view -F 64 test_sample.consensusMapped.bam | grep -c "cD:i:X"` to just look at R1 to get the per-template family size.  See https://broadinstitute.github.io/picard/explain-flags.html for more details on why `-F 64` selects only R1 reads.

**Comment by EwaMarek** [comment]
Thanks for your quick response! I didn't realize that the counts are reported per-template  :facepalm: 
It makes sense now, thanks for the clarification.
