### ISSUE TITLE
Error building with sbt

### ISSUE THREAD

**Issue by KevinYie** [fulcrumgenomics/fgbio#785]
Hello,

I am encountering the following issues when building with sbt. I'm relatively new to using sbt so there may be some configuration that could be incorrect. Thank you in advance for the help and time! 

[yiek01_adm@gn-0001 fgbio]$ sbt assembly
[info] welcome to sbt 1.6.2 (Oracle Corporation Java 1.8.0_181)
[info] loading settings for project fgbio-build from plugins.sbt ...
[info] loading project definition from /gpfs/share/apps/fgbio/1.5.1/raw/fgbio/project
[info] Updating
[info] Resolved  dependencies
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.github.gseitz:sbt-release:1.0.10 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.typesafe.sbt:sbt-git:1.0.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]          com.jsuereth:sbt-pgp:2.0.1 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn]  Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.github.gseitz:sbt-release;sbtVersion=1.0;scalaVersion=2.12:1.0.10
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/gseitz/sbt-release_2.12_1.0/1.0.10/sbt-release-1.0.10.pom
[error]   not found: /gpfs/home/yiek01_adm/.ivy2/localcom.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml) while downloading https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-git;sbtVersion=1.0;scalaVersion=2.12:1.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-git_2.12_1.0/1.0.0/sbt-git-1.0.0.pom
[error]   not found: /gpfs/home/yiek01_adm/.ivy2/localcom.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml) while downloading https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error] Error downloading com.jsuereth:sbt-pgp;sbtVersion=1.0;scalaVersion=2.12:2.0.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/jsuereth/sbt-pgp_2.12_1.0/2.0.1/sbt-pgp-2.0.1.pom
[error]   not found: /gpfs/home/yiek01_adm/.ivy2/localcom.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml) while downloading https://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]         at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:345)
[error]         at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:314)
[error]         at scala.util.Either$LeftProjection.map(Either.scala:573)
[error]         at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:314)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error]         at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error]         at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3690)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.github.gseitz:sbt-release;sbtVersion=1.0;scalaVersion=2.12:1.0.10
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/github/gseitz/sbt-release_2.12_1.0/1.0.10/sbt-release-1.0.10.pom
[error]   not found: /gpfs/home/yiek01_adm/.ivy2/localcom.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml) while downloading https://dl.bintray.com/sbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.github.gseitz/sbt-release/scala_2.12/sbt_1.0/1.0.10/ivys/ivy.xml
[error] Error downloading com.typesafe.sbt:sbt-git;sbtVersion=1.0;scalaVersion=2.12:1.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-git_2.12_1.0/1.0.0/sbt-git-1.0.0.pom
[error]   not found: /gpfs/home/yiek01_adm/.ivy2/localcom.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml) while downloading https://dl.bintray.com/sbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-git/scala_2.12/sbt_1.0/1.0.0/ivys/ivy.xml
[error] Error downloading com.jsuereth:sbt-pgp;sbtVersion=1.0;scalaVersion=2.12:2.0.1
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/jsuereth/sbt-pgp_2.12_1.0/2.0.1/sbt-pgp-2.0.1.pom
[error]   not found: /gpfs/home/yiek01_adm/.ivy2/localcom.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]   download error: Caught java.io.IOException (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml) while downloading https://dl.bintray.com/sbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml
[error]   download error: Caught java.net.SocketException (Connection reset) while downloading https://repo.typesafe.com/typesafe/ivy-releases/com.jsuereth/sbt-pgp/scala_2.12/sbt_1.0/2.0.1/ivys/ivy.xml

**Comment by nh13** [comment]
@KevinYie it looks like you are using scala 2.12.  We removed support for scala 2.12 in [release 1.4.0](https://github.com/fulcrumgenomics/fgbio/releases/tag/1.4.0). Please update your scala version to 2.13.
