### ISSUE TITLE
Consensus base qualities are all N after CallMolecularConsensusReads

### ISSUE THREAD

**Issue by taicher** [fulcrumgenomics/fgbio#808]
Hi,

When I run CallMolecularConsensusReads on my BAM file (after grouping by UMI and creating the MI tag) it outputs consensus reads but the FASTQ quality scores are all marked as N. I don't understand why as the original FASTQ quality scores are high and the consensus reads look as they overlap perfectly (I have attached a screenshot of one example of this). I understand N is a masked base when the quality scores are low but I have not changed the quality score masking threshold and I don't understand why the quality score would be low. 

Is there a reason CallMolecularConsensusReads is calling the quality scores as N for consensus reads? Is it something to do with the bam file format? The exact commands I used were:

java -jar /gpfs/home/tpa239/evronylab/bin/fgbio/fgbio-1.4.0.jar GroupReadsByUmi --input input.bam --output grouped.bam --strategy=identity

java -jar /gpfs/home/tpa239/evronylab/bin/fgbio/fgbio-1.4.0.jar CallMolecularConsensusReads --input grouped.bam --output=collapsed.bam --min-reads=2

I am using fgbio-1.4.0

Thank you

<img width="756" alt="Screen Shot 2022-03-09 at 4 40 20 PM" src="https://user-images.githubusercontent.com/19956079/157540803-164e5fe4-a7b8-41bf-a8f1-156d7f13171b.png">

<img width="1195" alt="MI_992_uncollapsed" src="https://user-images.githubusercontent.com/19956079/157539738-e4e7aa0a-f505-4b8d-b2ae-f995677a9716.png">

**Comment by nh13** [comment]
@taicher that is super strange.  I'd suggest the following:
1. Can you try running `CallMolecularConsensusReads` with the latest release version (`1.5.1`).  I am doubtful it will help, but worth a shot.
2. Can you post a SAM file for just the grouped reads in the screen shot for us to try to reproduce?

**Comment by tfenne** [comment]
@taicher the quality scores are encoded as ASCII characters by adding 33 to the numerical Phred score and converting to a character.  So `N` indicates a quality score of Q45.   (and M = Q44 and so on).  So what you're actually seeing is that post consensus calling and filtering as you're doing, we're calling most of the bases as  Q45.  This is exactly what I'd expect.

**Comment by nh13** [comment]
Doh, and here I am, the one who authored this page: https://broadinstitute.github.io/picard/explain-qualities.html. It’s time for bed, thanks @tfenne!

**Comment by taicher** [comment]
Thank you that makes sense my bad! I was confused because the documentation says "Deprecated: will be removed in future versions; use FilterConsensusReads to filter consensus bases on quality instead. Mask (make ‘N’) consensus bases with quality less than this threshold."

But I realize when it says "Mask (make 'N') consensus bases" the actual base will be coded as N instead of its quality score which was my mistaken interpretation.
