### ISSUE TITLE
how will figbio choose base?

### ISSUE THREAD

**Issue by asmlgkj** [fulcrumgenomics/fgbio#818]
if one position has 6 reads with the same start and end postion(postion1-position100), 
two reads with umi1 has base T in postion50, two reads with umi2 has base G in postion50,,and the other 2  with umi3  base C in postion50, how will fibio select the final base of this postion?
 Thanks a lot

**Comment by nh13** [comment]
Please add more details if the below assumptions are not correct, in particular about which tools you are using. There are many tools in `fgbio` including two for consensus calling depending on the type of data you have.

First, I assume you have run `GroupGreadsByUmi`.  This will assign the two reads with `umi1` to `molecule11, the two reads with`umi2` to `molecule2`, and the two reads with`umi3` to `molecule3`.  

Next, I assume you run `CallMolecularConsensusReads`.  This produce a consensus call for each molecule independently, using the reads from a given molecule.  So it will first consensus call the two reads from `molecule1`, both of which have a `T`, so the consensus at that position is `T`.  And so on for `molecule2` and `molecule3`.

**Comment by asmlgkj** [comment]
thanks  a lot for your kind help @nh13 .
I am using fgbio as the best practice.
I am just thinking of this question for fgbio, because if more input dna in library, the above assuption may happen, for each cluster it has a conssensus base, as T G C for umi1,2,3
but how will fgbio give the final base of this site, this is what I want to know

**Comment by nh13** [comment]
fgbio will not give a final base at this site, since there is no variant caller in fgbio.  Depending on your use case, you can use VarDictJava, MuTect2, GATK Haplotypecaller, freebase, strelk2, or others.  But that is beyond the scope of this toolkit.

**Comment by asmlgkj** [comment]
thanks a lot for your kind help @nh13 .
I know it will not give variant, but will fgbio keep all these three consensus base at the final output bam?

**Comment by nh13** [comment]
Yes, each consensus read will be its own SAM record in the output BAM file.  Give it a try!

**Comment by asmlgkj** [comment]
thanks a lot for your kind help @nh13 .
because I am not able to produce such case in data.
I am just thinking of such case in my mind.
in the other hand, from your experience, if  there was the above case, no matter which tools to be used (VarDictJava, MuTect2, GATK Haplotypecaller, freebase, strelk2, or others), do you think this base should call out a variant?

**Comment by nh13** [comment]
it should, but you need to get your hands on some data

**Comment by asmlgkj** [comment]
thanks a lot for your kind help @nh13.

**Comment by nh13** [comment]
Oh, and look for publicly available data from papers that deposit up to SRA and elsewhere.  I don't see why you can't get access to data if you spend the time looking.

**Comment by asmlgkj** [comment]
thanks a lot for your kind help @nh13.
I mean it is hard for me to find such sppecial case in bam or I can not find the easy way to find this
