### ISSUE TITLE
Does DemuxFastqs mismatch option apply to each barcode individually?

### ISSUE THREAD

**Issue by denriquez** [fulcrumgenomics/fgbio#827]
I have a question about the software tool fgbio DemuxFastqs. Does the max-mismatches option apply to each individual sample barcodes separately with regards to dual indexing? For instance, does that option allow one mismatch for the i7 index barcode and one for the i5 index barcode similar to bcl2fastq and BCL Convert?

**Comment by nh13** [comment]
The # of mismatches is calculated across all barcodes bases, so for dual index barcodes, that's across i5 and i7.   There is no option to specify the maximum number of mismatches _per segment_.  If you have a motivating example, I'd be curious.

**Comment by denriquez** [comment]
I am interested in demultiplexing off of FASTQ files to try to generate as similar results as BCL Convert. This is for uncommon situations when the BCL files are not accessible/available and demultiplexing needs to be redone.

**Comment by nh13** [comment]
Got it. Unfortunately it won’t be a perfect match and there’s no plan to do so. Hopefully that’s ok in the rare cases you need to use it.
