### ISSUE TITLE
Should fastqs be trimmed after ExtractUmisFromBam and before GroupReadsByUmi?

### ISSUE THREAD

**Issue by xiucz** [fulcrumgenomics/fgbio#839]
Hi, 
Thanks for your wonderful tool, after search the documents and the internet, I  still have a question, Should fastqs be trimmed after ExtractUmisFromBam and before GroupReadsByUmi?
And my pipline steps:

```
1. FastqToSam
2. ExtractUmisFromBam
3. SamToFastq
4. fastp
5. bwa mem & MergeBamAlignment
6. GroupReadsByUmi
```
Thank you,
xiucz

**Comment by xiucz** [comment]
Thank you! @nh13 , 

maybe I use an old version(fgbio-1.3.0.jar), so the `ExtractUmisFromBam` is still in my pipeline. I will update to the lastest version to feedback.  But I don't know why people don't do quality filtering during the fgbio processing when I search the keyword of "fgbio".

**Comment by nh13** [comment]
1. Aligners are pretty good about soft-clipping bases (e.g. adapters)
2. There is base quality trimming in `FilterConsensusReads`.

I think a motivating example where you got better results with quality trimming at a given step would be super helpful to us.
