### ISSUE TITLE
FilterConsensusReads  error 

### ISSUE THREAD

**Issue by fengdong110** [fulcrumgenomics/fgbio#841]
Dear fgbio developers:

   When i use fgbio-1.0.0.jar  FilterConsensusReads to deal my sample, I get the following error:

      Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Expected the AB-strand to have depth > 0 for read: BJ22CM006938_T:32807517 1/2 1b unmapped read.

    When I go back to check my BAM files, I find the BJ22CM006938_T:32807517 reads in consensus.ubam as following:
![image](https://user-images.githubusercontent.com/19946295/168737983-9c55d6f7-201a-4176-a839-4fd5445753e7.png)

    I want to know  how do  I handle this error.   Is my CallDuplexConsensusReads parameter problem?
    Although I can use samtools view -h BJ20CM022432.consensus.merge.bam | grep -v "BJ22CM006938_T:32807517" | samtools view -Sb - >BJ20CM022432.consensus.merge2.bam deal this error. but i want to know If there's an easier way?

    My command line is as follows:
     /software/java/jdk1.8.0_202/bin/java -Xmx20g -Djava.io.tmpdir=./tmp -jar /software/fgbio/fgbio-1.0.0.jar CallDuplexConsensusReads -i BJ20CM022432.group.bam -o BJ20CM022432.consensus.ubam --min-reads=1 0 0 --min-input-base-quality=30 --error-rate-pre-umi=45 --error-rate-post-umi=30

      /software/java/jdk1.8.0_202/bin/java -Xmx20g -Djava.io.tmpdir=./tmp -jar /software/fgbio/fgbio-1.0.0.jar FilterConsensusReads -i BJ20CM022432.consensus.merge.new.bam -o BJ20CM022432.consensus.filter.bam -r ucsc.hg19.fasta --min-reads=1 0 0 --max-read-error-rate=0    .05 --max-base-error-rate=0.1 --min-base-quality=30 --max-no-call-fraction=0.2

 Thank you very much.

**Comment by nh13** [comment]
1. Please use the latest version of fgbio as 1.0.0 was almost three years ago!
2. It also looks like one of the reads is only a single-base.  Please investigate why before reporting back.
