### ISSUE TITLE
Calling both duplex and single-strand consensus sequences

### ISSUE THREAD

**Issue by tobyaicher** [fulcrumgenomics/fgbio#843]
Hi,

I wanted to ask if fgbio is able to create duplex consensus strands when possible but includes single-strand consensus strands even when you are unable to create duplex strands. 

My guess is that this is what happens when you use:

 CallDuplexConsensusReads using -min-reads=2 2 0

But I wanted to confirm. 

Thank you!

**Comment by nh13** [comment]
Yes, it does have this feature.  Try `--min-reads 1 1 0`.  The first value says that the consensus has to have at least one input read, the second value says the "A" strand must have at least one input read, and the third value says the "B" strand can have no reads.  With `--min-reads 2 2 0` you'd require that all consensus reads must have at least two reads, even single strand consensus reads.

**Comment by tobyaicher** [comment]
Hi,

I just wanted to confirm one more thing:

If I use --min-reads 2 1 0, for a SSCS read where only one of the strands has reads and the other has 0 reads, will these reads always be under the "a" tag?

For instance, if you have a SSCS read, one of the reads will have >=2 and the other will have 0. In the final output cram, will it be the case that the aD:i tag will have >= 2 and the bD:i: will be equal to 0? Or is it ever the case that for whatever reason the bD:i tag could have >= 2, and the aD:i tag will have 0?

When I look through the final output BAM, this seems to be the case and there are no reads with aD:i0, but wanted to confirm this is always the case due to how fgbio is coded.

Thank you!

**Comment by nh13** [comment]
Yes, see: https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling#top-and-bottom-strand-single-strand-reads-relative-to-duplex-consensus-reads

**Comment by tobyaicher** [comment]
I see thank you!
