### ISSUE TITLE
ZipperBams vs bwa mem -C

### ISSUE THREAD

**Issue by stsergbg** [fulcrumgenomics/fgbio#844]
Hi!

Is there any difference between doing samtools fastq -T RX + bwa mem -C and using ZipperBams in the pipeline?

**Comment by tfenne** [comment]
There are functional differences, but depending on your use case they may not matter.  The major differences are:

1. Using `ZipperBams` the header of your unmapped BAM will be preserved in the output BAM.  This isn't usually such a big deal if a) you just have raw sequencing data and b) your uBam contains a single read-group (`@RG`), but is quite helpful if your uBAM has either multiple read groups _or_ you have a more complicated processing history (e.g. you have an unmapped _consensus_ BAM).
2. `ZipperBams` will, by default, copy all tags over from the input BAM that are not present in the aligned BAM, without you having to specify the list of tags anywhere.  So again, if you have a minimal uBAM it doesn't make much difference.
3. `ZipperBams` has the ability (and defaults that match fgbio's consensus tools) to reverse and reverse-complement array optional tags for reverse strand mapped reads to keep them in sync with the read.  This is helpful when re-mapping consensus reads that have all the additional tags describing per-base errors, depths, etc.

**Comment by stsergbg** [comment]
Thank you! Looks indispensable, especially for the [step 2(a).2](https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md#step-2a2-consensus-ubam---consensus-mapped-bam) of the best practices document.
