### ISSUE TITLE
bug in CallMolecularConsensusRead?

### ISSUE THREAD

**Issue by ruolin** [fulcrumgenomics/fgbio#851]
Hello, I encountered some issues in the CallMolecularConsensus. I think the output of this program is wrong. I used the following cml `java -jar fgbio-2.0.2.jar CallMolecularConsensusReads -i test.bam -o test.consensus.bam -M 1`. The reads were mapped to hs37. The example input is here [test.sam.txt](https://github.com/fulcrumgenomics/fgbio/files/8847062/test.sam.txt). It is one single family. 

The consensus has a `T` at the 44 bp from the 5'end, although all the input reads at this position have either `C` or `N`.

**Comment by nh13** [comment]
I'm curious, the UMIs in the RX tag look very different across the reads in this same family.  Is that to be expected?

I don't think this is correct:
> The consensus has a `T` at the 44 bp from the 5'end, although all the input reads at this position have either `C` or `N`. 

For the R1s I see:

```console
$ samtools view -h -f 0x40 -S input.sam | samtools fastq | awk 'NR%4==2' | cut -c 44 | sort | uniq -c
   8 C
   5 N
  10 T
```

and for R2s I see:
``` console
$ samtools view -h -f 0x80 -S input.sam | samtools fastq | awk 'NR%4==2' | cut -c 44 | sort | uniq -c
  10 C
   1 N
  12 T
```

Thus there is significant disagreement for that particular base in the R1 and R2 reads respectively.

**Comment by ruolin** [comment]
@nh13 Hi, thanks for the quick reply as always! Sorry I was not very clear. I am talking about the 44th bp after alignment or in the reference genome direction. If you do 
```
samtools view test.bam | cut -f 10  | cut -c 44 | sort | uniq -c
36 C
10 N
```

and if you mapped the consensus read, the 44th aligned consensus bp become a `T` which leads to a false mutation detection. 

I think I may have a sense of what might happened. This read family actually contains fragments from different strand orientations, i.e. having both F1R2 and F2R1. Is this supposed to happen? Per your question asked, the RX looks very different with this family. I don't think this is expected. I used `GroupReadsByUmi --strategy edit -e 2` and I just realized from you doc this is maybe a bad opt for this high coverage data. But regardlessly, the result now is a single family with reads from two different strands. in this situation, I do want to get two different families separately for the top and bottom strands. Do you think it is because of the hyphen that makes the program think it is duplex family?

**Comment by nh13** [comment]
For duplex data, you'll want to use `--strategy adjacency`.  And typically one uses `CallDuplexConsensusReads` after that.  But you can use `CallMolecularConsensusReads` on the output and it should create single strand reads (see https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling for AB and BA reads)

**Comment by ruolin** [comment]
ok. I don't have further questions. you can close it if you want.
