### ISSUE TITLE
ExtractUmisFromBam "Read was not the second end of a pair" Error

### ISSUE THREAD

**Issue by dstephensSD** [fulcrumgenomics/fgbio#852]
I'm getting a error with ExtractUmisFromBam (fgbio 2.0.2) that I can't figure out how to get around.  I converted fastq to bam using:

```
      picard FastqToSam  \
          FASTQ={input.fq1}  \
          FASTQ2={input.fq2}  \
          O={output}  \
          TMP_DIR=tmp  \
          SM={wildcards.sample}  \
          -Xmx32g
```

Then ran ExtractUmisFromBam as follows:

```
      fgbio ExtractUmisFromBam    \
          --input={input}  \
          --output={output}  \
          --read-structure=8M143T 8M143T  \
          --molecular-index-tags=ZA ZB  \
          --single-tag=RX  \
          -Xmx32g
```

Here is the error:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/103445628/172251976-adb1f852-4bee-4a31-a22d-7ec7932aa999.png)

I'm not sure how to get around this.  Any suggestions?

**Comment by nh13** [comment]
@dstephensSD I don't see anything immediately obvious with what you're doing.  The only think I can think of is that the FASTQs are out of sync with each other, but that seems unlikely. 

The other option is to go straight from FASTQ to annotated BAM.  You can use `fgbio FastqToBam` to perform the above two steps directly.

**Comment by dstephensSD** [comment]
Thank you very much for the very quick reply!  I will try what you have suggested - thanks again

**Comment by dstephensSD** [comment]
I implemented the following:

```
        fgbio FastqToBam  \
            --input={input.fq1} {input.fq2}  \
            --output={output}  \
            --sample={wildcards.sample}  \
            --library={params.flowcell}  \
            --read-structure=8M143T 8M143T  \
            --extract-umis-from-read-names=true  \
            --umi-tag=RX  \
            -Xmx64g
```

Unfortunately I get this error:

![image](https://user-images.githubusercontent.com/103445628/172267086-1ffaf1d7-4751-441c-8c9e-f5ffb72c306b.png)

Any ideas of what to check or test further?

Thank you

**Comment by nh13** [comment]
Check the FASTQs for the read with the name on the error message, it likely is truncated from 151bp. Did you adapter or quality trim prior to running the tool? If so, you can try the read structure: 8M+T 8M+T. The plus-T allows for a variable number of template bases up to the end of the read.

**Comment by dstephensSD** [comment]
I did not do any adapter or quality trimming.  I will take a look at the read in question.  Thank you for the response!

**Comment by dstephensSD** [comment]
Changing the read structure worked, thank you!

**Comment by nh13** [comment]
I’d still check your reads too. Glad the latter unblocked you!
