### ISSUE TITLE
Error: Sample at ordinal #1 is missing: Sample_ID

### ISSUE THREAD

**Issue by Phylloxera** [fulcrumgenomics/fgbio#856]
Using DemuxFastqs for the first time. It doesn't seem to like my metadata file, but I'm using one I got from another user on site and It seems to be following your specifications.
`head plate_04.csv`
﻿Sample_ID,Sample_Name,Library_ID,Sample_Barcode
LIB111785,SAM115593,LIB111785,CGTACGTA
LIB111786,SAM115594,LIB111786,AGCTAGCT
LIB111787,SAM115595,LIB111787,GCTTAACG
LIB111788,SAM115596,LIB111788,ATCCGGTA
LIB111789,SAM115597,LIB111789,TAGGCCAT
LIB111790,SAM115598,LIB111790,GCTACGAT
LIB111791,SAM115599,LIB111791,GATCAGCT
LIB111792,SAM115600,LIB111792,AACGTTGC
LIB111793,SAM115601,LIB111793,GACTTCAG

The full error is 
Exception: IllegalArgumentException
Error: Sample at ordinal #1 is missing: Sample_ID

ideas?

**Comment by nh13** [comment]
Try running `dos2unix` on the file.

**Comment by Phylloxera** [comment]
dos2unix appears to have converted to tab delimited?
`head plate_04.csv`
Sample_ID       Sample_Name     Library_ID      Sample_Barcode
LIB111785       SAM115593       LIB111785       CGTACGTA
LIB111786       SAM115594       LIB111786       AGCTAGCT
LIB111787       SAM115595       LIB111787       GCTTAACG
LIB111788       SAM115596       LIB111788       ATCCGGTA
LIB111789       SAM115597       LIB111789       TAGGCCAT
LIB111790       SAM115598       LIB111790       GCTACGAT
LIB111791       SAM115599       LIB111791       GATCAGCT
LIB111792       SAM115600       LIB111792       AACGTTGC
LIB111793       SAM115601       LIB111793       GACTTCAG

This time got 240 lines prior to the ...ordinal 1 is missing... error
I can attach if you want. Thanks for your help!

**Comment by nh13** [comment]
dos2unix should not have changed the delimiter.  Here's mine:
[plate_04.unix.csv](https://github.com/fulcrumgenomics/fgbio/files/8970152/plate_04.unix.csv)

**Comment by Phylloxera** [comment]
your file worked! i probably lost my delimiter trying to copy/paste from excel to nano
