### ISSUE TITLE
Unexpected Consensus Sequence When Using CallMolecularConsensusReads

### ISSUE THREAD

**Issue by bebelya** [fulcrumgenomics/fgbio#862]
Hi, I have a bam file containing a number of PCR duplicates. ~80% raw reads match the reference sequence exactly, while the rest have one or more errors. I would expect the consensus sequence to match the reference in most cases, but it doesn't. 

To isolate the problem, I extracted 30K reads corresponding to one specific UMI (yes, there were a lot of PCR duplicates!). I further set all quality scores to "F" to prevent those from potentially influencing the consensus calculation. As expected, a single paired-end consensus was generated. I tested two sets of parameters: --max-reads=10 --min-reads=2, and --max-reads=5000 --min-reads=2. In both cases, the second sequence of the consensus pair doesn't match the reference. In contrast, >80% raw reads at that coordinate are identical to each other, and are a perfect match the reference. 

Any thoughts?
Thanks!

**Output when --max-reads=10 --min-reads=2**
lib:0   77      *       0       0       *       *       0       0       GTTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC      NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN        cD:i:10 cE:f:0.142069   RG:Z:A  MI:Z:0  cM:i:10 RX:Z:GGTAAGAGACCGTTGTTCTT       cd:B:s,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10       ce:B:s,2,0,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,0,0,2,2,0,0,2,2,2,2,2,0,2,0,2,0,2,2,2,2,2,2,2,2,2,0,2,2,0,2,2,0,2,0,0,2,2,2,2,2,2,2,0,2,0,2,2,0,2,2,2,2,2,2,0,2,0,2,0,0,2,2,2,2,2,2,2,2,2,2,2,2,0,2,2,2,2,2,2,2,2,2,0,2,0,2,0,2,0,2,0,2,2,2,2,2,2,2,0,0,2,2,2,0,0,2,2,0,0,0,2,0,2,2,0,0,0,0,2,2,0,0,2,0,2
lib:0   141     *       0       0       *       *       0       0       NTNNNNNNNNNNNTNNNNNNCTNNTGNNNNNANGNTNNNNNNNNNTNNTNNCNGGNNNNNNNGNANNANNNNNNANANCCNNNNNNNNNNNNCNNNNNNNNNGNTNANCNTNNNNNNNAANNNACNNGGANANNCCACANATNAG      #N###########N######NN##NN#####N#N#N#########N##N##N#NN#######N#N##N######N#N#NN############N#########N#N#N#N#N#######NN###NN##NNN#N##NNNNN#NN#NG        cD:i:10 cE:f:0.703448   RG:Z:A  MI:Z:0  cM:i:10 RX:Z:GGTAAGAGACCGTTGTTCTT       cd:B:s,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10       ce:B:s,10,0,10,10,10,10,10,10,10,10,10,10,10,0,10,10,10,10,10,10,0,0,10,10,0,0,10,10,10,10,10,0,10,0,10,0,10,10,10,10,10,10,10,10,10,0,10,10,0,10,10,0,10,0,0,10,10,10,10,10,10,10,0,10,0,10,10,0,10,10,10,10,10,10,0,10,0,10,0,0,10,10,10,10,10,10,10,10,10,10,10,10,0,10,10,10,10,10,10,10,10,10,0,10,0,10,0,10,0,10,0,10,10,10,10,10,10,10,0,0,10,10,10,1,0,10,10,0,0,0,10,0,10,10,0,0,0,0,4,10,0,0,10,0,5

**Output when --max-reads=5000 --min-reads=2**
lib:0   77      *       0       0       *       *       0       0       GTTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC      NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN        cD:i:5000       cE:f:0.340637   RG:Z:A  MI:Z:0  cM:i:4999       RX:Z:GGTAAGAGACCGTTGTTCTT       cd:B:s,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,4999,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,4999,5000,5000,5000,5000,5000,5000,5000     ce:B:s,2397,1,2397,2395,2396,2395,2395,2394,2410,2404,2396,2392,2395,2,2395,2395,2395,2395,2397,2395,3,1,2423,2396,3,2,2398,2395,2396,2397,2395,1,2396,3,2395,4,2396,2396,2395,2395,2400,2395,2397,2396,2396,2,2395,2396,3,2395,2395,3,2396,1,5,2396,2396,2392,2394,2395,2400,2397,0,2397,1,2396,2397,1,2400,2396,2396,2395,2396,2395,0,2395,1,2396,3,2,2397,2395,2396,2392,2393,2396,2400,2398,2398,2395,2396,2395,0,2395,2404,2397,2397,2394,2395,2402,2403,2394,1,2397,3,2400,1,2394,7,2396,2,2398,2396,2399,2396,2385,2396,2396,3,9,2399,2395,2396,0,4,2394,2397,3,6,0,2398,1,2399,2397,1,10,2,1,2399,2392,2,9,2401,1,2400
lib:0   141     *       0       0       *       *       0       0       CTCATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGACTCAAGTGACCTGGAGACTCCACAAATAAG      NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN        cD:i:5000       cE:f:0.349849   RG:Z:A  MI:Z:0  cM:i:4999       RX:Z:GGTAAGAGACCGTTGTTCTT       cd:B:s,4999,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,4999,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,4999,4999,4999,4999,4999,4999,4999,4999,4999     ce:B:s,2442,42,2443,2440,2447,2433,2444,2447,2393,2393,2438,2458,2438,37,2447,2440,2444,2446,2438,2452,21,35,2391,2449,23,19,2433,2447,2445,2446,2438,12,2441,17,2444,36,2438,2435,2445,2446,2442,2445,2448,2447,2431,37,2451,2448,23,2446,2439,23,2456,25,18,2437,2426,2442,2424,2449,2436,2441,20,2447,12,2438,2450,47,2449,2448,2453,2442,2427,2455,12,2444,25,2436,37,27,2447,2460,2449,2453,2443,2442,2435,2446,2435,2438,2445,2451,16,2447,2400,2429,2440,2448,2436,2452,2447,2439,22,2442,110,2385,75,2479,29,2438,91,2443,2448,2405,2457,2491,2461,2427,70,142,2498,2499,2454,81,64,2450,2487,47,70,58,2453,45,2392,2436,43,162,43,29,2358,2486,93,180,2409,93,2468

**Comment by nh13** [comment]
I can't see something obvious, other than getting unlucky.  Can you try with different values (e.g. --max-reads 50 or --max-reads 100)?  

We use a [fixed seed for the random number generator](https://github.com/fulcrumgenomics/fgbio/blob/a96cdd781e43538eb777f51334d798f6ac661782/src/main/scala/com/fulcrumgenomics/umi/VanillaUmiConsensusCaller.scala#L121) used to shuffle the reads to downsample, so unfortunately running it multiple times with the same parameters will not affect the results.  

Alternatively, you could share the 30K reads and I could try to reproduce?

**Comment by nh13** [comment]
@bebelya would you mind sharing what kit/assay/technology you're using and from which organization you're from, eas I always interested in who is using our tools on what technology.

**Comment by bebelya** [comment]
Tried --max-reads values between 10 and 5000. The second sequence of the consensus pair never matched the reference. The first sequence was a hit-and-miss. 

If it matters, bam file was first grouped using the following command: 
$ fgbio GroupReadsByUmi -i $inFile -o $outFile --strategy=adjacency --edits=1 --assign-tag=MI.

Happy to share the data! Archive contains bam file and reference fasta. Thanks!
[test.zip](https://github.com/fulcrumgenomics/fgbio/files/9164973/test.zip)

**Comment by nh13** [comment]
A few things:

I looked at the most and least frequent sequences in your input BAMs.

R1:
```
6994 GTTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC
6654 CTCATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCCACAAATAAG
  62 GTTCAATCAATGATCATCTTCTCGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC
  27 GTTCAATCCATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC
  19 CTCATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGACTCAATTGACCTGGAGACTCCACAAATAAG
...
   1 CACATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGTTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAAATGACCTGGAGACTCCACAAATAAG
   1 CACATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCCACAAATAAG
   1 CACATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCATATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCAACAAATAAG
   1 ATTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC
   1 ATCATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCATTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCCAAAAATAATv
```

R2:
```
5064 CTCATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCCACAAATAAG
3539 GTTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACCCATTAC
 115 GTTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACCACACATTAC
 112 GTTCAATCAATGATCATCTTCTAGTGCACTTAGGATTCAAGATCCTATTATCAGGGACAAGAGCAGGATTAGGGATATCCGAGATGGCCACACTTTTAAGGAGCTTAGCATTGTTCAAAAGAAACAAGGACAAACAACCCATTAC
  88 CTCATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACTCTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCAACAAATAAG
...
   1 ATAATACTACAAGTTTGAAAAAATTTAAGCGAAGGAAAACACAGAAAGAGACTATAAACTCTGGACAACATAAAAAAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTGACCTGGAGACTCCACAAATAAG
   1 ATAAACCACCATGTTGGTAACTCTAGATCAGAAGGTAAGGCCAGATAGTGACTGGTCACTCAGGCCAAACTCTAACAGACTTATGCTAACGACAGAAACATCGGTGATCCTCTCTATCAGTAGACCTGGAGAATCAACAAATAAG
   1 AACATCCTCCATGTTGGTACCTCTTGATGCGAAGGTAAGGCCAGATTGTGACTGGTCACACTGGACAACCTCTAACAGCCTTATGCTAACGTCAGGGTCATCGGTGATCCTCTGAATCAATTTACCTGTAGACTCCACAAATAAG
   1 AACATACTACATGTTCGTAACACTATAAGCGAAGGTAAGGCCAGAATCTCACAGGTCACTCAGGACAACCACTAAAAGCCTTATCCTAAAGTAAGGGTCATCGGAGATCCTCTCAATCAATTTACAAAGATACTACACAAATAAC
   1 AAAATCCTACATGTTTGTAAAAATTTAAGCGAAGGTAAGGCCAGATAGTGAATTTTCACTCTGGACAACATCTAAAAGCATTAAGCTAACTTCATGGTCATCTGTGATCCTCTGAATCAATTGACCTGGAGACTCCACAAATAAG
```

Clearly there are two molecules that have been given the same MI (molecular identifier). 

I then looked a the RX tag for the reads in the input BAM, and saw they all have the value `GGTAAGAGACCGTTGTTCTT`.  But then when I looked at the read name I see that it ends with a UMI sequence (maybe) (e.g. `A01174:285:HYJCGDSX2:1:1102:16387:23422:UMI:TTATGGTACAC`).  I then sorted those and say that it does indeed look there are two UMIs:

```
14204 TTATGGTACAC
13634 TAAGTGGGGCG
 638 TTATGGTAGAC
 104 TTAGTGGGGCG
  92 TTATGGTACAA
  26 TAATTGGGGCG
  20 TTATGGTAGAA
  10 TAAGTGGGGCT
  10 ATATGGTACAC
   6 TAAGTGTGGCG
   6 AAAGTGGGGCG
   4 TTATGGTNCAC
...
```

So the question why is the RX tag different than the UMI in the read name, and where did the RX tag get set (and by whom)?  I'd bet if you used the UMI tag in the read name, you'd get sensical results.  

I do find it strange that the sequences are the same for R1s with UMI `TAAGTGGGGCG` compared to  R2s with the UMI `TTATGGTACAC` in the read names.  Are you sequencing the same amplicon so we'd expect many molecules to have the same start/stop?

**Comment by nh13** [comment]
@bebelya as this is likely an issue with your analysis and upstream workflow, and not an issue with the tools themselves, I am closing this issue.  Feel free to re-open if there's an issue with an upstream tool.  If you'd like support beyond fgbio, similar to what I've done above, feel free to reach out to us at https://fulcrumgenomics.com/ (we like getting paid for our work :P).

**Comment by bebelya** [comment]
I agree with your assessment, @nh13. Thanks for looking at the data so diligently.
