### ISSUE TITLE
Best practices ZipperBam after CallDuplexConsensusReads

### ISSUE THREAD

**Issue by tobyaicher** [fulcrumgenomics/fgbio#863]
Hi,

I am following fgbio's best practices (https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md#step-2a2-consensus-ubam---consensus-mapped-bam) but using CallDuplexConsensusReads with min-reads 1 1 0 instead of CallMolecularConsensusReads. 

Do I have to change anything with ZipperBams if I use CallDuplexConsensusReads instead of CallMolecularConsensusReads at this step? Wanted to confirm no changes necessary because the best practices isn't for CallDuplexConsensusRead and wanted to make sure there isn't anything different with the base-level tags that Zipperbams will change unintentionally.

Thank you!

**Comment by nh13** [comment]
Nope, just remember to use the two options:

```
--tags-to-reverse Consensus \
--tags-to-revcomp Consensus
```

and you should be fine.
