### ISSUE TITLE
Best practices CallDuplexConsensusReads with min-reads= 1 1 0

### ISSUE THREAD

**Issue by tobyaicher** [fulcrumgenomics/fgbio#866]
Hi,

I wanted to double check that CallDuplexConsensusReads can be used with min-reads=1 1 0 and then later filtered for duplex reads using FilterConsensusReads. I ask because using min-reads=1 is encouraged in the best practices page (https://github.com/fulcrumgenomics/fgbio/blob/main/docs/best-practice-consensus-pipeline.md#step-2a2-consensus-ubam---consensus-mapped-bam) but this is for the CallMolecularConsensusReads command. Wanted to make sure CallDuplexConsensusREads with min-reads=1 1 0 would still collapse reads correctly and not discard read families with single reads.

Thank you

**Comment by nh13** [comment]
Yes, that should work.  I think it was first supported in #293.
