### ISSUE TITLE
5’-3’ origin of UMIs

### ISSUE THREAD

**Issue by BiancaMor** [fulcrumgenomics/fgbio#869]
Hello,
Sorry this is not an issue, it’s a question.
I have just started working with duplexseq data for my PhD and I have a naive question which I didn’t quite get from the docs.
For the RX: UMI1-UMI2 
Is UMI1 always from my 5’end of the lib and UMI2 always from the 3’ end? 
thank you

**Comment by nh13** [comment]
No worries, questions welcome.  Can you take a look [at the wiki](https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling) and see if you still have questions?
