### ISSUE TITLE
Assertion error: reads out of order

### ISSUE THREAD

**Issue by smithcg02** [fulcrumgenomics/fgbio#87]
Hi
I am currently trying to handle sequence data that contains UMIs. I came across fgbio and have attempted to use some of its applications with my data. I have successfully annotated my bams with UMIs and am now looking to collapse the reads into a consensus sequence. I have tried using the 'GroupReadsByUmi' and 'CallMolecularConsensusReads' applications (I understand that the latter is dependent on the former?) but in both cases I encounter errors;
With regards to the former, the program seems to successfully complete the 'filtering and sorting input' step but stops during the 'Assigning reads to UMIs and outputting' step, giving the error;
_Reads out of order @ D00408:358:C8KK0ANXX:7:1105:12567:37050
at scala.Predef$.assert(Predef.scala:165)
        at com.fulcrumgenomics.umi.GroupReadsByUmi$$anonfun$execute$8.apply(GroupReadsByUmi.scala:447)
        at com.fulcrumgenomics.umi.GroupReadsByUmi$$anonfun$execute$8.apply(GroupReadsByUmi.scala:447)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:447)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:70)
        at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:53)
        at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:41)
        at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)_

When I try running 'CallMolecularConsensusReads' command (ignoring the fact that I haven't grouped reads by UMI) I also get an error;
_Alignments added out of order in SAMFileWriterImpl.addAlignment…
… 
Sort order is coordinate. Offending records are at [chr1:1257827] and [chr1:1257750]_

Do you have any idea what might be causing this issue - and what I can do to get around it. I have tried sorting the UMI-annotated BAM by query name and coordinate (even though in the notes it says this shouldn't matter) and it doesn't make a difference.

I would appreciate any help you could provide. I am relatively new to bioinformatics, so I apologise if the solution is obvious.
Thanks
C

**Comment by tfenne** [comment]
Hi @smithcg02, I'm sorry you're having problems.  You've inferred correctly - the workflow is to run an aligned bam through `GroupReadsByUmi` and then through `CallMolecularConsensusReads` in that order.

Looking at your stack trace the problem that's cropping up is that even after filtering out all un-paired reads and sorting by read name, it's encountering a situation where when it plucks two reads out they don't have the same read name.  The most likely explanation for this is that your BAM file contains reads that are flagged a pairs, but whose mate has been removed from the file for some reason.  Does that sound likely?  You could run Picard's `ValidateSamFile` on your input BAM which should report reads with missing mates.

**Comment by smithcg02** [comment]
Thanks @tfenne 
It does indeed look like some of the reads are missing the mate. I ran ValidateSamFile and got a series of messages like the following;
ERROR: Read name D00408:358:C8KK0ANXX:7:2103:4546:11697, Mate not found for paired read
I'm trying to dig in to the pipeline that yields that bam to see where reads are getting lost. I thought it might be MarkDuplicates but we're retaining all reads after using it...
In the meantime, could I ask why the mate is needed by these commands? Is there a way of getting around the problem of missing mates?
Thanks for your help

**Comment by tfenne** [comment]
The tools in their current state only work with PE data, and discard any SE data.  It's possible they could be patched to also discard reads that claim to be paired, but with the mate missing.  However, it would probably be better/easier to simply sanitze the input BAM before running the tool.  I'm pretty sure you can use picard's `RevertSam` with `SANITIZE=true` and all the REMOVE/RESTORE options set to false to do just that.

**Comment by smithcg02** [comment]
That seems to have done the trick, for now.
Both the GroupReadsByUmi and CallMolecularConsensusReads commands have worked, in as much as the commands have completed without any errors!
I'll have a look at interpreting the output
Thanks very much for your help!

**Comment by smithcg02** [comment]
Dear @tfenne
Me again.
I can see that the collapsed bam (as output by CallMolecularConsensusReads command) contains my reads but they don’t seem to have location information (no chromosome, start, end, etc). Is this what you’d expect of the command (if so, do you know how I might go about adding it?) or am I still doing something wrong?

An example of a line from my bam is copied here;

SLX-11341_A002:100      77      *       0       0       *       *       0       0       ACCCATCCCCGAGCCCAGTACCCAGCCTCCAGCCCAGTACCCATCCCCAAGCCCAGTACCCAGCCCCGAGCCCAGTACTCCACGACGCCGAAGGGCCGGGTCCTGCCTCCAGGGCTGAGCACCTT   D71:B?8??96D??CCCC@=??ADCCCDA<CCCC>BCCA?CCFCCCDCDC@A>DFAA>:DC>@@?AD86>@D@9AD9=C?B3>8FA<BB7@8??AFA35>?CCAHHBC;<73E?DB?:;EIAA>2   RG:Z:A  MI:Z:100

Of note, I have also used the –r option to write reads that aren’t used to a separate bam. The reads in this file DO contain location info

D00408:358:C8KK0ANXX:7:1206:9905:75008  83      chr1    10011   47      111M1I13M       =       10001   -134    CCTCACCCTACCCCTAACCCTAACCCTAACCCTACCCCTAACCCTAACCCTAACCCTAACCCTAACGCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAGCCCCTAATCCTAA   4040/>762/)8:5,4.)/7734:75,+-<7677(<96387<<;677;;673-;95587;;63641+9:;6;:;::::;:9;;:::5868::9:599677::99:::::9;:::;:989:;;990   MC:Z:16S104M5S  BD:Z:GFGEGFIIHFEEHHEEFDGGDDEDGGCDDDGGEEDDGFDDEDGGCDEDGGCDEDGGDDDDGGDCEFGFDDEDFFCDEDGGDDECFFCCDCFFCCDCECCDCFFCBDCFFDGGDDGGEFGGIGDDD      PG:Z:MarkDuplicates

     RG:Z:SLX-11341_A002     BI:Z:JIJGKHKKJJHHKKIHJHKKIHJHKKIGIHKKJIGGJJHGIGJJGGHGJJHGHGIIGGIFJJHFIHJIGGIEJJHGHFJIGFGGIJHGIFHIFFHFFGGHFIJHGIFJIGKHGGJJHFIFJJHHH      MI:Z:0  NM:i:7  MQ:i:30 AS:i:92 XS:i:82 RX:Z:GTTGTAACC

Thanks and best wishes
@smithcg02

**Comment by nh13** [comment]
@smithcg02 this is what we would expect, namely no mapping information in the consensus reads.  Therefore, you should map the consensus reads for any downstream analysis that requires it.

The motivation to output unmapped reads include but are not limited to:

1. Specifying the "right" mapped information is challenging from a set of input reads that have mapping information, especially with corner cases like indels or clipping.  We'd rather re-run it through the mapping tool to get the right information, and usually the # of reads are reduced, so it is not too computationally expensive.
2. The data into the tool does not need to have any mapping information, since the tool only assumes that the reads with the same molecular tag are grouped together. 

Hopefully that helps!

**Comment by nh13** [comment]
@smithcg02 closing this, please open a new issue if you encounter any other issues.  Thanks for reporting!
