### ISSUE TITLE
anyway to indentify the consensus reads with umi group size = 1 in the consensus fastq gz file (set min group size == 1) in umi process

### ISSUE THREAD

**Issue by linuxbioinfoguy** [fulcrumgenomics/fgbio#872]
Hi, I have the following situation, if I set the min umi group size == 1 in the umi process, is there anyway I can filter the final consensus fastq output by a further defined umi group size, for example, in the final consensus fastq, I want to extract only the consensus sequence with umi size >=2, is that possible.

Thanks!

**Comment by nh13** [comment]
Use [`FilterConsensusReads`](http://fulcrumgenomics.github.io/fgbio/tools/latest/FilterConsensusReads.html) on the consensus BAM to select consensus reads with a minimum # of reads with `--min-reads` (actual value(s) differs based on if you have duplex or non-duplex data).
