### ISSUE TITLE
Add UMIs to fastq

### ISSUE THREAD

**Issue by migrau** [fulcrumgenomics/fgbio#873]
I have my UMIs in an additional FASTQ file, containing only the UMIs:

```
@A00154:125:HGKTMDMXX:1:1101:10420:1000 2:N:0:AACTGAGG+ATGCGTC   
GCGCGT   
+   
FFFFFF   
```

I'm doing the UMIs calling using `AnnotateBamWithUmis` to include the UMIs in the RX tag after the alignment, but it is quite memory demanding so I was instead considering to start using `FastqToBam` at the begging of the pipeline. Is it a good idea adding my UMIs sequences to one of my paired fastq files (to R2 for example should is enough), and use `FastqToBam`?

**Comment by nh13** [comment]
Do you have the UMIs in a FASTQ already? If so, you can use FastqToBam directly.

**Comment by migrau** [comment]
Yes, I have two fastq files (R1, R2) + another fastq only with UMIs. The paired fastq contains the sequences without barcodes, indexes etc. Would it be correct?
`--input r1.fq r2.fq umi.fq --read-structures +T +T +M`

I realized that Sarek is using the fgbio pipe for UMIs, but it looks like the only way to use it is having the UMIs in the fastq reads, right? https://nf-co.re/sarek/usage#how-to-handle-umis

**Comment by nh13** [comment]
@migrau the above command looks right to me.   I haven't used `sarek`, so you'd need to see how FastqToBam is being used there.
