### ISSUE TITLE
CorrectUmis metrics file: extra line with Ns

### ISSUE THREAD

**Issue by gshiba** [fulcrumgenomics/fgbio#875]
There is a line in `CorrectUmis`'s metrics file (from `-M` flag) where the umi sequence is Ns. What does this line represent?

Usage: `fgbio CorrectUmis -i ... -o ... -m 0 -d 1 -M metrics.txt -U umis.txt`

We have `y` lines in `umis.txt`, but there are `y+1(header)+1(the Ns)` lines in `metrics.txt`.

Thanks!

**Comment by nh13** [comment]
Take a look at the documentation for [`UmiCorrectionMetrics`](http://fulcrumgenomics.github.io/fgbio/metrics/latest/#umicorrectionmetrics).  The `umi` column says:

> The corrected UMI sequence (or all Ns for unmatched).

So the all Ns is for all reads that could not be corrected.

**Comment by gshiba** [comment]
Thank you. I didn't know (or had forgotten) about this metrics page.
