### ISSUE TITLE
Zipperbams error:

### ISSUE THREAD

**Issue by gevro** [fulcrumgenomics/fgbio#888]
Hi,
I'm following the best practices exactly, but receiving a Warning from Zipper bams at the below step: "#Duplex consensus unmapped BAM -> Duplex consensus mapped BAM"

Warning:
```
[2022/11/24 13:00:29 | FgBioMain | Info] Executing ZipperBams from fgbio version 2.0.2 as g01@cn-0007 on JRE 17.0.2+8 with snappy, IntelInflater, and IntelDeflater
[2022/11/24 13:00:29 | ZipperBams | Warning] input file /dev/stdin does not appear to be queryname sorted or grouped.
[2022/11/24 13:00:29 | ZipperBams | Warning] Continuing, but your output may be incorrect.
```

Pipeline:
```
#Fastq -> uBam
sbatch -t 300 --mem=4G -c 4 --wrap "java -Xmx1g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io FastqToBam --input BS18870A_R1_000.fastq.gz BS18870A_R2_000.fastq.gz --read-structures 3M2S+T 3M2S+T --sample BS18870A --library BS18870A --output BS18870A.unmapped.bam"

#uBam -> Mapped BAM
sbatch -t 300 --mem=32G -c 16 --wrap "samtools fastq BS18870A.unmapped.bam | bwa mem -t 12 -p -K 150000000 -Y ~/lab/reference-files/mm10/mm10.fa - | java -Xmx4g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io ZipperBams --unmapped BS18870A.unmapped.bam --ref ~/lab/reference-files/mm10/mm10.fa --output BS18870A.mapped.bam"

#Mapped BAM -> Grouped BAM
sbatch -t 300 --mem=16G -c 4 --wrap "java -Xmx8g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io GroupReadsByUmi --input BS18870A.mapped.bam --strategy paired --edits 1 --output BS18870A.grouped.bam --family-size-histogram BS18870A.tag-family-sizes.txt"

#Grouped BAM -> Duplex consensus unmapped BAM
sbatch -t 300 --mem=16G -c 4 --wrap "java -Xmx8g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 CallDuplexConsensusReads --input BS18870A.grouped.bam --output BS18870A.collapsed_unaligned.bam --min-reads 4 2 2 --threads 4"

#Duplex consensus unmapped BAM -> Duplex consensus mapped BAM
sbatch -t 300 --mem=16G -c 8 --wrap "samtools fastq BS18870A.collapsed_unaligned.bam | bwa mem -t 6 -p -K 150000000 -Y ref.fa - | java -Xmx8g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io ZipperBams --unmapped BS18870A.collapsed_unaligned.bam --ref ~/lab/reference-files/mm10/mm10.fa --tags-to-reverse Consensus --tags-to-revcomp Consensus --output BS18870A.collapsed_aligned.bam"
```

**Comment by gevro** [comment]
Nevermind I found the error. Wrong parameter for ref.fa.

**Comment by gevro** [comment]
I thought I found the error, but even after correcting the ref.fa parameter, I still see the Warning. Is this an expected warning?

```
#Fastq -> uBam
sbatch -t 300 --mem=4G -c 4 --wrap "java -Xmx1g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io FastqToBam --input BS18870A_R1_000.fastq.gz BS18870A_R2_000.fastq.gz --read-structures 3M2S+T 3M2S+T --sample BS18870A --library BS18870A --output BS18870A.unmapped.bam"

#uBam -> Mapped BAM
sbatch -t 300 --mem=32G -c 16 --wrap "samtools fastq BS18870A.unmapped.bam | bwa mem -t 12 -p -K 150000000 -Y ~/lab/reference-files/mm10/mm10.fa - | java -Xmx4g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io ZipperBams --unmapped BS18870A.unmapped.bam --ref ~/lab/reference-files/mm10/mm10.fa --output BS18870A.mapped.bam"

#Mapped BAM -> Grouped BAM
sbatch -t 300 --mem=16G -c 4 --wrap "java -Xmx8g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io GroupReadsByUmi --input BS18870A.mapped.bam --strategy paired --edits 1 --output BS18870A.grouped.bam --family-size-histogram BS18870A.tag-family-sizes.txt"
#Grouped BAM -> Duplex consensus unmapped BAM
sbatch -t 300 --mem=16G -c 4 --wrap "java -Xmx8g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 CallDuplexConsensusReads --input BS18870A.grouped.bam --output BS18870A.collapsed_unaligned.bam --min-reads 4 2 2 --threads 4"

#Duplex consensus unmapped BAM -> Duplex consensus mapped BAM
sbatch -t 300 --mem=16G -c 8 --wrap "samtools fastq BS18870A.collapsed_unaligned.bam | bwa mem -t 6 -p -K 150000000 -Y ~/lab/reference-files/mm10/mm10.fa - | java -Xmx8g -jar ~/lab/bin/fgbio/fgbio-2.0.2.jar --compression 1 --async-io ZipperBams --unmapped BS18870A.collapsed_unaligned.bam --ref ~/lab/reference-files/mm10/mm10.fa --tags-to-reverse Consensus --tags-to-revcomp Consensus --output BS18870A.collapsed_aligned.bam"
```

**Comment by gevro** [comment]
Note: this Warning happens even if I do 'samtools sort -n' to the duplex consensus bam before the mapping step.

And it also still happens if I run CallDuplexConsensusReads with the '--sort-order=Queryname' option.

So even if I query sort the BAM file input into the mapping step (samtools fastq | bwa mem | ZipperBams) still gives the Warning.

**Comment by tobyaicher** [comment]
Hi,

I wanted to follow-up on this issue as I am also interested in the answer.

Thanks

**Comment by nh13** [comment]
No progress has been made on this, feel free to reach out to us if you want to sponsor our work so it is prioritized.

**Comment by esamorodnitsky** [comment]
@gevro I use the gatk4 function SortSam with the flag --SORT_ORDER queryname. Maybe this will hep you.

**Comment by gevro** [comment]
Thanks! I'm assuming 'samtools sort -n' would work too?

Regardless, this should be added to the best practices then.

**Comment by esamorodnitsky** [comment]
> Thanks! I'm assuming 'samtools sort -n' would work too?
> 
> Regardless, this should be added to the best practices then.

Maybe. I don't know. I haven't tried. Let me know how it works for you.

**Comment by gevro** [comment]
Actually I forgot since it's been a while that I already tried samtools sort -n, and it doesn't work.

Quote from prior message:
"Note: this Warning happens even if I do 'samtools sort -n' to the duplex consensus bam before the mapping step.

And it also still happens if I run CallDuplexConsensusReads with the '--sort-order=Queryname' option.

So even if I query sort the BAM file input into the mapping step (samtools fastq | bwa mem | ZipperBams) still gives the Warning."

You don't see the warning with SortSam? If so, it must be some tag in SortSam that 'samtools sort -n' and 'CallDuplexConsensusReads with the '--sort-order=Queryname' option' do not do.

Definitely seems like a bug in ZipperBams to me.

**Comment by esamorodnitsky** [comment]
I run the SortSam step twice before running gatk4's MergeBamAlignment, but I haven't tried ZipperBams. Here are my steps:

gatk4 --java-options "-Xmx39g" SortSam --INPUT concensusUnmapped_UMI.bam --OUTPUT concensusUnmapped_UMI.qry_sorted.bam --SORT_ORDER queryname

gatk4 --java-options "-Xmx39g" SortSam --INPUT cns_mem.bam --OUTPUT cns_mem.qry_sorted.bam --SORT_ORDER queryname

Then, I run gatk4's MergeBamAlignment command, but you can see if this works with ZipperBams.
