### ISSUE TITLE
Specific reads used for each consensus sequence

### ISSUE THREAD

**Issue by karlbeutner** [fulcrumgenomics/fgbio#892]
Hello, I am working on an analysis that requires knowing exactly which reads in a "raw"/"umi" bam file were used to create each consensus read output from [CallDuplexConsensusReads](http://fulcrumgenomics.github.io/fgbio/tools/latest/CallDuplexConsensusReads.html). 

I tried reading through the umi bam and consensu bam file while using the RX, aD, bD, and cD tags to re-group the umi reads myself. It looks like the algorithm fgbio uses is a bit complex, and I am hoping to not have to re-implement or approximate it myself as I think that will be error prone and buggy.

Is there an existing tool I can use to see exactly which read(s) in the umi bam files were used to create each read in the consensus bam file?

Thank you

**Comment by nh13** [comment]
@karlbeutner I believe that the consensus read pair and raw reads should share the same `MI` tag.  For duplex reads there will be a trailing `/A` and `/B` as per: https://github.com/fulcrumgenomics/fgbio/wiki/Developer-Note:-Tracking-Reads-through-Grouping-and-Duplex-Consensus-Calling

**Comment by karlbeutner** [comment]
THank you @nh13. I didn't see the MI tag in the umi file because I was looking at the wrong one from our pipeline. I have generated the appropriate file, and can see the expected MI tags. Sorry the silly question.
