### ISSUE TITLE
How does CallDuplexConsensusReads handle homopolymers?

### ISSUE THREAD

**Issue by karlbeutner** [fulcrumgenomics/fgbio#895]
I am analyzing heterogeneity of homopolymer lengths in my paired-end sequencing reads. 

In some cases I can see that half of the raw reads with the same `MI` have one homopolymer length (say 14), but the other half of the reads with that same `MI` have another length (say 15). I expect there to be zero heterogenity of the homopolymer length amongst reads with the same `MI` tag value, so I know that all the heterogenity I see is noise (probably from library prep and/or sequencing polymerase errors).

How does `CallDuplexConsensusReads` assign a consensus homopolymer length (sequence) when the underlying reads provide equally good evidence for two different values?

I worry that since I do not do an indel re-alignment on the raw UMI bam file (mostly because it would be so computationally expensive to do so. Currently that is done down-stream on the consensus bam file), the alignment may spread the deletions over many positions and the resulting consensus sequences end up with homopolymers that are too long. Is this an already tested or known issue?

**Comment by nh13** [comment]
1. You can read through how reads from the same molecule are called, paying close attention to the "cigar-filtering" section: https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Duplex-Consensus-Reads#cigar-filtering.  
2. We explored the possibility of using multiple-sequence-alignment to better call consensus reads from raw reads with homopolymer length differences, in particular for STRs where PCR stutter is an issues.  It did help a little, but we did not pursue it any further. See: https://github.com/fulcrumgenomics/fgstr.
3. We'd welcome working on the project, but are prioritizing client work ([contact us](https://fulcrumgenomics.com/) if you're interested)

**Comment by karlbeutner** [comment]
Thank you @nh13! I will look more closely at the work you linked.
