### ISSUE TITLE
CallMolecularConsensusReads with multiple threads causing a core dump

### ISSUE THREAD

**Issue by esamorodnitsky** [fulcrumgenomics/fgbio#900]
When I was running CallMolecularConsensusReads with one thread, it worked fine, however with multiple threads, I am getting a core dump.

-bash-4.2$ java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)

-bash-4.2$ java -jar /fs/project/PAS0854/Software/fgbio_2.1.0/target/scala-2.13/fgbio-2.1.1-58a45a4-SNAPSHOT.jar CallMolecularConsensusReads --min-reads=3 -i input.bam -r rejected.bam --min-input-base-quality=30 --read-group-id=osu_illumina -o output_concensusUnmapped_UMI.bam --threads=2
[2023/02/02 16:14:31 | FgBioMain | Info] Executing CallMolecularConsensusReads from fgbio version 2.1.1-58a45a4-SNAPSHOT as osu7224@owens-login03.hpc.osc.edu on JRE 1.8.0_352-b08 with snappy, IntelInflater, and IntelDeflater

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x00002b337c7832a8, pid=6184, tid=0x00002b3405adc700

 JRE version: OpenJDK Runtime Environment (8.0_352-b08) (build 1.8.0_352-b08)
 Java VM: OpenJDK 64-Bit Server VM (25.352-b08 mixed mode linux-amd64 compressed oops)
 Problematic frame:
 C  [libz.so.1+0x42a8]  deflateReset+0x38

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /fs/ess/PAS0854/Eric/Test/All_one_lane1_para/Consensus_BAM_min3/hs_err_pid6184.log

 If you would like to submit a bug report, please visit:
   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

**Comment by nh13** [comment]
Can you try updating your java (newer version 8, or try 11 or 17).

**Comment by esamorodnitsky** [comment]
I tried java/12.0.2. Same thing happened.

**Comment by nh13** [comment]
I think the only thing we can do is to try to recreate, for which we'd need all the inputs to run.

**Comment by esamorodnitsky** [comment]
Do you have an sftp or scp or something so I can send you my fastqs?

**Comment by nh13** [comment]
I do not, I am sorry.

**Comment by nh13** [comment]
Also note we are extremely booked with client work, so I am not sure I would be able to look in any reasonable amount of time.  Consider installing via conda or run in a docker container to see if you can run it that way.  Debugging seg-faults because of the JVM is very tough and a little beyond the scope of maintaining this repo through volunteer time.
