### ISSUE TITLE
Does CallDuplexConsensusReads require overlapping read pairs?

### ISSUE THREAD

**Issue by mulderdt** [fulcrumgenomics/fgbio#903]
Hello,

Our process right now is for low depth : fgbio GroupReadsByUmi | CallMolecularConsensusReads | FilterConsensusReads
Our process right now is for high depth : fgbio GroupReadsByUmi | CallDuplexConsensusReads | FilterConsensusReads

Our reads right now are mostly overlapping PE150 with insert sizes of ~200bp.

We are wondering if we move to shorter read lengths e.g. PE75 or PE100 and have little overlap between R1 and R2 whether fgbio CallDuplexConsensusReads is possible?

The documentation states that "read pairs for which consensus reads cannot be generated dfor one or other read (R1 or R2) are omitted from the output".

Am I correct in my interpretation then that fgbio CallDuplexConsensusReads cannot be run on a paired UMI paired end high coverage data set where the R1 and R2 have little to no overlap?

Thank you for your time.

**Comment by nh13** [comment]
I am unclear on how if you truly have duplex sequencing data when using `CallDuplexConsensusReads`.  If you do, why are you using `CallMolecularConsensusReads` when you have duplex sequencing data?

I am also confused by your insert size comment and overlap comment.  The `CallDuplexConsensusReads` and `CallMolecularConsensusReads` are used when you have UMIs that help identify templates (read pairs) that sequence the same source molecule.  So you have good coverage of each molecule with multiple reads, producing a consensus (read pair) per molecule.  For duplex sequencing data, you can identify on which strand of the source molecule each read pair belongs.

On the other hand, sounds like you might be trying to leverage the short inserts to call a consensus sequence within the overlap in each read pair?   In that case, why not use `CallOverlappingConsensusBases`?   I don't see the purpose of the other two tools in this case.  

But you must have UMIs if you're using `GroupReadsByUmi`, so I am very confused about what actual sample/library prep protocol you're using.  Can you explain?

**Comment by mulderdt** [comment]
I am sorry I was not clear. We are indeed using paired UMIs and using `bcbio-nextgen` to call `fgbio`. But it looks like our bam file RX tags were not encoding both UMIs properly so `CallMolecularConsensusReads` was being utilitized instead of `CallDuplexConsensusReads`.

I think I also had a misunderstanding around how R1 and R2 reads are associated with the template strand in our process and used in the consensus strand building. I think I have it figured out now. Thank you.
