### ISSUE TITLE
GroupReadsByUmi Error - multiple non-secondary, non-supplemental R1s 

### ISSUE THREAD

**Issue by saradunaj** [fulcrumgenomics/fgbio#904]
Hi. I ran the following with your GroupReadsByUmi package via Conda:

fgbio GroupReadsByUmi -s Paired -i Dups.Marked.bam -o groupedBam -t RX"

This is the error I got towards the end of running the tool:

2023/03/08 16:50:49 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 31.79 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: Multiple non-secondary, non-supplemental R1s for ...

[2023/03/08 16:50:49 | FgBioMain | Info] GroupReadsByUmi failed. Elapsed time: 31.79 minutes.
Exception in thread "main" java.lang.IllegalArgumentException: Multiple non-secondary, non-supplemental R1s for VH01033:7:AAC22LYH
V:1:2210:76003:35663:TAA+ACT
	at com.fulcrumgenomics.bam.Template$.$anonfun$apply$2(Bams.scala:155)
	at com.fulcrumgenomics.bam.Template$.$anonfun$apply$2$adapted(Bams.scala:147)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator$$anon$1.foreach(BetterBufferedIterator.scala:61)
	at com.fulcrumgenomics.bam.Template$.apply(Bams.scala:147)
	at com.fulcrumgenomics.bam.Template$.apply(Bams.scala:133)
	at com.fulcrumgenomics.bam.Bams$$anon$1.next(Bams.scala:314)
	at com.fulcrumgenomics.bam.Bams$$anon$1.next(Bams.scala:310)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.maybeNext(BetterBufferedIterator.scala:45)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.$anonfun$next$2(BetterBufferedIterator.scala:54)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen(CommonsDef.scala:72)
	at com.fulcrumgenomics.commons.CommonsDef.yieldAndThen$(CommonsDef.scala:70)
	at com.fulcrumgenomics.commons.CommonsDef$.yieldAndThen(CommonsDef.scala:440)
	at com.fulcrumgenomics.commons.collection.BetterBufferedIterator.next(BetterBufferedIterator.scala:54)
	at com.fulcrumgenomics.commons.collection.SelfClosingIterator.next(SelfClosingIterator.scala:46)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.takeNextGroup(GroupReadsByUmi.scala:653)
	at com.fulcrumgenomics.umi.GroupReadsByUmi.execute(GroupReadsByUmi.scala:611)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSo(FgBioMain.scala:124)
	at com.fulcrumgenomics.cmdline.FgBioMain.makeItSoAndExit(FgBioMain.scala:99)
	at com.fulcrumgenomics.cmdline.FgBioMain$.main(FgBioMain.scala:50)
	at com.fulcrumgenomics.cmdline.FgBioMain.main(FgBioMain.scala)

What does this error mean and how do I correct for this error?

Thank you

**Comment by nh13** [comment]
Can you take a look at the records in your BAM with  with name `VH01033:7:AAC22LYH` and check to see if you have multiple primary R1 records (see [explain flags](https://broadinstitute.github.io/picard/explain-flags.html))?  Likely there is an issue with your input BAM having two or more R1 records for that read that are marked as "primary".  You can run `picard ValidateSam` to confirm.  Likely you had an issue in your mapping step where the reads were treated as fragment reads rather than paired (e.g. not using `bwa mem`'s `-p` option).

**Comment by saradunaj** [comment]
Thank you for your time and help with this. Here is a snapshot of the bam records:

`VH01033:7:AAC22LYHV:1:1107:28513:19989:GAA+AAG	99	1	183026	0	94M5S	=	183026	94	GGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGACTT	CCCCCCCCCCCCCCCCCCCCCCCCCCCC-CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	MC:Z:5S94M	MD:Z:94	RG:Z:A	NM:i:0	MQ:i:0	UQ:i:0	AS:i:95	RX:Z:GAA-AAG
VH01033:7:AAC22LYHV:1:1108:50441:17376:TTA+CCT	99	1	183026	0	146M	=	183148	268	GGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGTCTCCCCCCAGGTGTGTGGTGATGCCAGGCATGCCCTTCCCCAGCATCAGG	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC	MC:Z:146M	MD:Z:146	RG:Z:A	NM:i:0	MQ:i:0	UQ:i:0	AS:i:146	RX:Z:TTA-CCT
VH01033:7:AAC22LYHV:1:1109:25218:1814:GAG+ACC	163	1	183026	0	146M	=	183149	269	GGGAGGGGCAGAGCCGCAGGCACAGCCAAGAGGGCTGAAGAAATGGTAGAACGGAGCAGCTGGTGATGTGTGGGCCCACCGGCCCCAGGCTCCTGTCTCCCCCCAGGTGTGTGGTGATGCCAGGCATGCCCTTCCCCAGCATCAGG	CCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC;CCCCCCCC;CCCCCCCCCCCCCCCCCC--CCCCCCCCC	MC:Z:146M	MD:Z:146	RG:Z:A	NM:i:0	MQ:i:0	UQ:i:0	AS:i:146	RX:Z:GAG-ACC
VH01033:7:AAC22LYHV:1:^`

I ran BWA MEM with the -M option for use with Picard  UMI aware mark duplicates (https://gatk.broadinstitute.org/hc/en-us/articles/360037593651-UmiAwareMarkDuplicatesWithMateCigar-Picard-EXPERIMENTAL-)

Is this causing the issue? As I need to run both group reads by UMI after I mark duplicates.

Thank you

**Comment by saradunaj** [comment]
It is still running and I expect it will for awhile longer, as this is from a deeply sequenced sample. Here is some output so far:
`[Thu Mar 09 16:37:37 UTC 2023] ValidateSamFile INPUT=FANCF1_Agi_S1_L001.merged.merged.markedDup.bam MODE=SUMMARY    MAX_OUTPUT=100 IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE IS_BISULFITE_SEQUENCED=false MAX_OPEN_TEMP_FILES=8000 SKIP_MATE_VALIDATION=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Thu Mar 09 16:37:37 UTC 2023] Executing as sdunaj@ip-10-32-254-33.ec2.internal on Linux 4.14.262-200.489.amzn2.x86_64 amd64; OpenJDK 64-Bit Server VM 1.8.0_332-b09; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.27.5
WARNING 2023-03-09 16:37:37     ValidateSamFile NM validation cannot be performed without the reference. All other validations will still occur.
INFO    2023-03-09 16:38:24     SamFileValidator        Validated Read    10,000,000 records.  Elapsed time: 00:00:46s.  Time for last 10,000,000:   46s.  Last read position: 1:34,787,513
INFO    2023-03-09 16:39:10     SamFileValidator        Validated Read    20,000,000 records.  Elapsed time: 00:01:32s.  Time for last 10,000,000:   45s.  Last read position: 1:119,969,657
INFO    2023-03-09 16:39:56     SamFileValidator        Validated Read    30,000,000 records.  Elapsed time: 00:02:18s.  Time for last 10,000,000:   46s.  Last read position: 1:200,956,203
INFO    2023-03-09 16:40:44     SamFileValidator        Validated Read    40,000,000 records.  Elapsed time: 00:03:06s.  Time for last 10,000,000:   47s.  Last read position: 2:27,657,278
INFO    2023-03-09 16:41:30     SamFileValidator        Validated Read    50,000,000 records.  Elapsed time: 00:03:53s.  Time for last 10,000,000:   46s.  Last read position: 2:130,010,201
INFO    2023-03-09 16:42:17     SamFileValidator        Validated Read    60,000,000 records.  Elapsed time: 00:04:40s.  Time for last 10,000,000:   46s.  Last read position: 3:9,297,636
INFO    2023-03-09 16:43:04     SamFileValidator        Validated Read    70,000,000 records.  Elapsed time: 00:05:26s.  Time for last 10,000,000:   46s.  Last read position: 3:76,064,100
INFO    2023-03-09 16:43:50     SamFileValidator        Validated Read    80,000,000 records.  Elapsed time: 00:06:13s.  Time for last 10,000,000:   46s.  Last read position: 4:1,978,616
INFO    2023-03-09 16:44:36     SamFileValidator        Validated Read    90,000,000 records.  Elapsed time: 00:06:58s.  Time for last 10,000,000:   45s.  Last read position: 4:163,037,920
INFO    2023-03-09 16:45:22     SamFileValidator        Validated Read   100,000,000 records.  Elapsed time: 00:07:45s.  Time for last 10,000,000:   46s.  Last read position: 5:139,002,079
INFO    2023-03-09 16:46:09     SamFileValidator        Validated Read   110,000,000 records.  Elapsed time: 00:08:32s.  Time for last 10,000,000:   46s.  Last read position: 6:73,618,007
INFO    2023-03-09 16:46:57     SamFileValidator        Validated Read   120,000,000 records.  Elapsed time: 00:09:19s.  Time for last 10,000,000:   47s.  Last read position: 7:1,861,318
INFO    2023-03-09 16:47:43     SamFileValidator        Validated Read   130,000,000 records.  Elapsed time: 00:10:05s.  Time for last 10,000,000:   46s.  Last read position: 7:102,491,115
INFO    2023-03-09 16:48:29     SamFileValidator        Validated Read   140,000,000 records.  Elapsed time: 00:10:52s.  Time for last 10,000,000:   46s.  Last read position: 7:153,560,812
INFO    2023-03-09 16:49:16     SamFileValidator        Validated Read   150,000,000 records.  Elapsed time: 00:11:38s.  Time for last 10,000,000:   46s.  Last read position: 8:126,551,568
INFO    2023-03-09 16:50:03     SamFileValidator        Validated Read   160,000,000 records.  Elapsed time: 00:12:25s.  Time for last 10,000,000:   47s.  Last read position: 9:110,293,920
INFO    2023-03-09 16:50:51     SamFileValidator        Validated Read   170,000,000 records.  Elapsed time: 00:13:13s.  Time for last 10,000,000:   47s.  Last read position: 10:50,010,096
INFO    2023-03-09 16:51:36     SamFileValidator        Validated Read   180,000,000 records.  Elapsed time: 00:13:59s.  Time for last 10,000,000:   45s.  Last read position: 10:128,142,556
INFO    2023-03-09 16:52:23     SamFileValidator        Validated Read   190,000,000 records.  Elapsed time: 00:14:46s.  Time for last 10,000,000:   47s.  Last read position: 11:92,801,774
INFO    2023-03-09 16:53:11     SamFileValidator        Validated Read   200,000,000 records.  Elapsed time: 00:15:33s.  Time for last 10,000,000:   47s.  Last read position: 12:52,450,365
INFO    2023-03-09 16:53:57     SamFileValidator        Validated Read   210,000,000 records.  Elapsed time: 00:16:19s.  Time for last 10,000,000:   45s.  Last read position: 12:132,856,801
INFO    2023-03-09 16:54:44     SamFileValidator        Validated Read   220,000,000 records.  Elapsed time: 00:17:07s.  Time for last 10,000,000:   47s.  Last read position: 14:21,569,270
INFO    2023-03-09 16:55:31     SamFileValidator        Validated Read   230,000,000 records.  Elapsed time: 00:17:53s.  Time for last 10,000,000:   46s.  Last read position: 15:40,859,943
`

**Comment by nh13** [comment]
You can use `fgbio ZipperBams` instead of `picard MergeBamAlignment` too.

**Comment by saradunaj** [comment]
How fgbio ZipperBams help with running GroupReadsByUMI?  

What is the best way to prep my markedduplicate bam file for running GroupReadsbyUMI based on the errors reported from ValidateSamFile?

## HISTOGRAM    java.lang.String Error Type      Count ERROR:MATES_ARE_SAME_END        19020 ERROR:MISMATCH_FLAG_MATE_NEG_STRAND     75350 ERROR:MISMATCH_FLAG_MATE_UNMAPPED       112668 ERROR:MISMATCH_MATE_CIGAR_STRING        71354

**Comment by nh13** [comment]
@saradunaj 

1. You can use fgbio ZipperBams instead of picard MergeBamAlignment too.  Did you try that?
2. Did you try removing the "-M" option?

I am sorry I am unable to help more, please speak with your manager, team, or advisor to get some more help.
