### ISSUE TITLE
Should we make a recipe for fgbio in homebrew?

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgbio#91]
It probably belongs in [homebrew-science](https://github.com/Homebrew/homebrew-scienc).  See the [contributing  guide](https://github.com/Homebrew/homebrew-science/blob/master/.github/CONTRIBUTING.md).

```
class Fgbio < Formula
  desc "Tools for working with genomic and high throughput sequencing data."
  homepage "https://github.com/fulcrumgenomics/fgbio"
  url "https://github.com/fulcrumgenomics/fgbio/archive/0.1.1.tar.gz"
  sha256 "4b2414ab8af5e8cfa384cde44fc9a282cec83c51cd93efe0113866dc2840e696"

  head do
    url "https://github.com/fulcrumgenomics/fgbio.git"
  end

  bottle :unneeded

  depends_on :java => "1.8+"
  depends_on "sbt" => :build

  def install
    system "sbt", "assembly"
    libexec.install Dir["target/scala-*/fgbio-*.jar"][0]
    bin.write_jar_script Dir[libexec/"fgbio-*.jar"][0], "fgbio"
  end

  test do
    assert_match "USAGE", shell_output("#{bin}/fgbio -h 2>&1", 1)
  end
end
```

**Comment by chapmanb** [comment]
As a heads up, I created a conda recipe for bioconda (https://bioconda.github.io/) with the latest development version (https://anaconda.org/bioconda/fgbio).

**Comment by tfenne** [comment]
@nh13 I think we should close this as bioconda is probably the better place and @chapmanb has already hooked us up.  What do you think?
