### ISSUE TITLE
families vs groups

### ISSUE THREAD

**Issue by LeilyR** [fulcrumgenomics/fgbio#919]
Hi, I am working with bam files with RX tags like this: `RX:Z:AAAGT-CGTGT` where each barcode is at the end of a read in a pair. So I assume this is what is called `duplex`. I have used grouping with `--paired` as suggested in your documentation and saved the family size text file as well. I will get about 80 family of reads, which is way less than the number of MI tags I get in the bam files that represents the number of groups. I have tried to find this out in your documentation but did not find a place where I could see how groups are gathered together in a single family. Could please help me wit that. Thanks!

**Comment by nh13** [comment]
Please see the usage for GroupReadsByUmi: http://fulcrumgenomics.github.io/fgbio/tools/latest/GroupReadsByUmi.html

If you’d like further help, we offer our services here:
https://fulcrumgenomics.com/
