### ISSUE TITLE
DemuxFastqs --omit-failing-reads opposite expected behavior.

### ISSUE THREAD

**Issue by gouinK** [fulcrumgenomics/fgbio#922]
Hi all,

I attempted to use the `DemuxFastqs` function with the `--omit-failing-reads` flag set, and I noticed that it outputs reads that have the chastity flag set to `Y`, however I believe the expected behavior is to output reads that have the chastity flag set to `N`. 

It seems like in the original PR https://github.com/fulcrumgenomics/fgbio/pull/713 that added this feature, the intended behavior was indeed to output reads with chastity flag set to `Y`, so perhaps there was just a misunderstanding about what the `Y` vs `N` means. Based on Illumina's [documentation](https://support.illumina.com/help/BaseSpace_OLH_009008/Content/Source/Informatics/BS/FileFormat_FASTQ-files_swBS.htm) when the flag is set to `Y` it means that the read _failed_ filtering. 

Maybe I am mis-interpreting the meaning of the `--omit-failing-reads` flag?

Thanks for your time!

**Comment by nh13** [comment]
@gouinK I think you're right, and here's the offending line: https://github.com/fulcrumgenomics/fgbio/blob/e197ce44233c4a6dcbbb8d9f5da6102cd4209e75/src/main/scala/com/fulcrumgenomics/fastq/DemuxFastqs.scala#L916

As a heads up, most of the work on FASTQ demultiplexing has moved over to [`fqtk`](https://github.com/fulcrumgenomics/fqtk), though we do not intend to port over all options like this one (or BAM output support; use `samtools import`).  It should be MUCH faster for you.

**Comment by gouinK** [comment]
Thanks for the clarification and the tip on the new tool!

**Comment by nh13** [comment]
Fixed in #923
