### ISSUE TITLE
Add tag to store barcode quality in sam for FastqToBam

### ISSUE THREAD

**Issue by galaxy001** [fulcrumgenomics/fgbio#931]
In `FastqToBam`, there is "--umi-qual-tag" for UMI quality. However, there is no option to save barcode quality to tag.
Please add as STAR require quality input at <https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md#input-reads-from-bam-files>.

**Comment by nh13** [comment]
Seems like a great first issue if you want to help implement the feature and add a unit test or two!

**Comment by galaxy001** [comment]
Checked #932 with `sbt test`, and all tests passed.

**Comment by nh13** [comment]
Done in #933!
