### ISSUE TITLE
add --barcode to FastqToBam ?

### ISSUE THREAD

**Issue by bwlang** [fulcrumgenomics/fgbio#935]
right now the docs show:
`--platform-unit=String        Platform unit (e.g. <flowcell-barcode>.<lane>.<sample-barcode>`

I think that does not match with the[ sam spec](https://samtools.github.io/hts-specs/SAMv1.pdf):

> Platform unit (e.g., flowcell-barcode.lane for Illumina or slide for SOLiD). Unique identifier.
which does not say anything about sample barcode

Instead I think sample-barcode should go to the BC tag instead, but there is no option for that.

> Barcode sequence identifying the sample or library. This value is the expected barcode bases
as read by the sequencing machine in the absence of errors. If there are several barcodes for
the sample/library (e.g., one on each end of the template), the recommended implementation
concatenates all the barcodes separating them with hyphens (‘-’).

Would a PR for that be merged quickly?

**Comment by nh13** [comment]
The `PU` (platform-unit) tag need only be a unique identifier.  I don't see anything in the code or usage that disagrees with the SAM spec.  I don't see anything in the usage that talks about the _sample_ barcode.  The example (in parentheses) talks about a _flowcell_ barcode (i.e. a unique string that identifies the flowcell)  What am I missing? 

We don't have an option to set the `BC` tag in the read group in SAM header that's true.  I'd be ok with a PR for that, and we can get that merged quickly but not sure when a release would be.

**Comment by bwlang** [comment]
formatting obscured the sample_barcode bit...  fixed that just now. 
I'll see what I can put together quickly
