### ISSUE TITLE
Illegal option: 'ExtractUmisFromBam'

### ISSUE THREAD

**Issue by Neeecolaaaa** [fulcrumgenomics/fgbio#947]
I'd love some help figuring out what could be going wrong with my code to remove UMIs from a uBAM file. I have 12 4nt long UMIs which are on the left side of all of my sequences. I couldn't find an example of this command online to help me troubleshoot on my own. Thanks!

Here is my code: 
fgbio ExtractUmisFromBam \
> --input /n/path/to/file/S2_Entire_noUntrimmed.fastq \
> --read-structure 4M+T \
> -- molecular-index-tags “AGCG, CGTC, CTGG, ACTT, GGGT, GTTA, TATG, TCGC, ACTG, GAAG, CGGA, TGCC” \
> --output /n/path/to/file/S2_Entire_noUntrimmed-UMIsOUT.fastq

This code results in this error: 

------------------------------------------------------------------------------------------------------------------------
-i PathToBam, --input=PathToBam
                              Input BAM file. 
-o PathToBam, --output=PathToBam
                              Output BAM file. 
-r ReadStructure+, --read-structure=ReadStructure+
                              The read structure, one per read in a template. 
-h [[true|false]], --help[[=true|false]]
                              Display the help message. [Default: false]. 
--version[[=true|false]]      Display the version number for this tool. [Default: false]. 
-t String*, --molecular-index-tags=String*
                              SAM tag(s) in which to store the molecular indices. [Optional]. 
-s String, --single-tag=StringSingle tag into which to concatenate all molecular indices. [Optional].
                              
-a [[true|false]], --annotate-read-names[[=true|false]]
                              Annotate the read names with the molecular indices. See usage for more details.
                              [Default: false]. 
-c String, --clipping-attribute=String
                              The SAM tag with the position in read to clip adapters (e.g. 'XT' as produced by Picard's
                              'MarkIlluminaAdapters'). [Optional]. 

Exception: ValidationException
Error: SAM tags must be of length two: “AGCG,

**Comment by nh13** [comment]
You are using the -- molecular-index-tags option incorrectly (can you please re-read the usage and option descriptions to let us know the confusion). It looks like you have fixed set of values, whereas that option is the SAM tag (typically RX) in which the 4bp UMI will be stored in the output BAM.  Try not specifying that option to produce the BAM. If you want to enforce only a fixed set of 4bp UMIs are kept, see CorrectUmis.

**Comment by Neeecolaaaa** [comment]
Thank you so much! I re-read the molecular-index-tags and then found some more information on sam tags, which helped me avoid the error I had above. FYI, running the code simply without molecular-index-tags produced this error: 
Error: At least one molecular-index-tag must be specified.
However, running with the code below stopped my original error. I am now trying to figure out how to fix that problem (which just FYI is: SAMFormatException: Error parsing SAM header. Unrecognized header record type.

fgbio ExtractUmisFromBam \
> --input /n/path/to/file/S2_Entire_noUntrimmed.fastq/S2_Entire_noUntrimmed.fastq \
> --read-structure 4M+T \
> --molecular-index-tags GC \
> --output /n/path/to/file/S2_Entire_noUntrimmed.fastq/S2_Entire_noUntrimmed-UMIsOUT.fastq

**Comment by nh13** [comment]
The input file is FASTQ, but the tool expects a BAM file (_FromBam_).    Perhaps you want to use https://fulcrumgenomics.github.io/fgbio/tools/latest/FastqToBam.html
