### ISSUE TITLE
quality score of masked N bases set to 2

### ISSUE THREAD

**Issue by tobyaicher** [fulcrumgenomics/fgbio#953]
Hi,

I wanted to confirm that when you use FilterConsensusReads and mask any bases with a quality score below a given cutoff, that the quality score of the masked bases automatically becomes 2. I see that masked bases have a quality score of 2 in my data but I wanted to confirm that this is indeed coded into fgbio. Thank you!

**Comment by nh13** [comment]
That's correct, see here:

* [single-umi/non-duplex](https://github.com/fulcrumgenomics/fgbio/blob/9c475fdb06e4f05a2a5eabe9006e0facb31726b5/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala#L282C1-L283C1)
* [duplex](https://github.com/fulcrumgenomics/fgbio/blob/9c475fdb06e4f05a2a5eabe9006e0facb31726b5/src/main/scala/com/fulcrumgenomics/umi/FilterConsensusReads.scala#L320)

And the last sentence in this section: https://github.com/fulcrumgenomics/fgbio/wiki/Calling-Consensus-Reads#adjusting-the-output-consensus-base-quality

**Comment by tobyaicher** [comment]
Ok got it thanks and it looks like the minPhred score of 2 is specified here: 

https://github.com/fulcrumgenomics/fgbio/blob/9c475fdb06e4f05a2a5eabe9006e0facb31726b5/src/main/scala/com/fulcrumgenomics/util/NumericTypes.scala
