### ISSUE TITLE
Missing space in docs

### ISSUE THREAD

**Issue by mmterpstra** [fulcrumgenomics/fgbio#965]
Missing space in docs

'ofoperators' -> 'of operators' 

Link to line:
https://github.com/fulcrumgenomics/fgbio/blob/371db03ba58538ef6b422de622fda5df8f824882/src/main/scala/com/fulcrumgenomics/umi/ExtractUmisFromBam.scala#L64

Ty for the software!

**Comment by VasLem** [comment]
Wow, that issue must be how perfection should look like for a software😃
