### ISSUE TITLE
heap memory error

### ISSUE THREAD

**Issue by subarna-slg** [fulcrumgenomics/fgbio#967]
I am trying to use clipbam option in fgbio (installed in conda env) in a bash script for clipping reads using the following commands:
$FGBIO -ClipBam -i $BAM_MD -o $BAM_MD_CLIPPED -r $ref --clip-overlapping-reads -c Hard -m ${base}"_fgbio_metrics.txt"
I am getting an error: 
[2024/02/03 04:02:32 | FgBioMain | Info] ClipBam failed. Elapsed time: 0.19 minutes.
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
please suggest

**Comment by nh13** [comment]
A quick search of previous issues will contain the solution: https://github.com/search?q=repo%3Afulcrumgenomics%2Ffgbio+heap&type=issues
