### ISSUE TITLE
GroupReadsByUmi groups reads with or without the same end.

### ISSUE THREAD

**Issue by jeanquassi** [fulcrumgenomics/fgbio#979]
Hi, 
I am working on amplicon sequencing data with UMI. 
After grouping with GroupReadsByUmi (strategy=identity), among others UMI families I get the two below(showing a couple of the reads) :

UMI family 2160
![umi family 2160](https://github.com/fulcrumgenomics/fgbio/assets/93553380/d1e0676a-31aa-420d-8b38-4199694837a3)

UMI family 4716
![umi family 4716](https://github.com/fulcrumgenomics/fgbio/assets/93553380/c8d28341-2d5c-4bc3-a1eb-df7782fda372)

 As I understand the grouping method :
The 2 families are mapped on the same amplicon, they have the same UMI sequence,  all the reads start at the same position. The only difference is seems to be their ending position; and that is their are separated in 2 families. 
 If the above assumption is true, why is the 3rd read in the family 4716 (0074-01718) grouped there since it has only length 42 compared to the others reads with a length of 138?
 
I am new using the GroupReadsByUmi and read the official instruction page. However I might have misunderstand the grouping method.
 Thank you in advance for your help.

**Comment by nh13** [comment]
If reads are from the same source molecule, then the _outer_ ends of the template are assumed to be the same.  Since you're not using paired end, then the outer ends are the start and end of each read. I'd ask if you're doing some up front quality or adapter trimming prior to grouping of the reads to make their read lengths different.

**Comment by jeanquassi** [comment]
Hi Nils, 
thank you for your swift answer. 
Indeed we do some adapter trimming before the grouping. I will check the quality of the trimming for the strange reads. 

thank you again for your help
